import { useMemo, useState } from 'react';

import { useQuery } from '@tanstack/react-query';
import { AlertTriangle, ArrowLeft, Clock3, ExternalLink, Gauge, LayoutDashboard, MoreHorizontal, Pencil, RefreshCw, ShieldCheck, SlidersHorizontal } from 'lucide-react';
import { useNavigate, useParams } from 'react-router-dom';

import './DashboardOperations.css';
import { dashboardOperationsService } from './dashboardOperations.service';
import type { DashboardPanel } from './dashboardOperations.types';
import { DashboardPanelRenderer } from './DashboardPanelRenderer';

import { HaDrawer } from '@/components/ha-drawer';
import { StatusDock } from '@/components/status-dock';
import { useEpsStream } from '@/hooks/useEpsStream';

export function DashboardViewPage(): JSX.Element {
  const {id=''}=useParams(); const navigate=useNavigate(); const eps=useEpsStream();
  const [timeRange,setTimeRange]=useState('Last 24 hours'); const [tenant,setTenant]=useState('All authorized tenants'); const [selected,setSelected]=useState<DashboardPanel|null>(null);
  const query=useQuery({queryKey:['dashboard-operations',id],queryFn:({signal})=>dashboardOperationsService.get(id,signal),enabled:Boolean(id),staleTime:30_000});
  const dashboard=query.data;
  const staleCount=useMemo(()=>dashboard?.panels.filter((panel)=>panel.state==='stale'||panel.state==='partial').length??0,[dashboard]);
  if(query.isLoading)return <section className="dsh-page"><div className="dsh-state" role="status"><Gauge size={28}/><strong>Loading operational dashboard</strong><span>Resolving definition, variables, and bounded panel projections.</span></div></section>;
  if(query.isError||!dashboard)return <section className="dsh-page"><div className="dsh-state dsh-state--error" role="alert"><AlertTriangle size={28}/><strong>Dashboard unavailable</strong><span>{query.error instanceof Error?query.error.message:'The dashboard could not be loaded.'}</span><button className="dsh-button" onClick={()=>navigate('/dashboards')}>Back to dashboards</button></div></section>;
  return <section className="dsh-page">
    <header className="dsh-header"><div className="dsh-header__identity"><button className="dsh-icon-button" type="button" onClick={()=>navigate('/dashboards')} aria-label="Back to dashboards"><ArrowLeft size={15}/></button><span className="dsh-header__mark"><LayoutDashboard size={18}/></span><div className="dsh-header__copy"><span className="dsh-eyebrow">{dashboard.managed?'MANAGED DASHBOARD':'OPERATIONAL DASHBOARD'} · v{dashboard.version??1}</span><h1>{dashboard.title}</h1></div></div><div className="dsh-header__actions"><span className="dsh-badge" data-health={dashboard.health}>{dashboard.health}</span><button className="dsh-button" type="button" onClick={()=>query.refetch()}><RefreshCw size={13}/>Refresh</button><button className="dsh-button" type="button" disabled={dashboard.managed&&!dashboardOperationsService.fixtureMode} onClick={()=>navigate(`/dashboards/${dashboard.id}/edit`)}><Pencil size={13}/>{dashboard.managed?'Clone to edit':'Edit'}</button></div></header>
    {dashboardOperationsService.fixtureMode&&<div className="dsh-trust"><ShieldCheck size={13}/><strong>Design fixture:</strong> fictional panel results are enabled for visual review. Live mode runs stored visualizations through the role-gated API.</div>}
    <div className="dsh-runtime-controls" aria-label="Dashboard context"><select className="dsh-select" value={timeRange} onChange={(event)=>setTimeRange(event.target.value)} aria-label="Time range"><option>Last 15 minutes</option><option>Last 4 hours</option><option>Last 24 hours</option><option>Last 7 days</option></select><select className="dsh-select" value={tenant} onChange={(event)=>setTenant(event.target.value)} aria-label="Tenant scope"><option>All authorized tenants</option><option>Northwind Financial</option><option>Contoso Research</option></select>{dashboard.variables.map((variable)=><select className="dsh-select" key={variable.id} defaultValue={variable.value} aria-label={variable.label}>{variable.options.map((option)=><option key={option.value} value={option.value}>{variable.label}: {option.label}</option>)}</select>)}<button className="dsh-button" type="button"><SlidersHorizontal size={13}/>Filters</button><button className="dsh-button" type="button" onClick={()=>navigate('/search')}><ExternalLink size={13}/>Open in Hunt</button></div>
    <main className="dsh-runtime"><div className="dsh-runtime-grid">{dashboard.panels.map((panel)=><article className="dsh-panel" key={panel.id} style={{gridColumn:`${panel.position.x+1} / span ${panel.position.w}`,gridRow:`${panel.position.y+1} / span ${panel.position.h}`}}><header className="dsh-panel__head"><div><h2>{panel.title}</h2><div className="dsh-panel__meta"><span>{panel.source}</span><span>·</span><span data-state={panel.state}>{panel.state}</span>{panel.updatedAt&&<><span>·</span><span>{new Date(panel.updatedAt).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</span></>}</div></div><button type="button" className="dsh-panel-menu" onClick={()=>setSelected(panel)} aria-label={`Open ${panel.title} details`}><MoreHorizontal size={14}/></button></header><div className="dsh-panel__body"><DashboardPanelRenderer panel={panel}/></div></article>)}</div></main>
    <div className="dsh-status"><span><Clock3 size={11}/>{timeRange} · {tenant}</span><strong>{staleCount?`${staleCount} panels stale or partial`:'All panels current'}</strong><span>{dashboard.panels.length} panels · {dashboard.sourceCount??0} sources</span></div><StatusDock className="dsh-status-dock" sseConnected={dashboardOperationsService.fixtureMode||eps.connected} eps={dashboardOperationsService.fixtureMode?12840:eps.eps} mode="live" lastUpdated={query.dataUpdatedAt?new Date(query.dataUpdatedAt):undefined}/>
    <HaDrawer isOpen={Boolean(selected)} onClose={()=>setSelected(null)} title={selected?.title??'Panel details'} subtitle={selected?.description} width={480} footer={selected?.drilldown?<button className="dsh-button dsh-button--primary" type="button" onClick={()=>{if(selected.drilldown)navigate(selected.drilldown);}}><ExternalLink size={13}/>Open investigation pivot</button>:undefined}>{selected&&<div><div className="dsh-readiness" data-ready={selected.state==='ready'}><strong>{selected.state==='ready'?'Projection ready':`Panel state: ${selected.state}`}</strong><br/>{selected.state==='contract_unavailable'?'This panel has no stored visualization id, so it cannot be executed.':selected.visualizationId!==undefined?'Panel results come from the authorized visualization run endpoint.':'Panel results preserve the active global context when opened.'}</div><dl><dt>Source</dt><dd>{selected.source}</dd><dt>Query contract</dt><dd>{selected.queryLabel}</dd><dt>Freshness</dt><dd>{selected.updatedAt?new Date(selected.updatedAt).toLocaleString():'Not reported'}</dd><dt>Layout</dt><dd>{selected.position.w} × {selected.position.h}</dd></dl></div>}</HaDrawer>
  </section>;
}
