import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        surface: {
          ground:         "var(--surface-ground)",
          primary:        "var(--surface-primary)",
          secondary:      "var(--surface-secondary)",
          tertiary:       "var(--surface-tertiary)",
          elevated:       "var(--surface-elevated)",
          border:         "var(--surface-border)",
          "border-strong": "var(--surface-border-strong)",
          "border-focus":  "var(--surface-border-focus)",
        },
        brand: {
          DEFAULT:  "var(--brand-primary)",
          hover:    "var(--brand-primary-hover)",
          subtle:   "var(--brand-primary-subtle)",
          glow:     "var(--brand-primary-glow)",
          secondary: "var(--brand-secondary)",
          "secondary-subtle": "var(--brand-secondary-subtle)",
          accent:   "var(--brand-accent)",
        },
        severity: {
          critical: "var(--color-critical)",
          "critical-subtle": "var(--color-critical-subtle)",
          high:     "var(--color-high)",
          "high-subtle": "var(--color-high-subtle)",
          medium:   "var(--color-medium)",
          "medium-subtle": "var(--color-medium-subtle)",
          low:      "var(--color-low)",
          "low-subtle": "var(--color-low-subtle)",
          info:     "var(--color-info)",
          "info-subtle": "var(--color-info-subtle)",
        },
        status: {
          ingesting: "var(--color-ingesting)",
          degraded:  "var(--color-degraded)",
          offline:   "var(--color-offline)",
        },
        success:  "var(--color-success)",
        warning:  "var(--color-warning)",
        danger:   "var(--color-danger)",
        chart: {
          1: "var(--chart-1)",
          2: "var(--chart-2)",
          3: "var(--chart-3)",
          4: "var(--chart-4)",
          5: "var(--chart-5)",
          6: "var(--chart-6)",
          7: "var(--chart-7)",
          8: "var(--chart-8)",
        },
      },
      textColor: {
        primary:   "var(--text-primary)",
        secondary: "var(--text-secondary)",
        muted:     "var(--text-muted)",
        disabled:  "var(--text-disabled)",
        inverse:   "var(--text-inverse)",
        brand:     "var(--text-brand)",
        critical:  "var(--text-critical)",
        success:   "var(--text-success)",
      },
      fontFamily: {
        sans: ["Inter", "var(--font-sans)", "-apple-system", "BlinkMacSystemFont", "sans-serif"],
        mono: ["JetBrains Mono", "var(--font-mono)", "Fira Code", "Consolas", "monospace"],
        display: ["Inter", "sans-serif"],
      },
      fontSize: {
        display: ["2.5rem", { lineHeight: "1.1", fontWeight: "700", letterSpacing: "-0.02em" }],
        h1: ["1.5rem",  { lineHeight: "1.3", fontWeight: "600", letterSpacing: "-0.01em" }],
        h2: ["1.25rem", { lineHeight: "1.35", fontWeight: "600" }],
        h3: ["1rem",    { lineHeight: "1.4", fontWeight: "500" }],
        h4: ["0.875rem",{ lineHeight: "1.5", fontWeight: "500" }],
        body: ["0.875rem", { lineHeight: "1.6", fontWeight: "400" }],
        small: ["0.75rem", { lineHeight: "1.5", fontWeight: "400" }],
        tiny:  ["0.6875rem",{ lineHeight: "1.4", fontWeight: "400" }],
        micro: ["0.625rem", { lineHeight: "1.3", fontWeight: "500" }],
      },
      borderRadius: {
        sm:   "3px",
        md:   "6px",
        lg:   "8px",
        xl:   "12px",
        "2xl": "16px",
        pill: "999px",
      },
      boxShadow: {
        card:     "0 1px 3px rgba(0,0,0,0.4), 0 1px 2px rgba(0,0,0,0.3)",
        elevated: "0 4px 16px rgba(0,0,0,0.5)",
        dropdown: "0 8px 32px rgba(0,0,0,0.6), 0 2px 8px rgba(0,0,0,0.4)",
        glow:     "0 0 16px var(--brand-primary-glow)",
        "glow-critical": "0 0 12px var(--color-critical-glow)",
        "glow-success":  "0 0 12px var(--color-success-subtle)",
        drawer:   "-4px 0 32px rgba(0,0,0,0.6)",
      },
      spacing: {
        sidebar:            "260px",
        "sidebar-collapsed": "64px",
        topbar:              "56px",
        statusbar:           "32px",
        "shell-top":         "88px",
      },
      zIndex: {
        statusbar:    "50",
        topbar:       "40",
        sidebar:      "40",
        dropdown:     "100",
        overlay:      "200",
        modal:        "300",
        toast:        "400",
        command:      "500",
      },
      animation: {
        shimmer:         "shimmerMove 1.6s ease-in-out infinite",
        "data-pulse":    "dataPulse 2s ease-in-out infinite",
        "live-glow":     "liveGlow 2s ease-in-out infinite",
        "slide-in-right":"slideInRight 0.28s cubic-bezier(0.4,0,0.2,1)",
        "slide-in-left": "slideInLeft 0.28s cubic-bezier(0.4,0,0.2,1)",
        "slide-in-up":   "slideInUp 0.2s cubic-bezier(0.4,0,0.2,1)",
        "slide-in-down": "slideInDown 0.2s cubic-bezier(0.4,0,0.2,1)",
        "fade-in":       "fadeIn 0.2s cubic-bezier(0.4,0,0.2,1)",
        "scale-in":      "scaleIn 0.15s cubic-bezier(0.34,1.56,0.64,1)",
        "pulse-ring":    "pulseRing 2s ease-out infinite",
        "spin-slow":     "spin 3s linear infinite",
      },
      keyframes: {
        shimmerMove: {
          "0%":   { transform: "translateX(-100%)" },
          "100%": { transform: "translateX(100%)" },
        },
        dataPulse: {
          "0%, 100%": { opacity: "1" },
          "50%":      { opacity: "0.4" },
        },
        liveGlow: {
          "0%, 100%": { boxShadow: "0 0 4px var(--color-ingesting-glow)" },
          "50%":      { boxShadow: "0 0 10px var(--color-ingesting-glow), 0 0 20px var(--color-ingesting-glow)" },
        },
        slideInRight: {
          from: { transform: "translateX(100%)", opacity: "0" },
          to:   { transform: "translateX(0)",    opacity: "1" },
        },
        slideInLeft: {
          from: { transform: "translateX(-100%)", opacity: "0" },
          to:   { transform: "translateX(0)",     opacity: "1" },
        },
        slideInUp: {
          from: { transform: "translateY(12px)", opacity: "0" },
          to:   { transform: "translateY(0)",    opacity: "1" },
        },
        slideInDown: {
          from: { transform: "translateY(-8px)", opacity: "0" },
          to:   { transform: "translateY(0)",    opacity: "1" },
        },
        fadeIn: {
          from: { opacity: "0" },
          to:   { opacity: "1" },
        },
        scaleIn: {
          from: { transform: "scale(0.95)", opacity: "0" },
          to:   { transform: "scale(1)",    opacity: "1" },
        },
        pulseRing: {
          "0%":         { transform: "scale(1)", opacity: "0.6" },
          "70%, 100%":  { transform: "scale(1.08)", opacity: "0" },
        },
      },
      transitionTimingFunction: {
        spring: "cubic-bezier(0.34, 1.56, 0.64, 1)",
        smooth: "cubic-bezier(0.4, 0, 0.2, 1)",
      },
    },
  },
  plugins: [],
};

export default config;
