import { useEffect, useMemo, useState } from 'react';

import { useQuery } from '@tanstack/react-query';
import { Activity, AlertTriangle, ArrowRight, Boxes, Braces, CheckCircle2, ChevronRight, CircleSlash2, Clock3, Code2, Database, FileWarning, Gauge, Network, Plus, RadioTower, RefreshCw, RotateCcw, Search, ServerCog, ShieldCheck, X } from 'lucide-react';
import { useNavigate } from 'react-router-dom';

import './PipelineOperations.css';
import { pipelineOperationsService } from './pipelineOperations.service';
import type { OperationalState, PipelineFailureGroup, PipelineOperationsInventory, PipelineParser, PipelineSource, PipelineStage, PipelineView } from './pipelineOperations.types';

import { StatusDock } from '@/components/status-dock';
import { useEpsStream } from '@/hooks/useEpsStream';
import { useAuthStore } from '@/store/auth.store';

type SelectedRecord={kind:'source';value:PipelineSource}|{kind:'parser';value:PipelineParser}|{kind:'failure';value:PipelineFailureGroup};

const viewRoutes:Record<PipelineView,string>={overview:'/admin/pipeline-signals',sources:'/inputs/sources',parsers:'/admin/data-parsing',failures:'/admin/pipeline-signals?view=failures',capacity:'/admin/pipeline-signals?view=capacity'};
const fmtNumber=(value:number|null):string=>value===null?'Not reported':new Intl.NumberFormat(undefined,{maximumFractionDigits:1}).format(value);
const fmtDate=(value:string|null|undefined):string=>value?new Intl.DateTimeFormat(undefined,{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}).format(new Date(value)):'Not reported';
const fmtBytes=(value:number|null|undefined):string=>{if(value===null||value===undefined)return'Not reported';const units=['B','KB','MB','GB','TB'];let size=value;let unit=0;while(size>=1024&&unit<units.length-1){size/=1024;unit+=1;}return`${size.toFixed(unit>1?2:1)} ${units[unit]}`;};
const stateIcon=(state:OperationalState):JSX.Element=>state==='attention'||state==='unavailable'?<AlertTriangle size={12}/>:state==='not_reported'?<CircleSlash2 size={12}/>:<CheckCircle2 size={12}/>;

export function PipelineOperationsPage({initialView='overview'}:{initialView?:PipelineView}):JSX.Element{
  const navigate=useNavigate();const eps=useEpsStream();const {hasAnyRole,hasRole}=useAuthStore();
  const canView=hasAnyRole(['ROLE_ADMIN','ROLE_ANALYST']);const canManage=hasRole('ROLE_ADMIN');
  const [view,setView]=useState<PipelineView>(initialView);const [query,setQuery]=useState('');const [stateFilter,setStateFilter]=useState('all');const [selected,setSelected]=useState<SelectedRecord>();const [onboarding,setOnboarding]=useState(false);const [replay,setReplay]=useState<PipelineFailureGroup>();
  const inventoryQuery=useQuery({queryKey:['pipeline-operations'],queryFn:({signal})=>pipelineOperationsService.list(signal),enabled:canView,staleTime:30_000,refetchInterval:60_000});
  const inventory=inventoryQuery.data;
  useEffect(()=>setView(initialView),[initialView]);
  const filteredSources=useMemo(()=>filterRows(inventory?.sources??[],query,stateFilter),[inventory?.sources,query,stateFilter]);
  const filteredParsers=useMemo(()=>filterRows(inventory?.parsers??[],query,stateFilter),[inventory?.parsers,query,stateFilter]);
  const filteredFailures=useMemo(()=>{const needle=query.trim().toLocaleLowerCase();return(inventory?.failures??[]).filter((item)=>(stateFilter==='all'||item.status===stateFilter)&&(!needle||JSON.stringify(item).toLocaleLowerCase().includes(needle)));},[inventory?.failures,query,stateFilter]);
  const rowIds=useMemo(()=>view==='sources'?filteredSources.map((item)=>item.id):view==='parsers'?filteredParsers.map((item)=>item.id):view==='failures'?filteredFailures.map((item)=>item.id):[],[filteredFailures,filteredParsers,filteredSources,view]);
  useEffect(()=>{const listener=(event:KeyboardEvent):void=>{const tag=(event.target as HTMLElement).tagName;if(['INPUT','SELECT','TEXTAREA'].includes(tag))return;if(event.key==='Escape'){setSelected(undefined);setOnboarding(false);setReplay(undefined);return;}if(!['j','k','J','K'].includes(event.key)||rowIds.length===0)return;event.preventDefault();const current=selected?.value.id;const index=current?rowIds.indexOf(current):-1;const next=event.key.toLocaleLowerCase()==='j'?Math.min(index+1,rowIds.length-1):Math.max(index-1,0);const id=rowIds[next];if(view==='sources'){const value=filteredSources.find((item)=>item.id===id);if(value)setSelected({kind:'source',value});}if(view==='parsers'){const value=filteredParsers.find((item)=>item.id===id);if(value)setSelected({kind:'parser',value});}if(view==='failures'){const value=filteredFailures.find((item)=>item.id===id);if(value)setSelected({kind:'failure',value});}};window.addEventListener('keydown',listener);return()=>window.removeEventListener('keydown',listener);},[filteredFailures,filteredParsers,filteredSources,rowIds,selected,view]);
  const changeView=(next:PipelineView):void=>{setView(next);setSelected(undefined);setQuery('');setStateFilter('all');navigate(viewRoutes[next]);};
  if(!canView)return <section className="pipe-page"><Header canManage={false} onAdd={()=>undefined} onRefresh={()=>undefined}/><State icon={<CircleSlash2 size={30}/>} title="Pipeline operations access restricted" detail="Data-pipeline operations require Analyst or Platform Administrator. Ask an administrator for an authorized role."/></section>;
  const receiving=inventory?.sources.filter((item)=>item.enabled&&(item.state==='healthy'||item.state==='observed')).length??0;
  const attention=inventory?.sources.filter((item)=>item.state==='attention'||item.state==='unavailable').length??0;
  const parsersReady=inventory?.parsers.filter((item)=>item.state==='healthy'||item.state==='observed').length??0;
  const failedEvents=inventory?.failures.filter((item)=>item.status==='open'||item.status==='reviewing').reduce((sum,item)=>sum+item.count,0)??0;
  return <section className="pipe-page">
    <Header canManage={canManage} onAdd={()=>setOnboarding(true)} onRefresh={()=>inventoryQuery.refetch()}/>
    {pipelineOperationsService.fixtureMode&&<div className="pipe-trust"><ShieldCheck size={13}/><strong>Design fixture:</strong> fictional source, parser and failure records are enabled for visual review. Production never receives these records.</div>}
    <section className="pipe-summary" aria-label="Pipeline operations summary"><div><span>Configured sources</span><strong>{inventory?.sources.length??0}</strong><small>{inventory?.bounded?'bounded projection':'loaded legacy set'}</small></div><div data-tone="healthy"><span>Receiving</span><strong>{receiving}</strong><small>directly observed state</small></div><div data-tone={attention?'warning':undefined}><span>Source attention</span><strong>{attention}</strong><small>dependency or freshness</small></div><div><span>Parsers ready</span><strong>{parsersReady}</strong><small>configuration/runtime state</small></div><div data-tone={failedEvents?'warning':undefined}><span>Failed events</span><strong>{failedEvents}</strong><small>loaded failure groups</small></div><div><span>Soak evidence</span><strong>{inventory?.signals?.soakSampleCount??'—'}</strong><small>{inventory?.signals?.soakSpanHours===null||inventory?.signals?.soakSpanHours===undefined?'span not reported':`${inventory.signals.soakSpanHours.toFixed(1)}h measured span`}</small></div></section>
    <Tabs view={view} inventory={inventory} onChange={changeView}/>
    {(view==='sources'||view==='parsers'||view==='failures')&&<Toolbar view={view} query={query} state={stateFilter} onQuery={setQuery} onState={setStateFilter} onRefresh={()=>inventoryQuery.refetch()} snapshotAt={inventory?.snapshotAt}/>}
    <main className="pipe-main" data-drawer={Boolean(selected)}><section className="pipe-workspace">
      {inventoryQuery.isLoading?<State icon={<Activity size={28}/>} title="Loading pipeline operations" detail="Retrieving the authorized source-to-index projection."/>:inventoryQuery.isError?<State error icon={<AlertTriangle size={28}/>} title="Pipeline operations unavailable" detail={inventoryQuery.error instanceof Error?inventoryQuery.error.message:'The operational projection could not be loaded.'} action={()=>inventoryQuery.refetch()}/>:view==='overview'?<Overview inventory={inventory}/>:view==='sources'?<Sources rows={filteredSources} selected={selected?.value.id} onSelect={(value)=>setSelected({kind:'source',value})}/>:view==='parsers'?<Parsers rows={filteredParsers} selected={selected?.value.id} onSelect={(value)=>setSelected({kind:'parser',value})}/>:view==='failures'?<Failures rows={filteredFailures} selected={selected?.value.id} onSelect={(value)=>setSelected({kind:'failure',value})}/>:<Capacity inventory={inventory}/>}
    </section>{selected&&<Detail record={selected} canManage={canManage} onReplay={(failure)=>setReplay(failure)} onClose={()=>setSelected(undefined)}/>}</main>
    <div className="pipe-status"><span><ShieldCheck size={11}/>Replay never occurs without a bounded preview, authorization and audit</span><strong>{inventory?.partial?inventory.warnings[0]:pipelineOperationsService.fixtureMode?'Fixture lifecycle · no events reprocessed':'Measured projection current'}</strong><span>{inventory?.tenantScoped?'Authorized tenant scope':'Tenant scope not proven'}</span></div><StatusDock className="pipe-status-dock" sseConnected={pipelineOperationsService.fixtureMode||eps.connected} eps={pipelineOperationsService.fixtureMode?12840:eps.eps} mode="historical" lastUpdated={inventoryQuery.dataUpdatedAt?new Date(inventoryQuery.dataUpdatedAt):undefined}/>
    {onboarding&&<OnboardingDialog canSubmit={false} onClose={()=>setOnboarding(false)}/>} {replay&&<ReplayDialog failure={replay} onClose={()=>setReplay(undefined)}/>}
  </section>;
}

function filterRows<T extends {state:OperationalState}>(rows:T[],query:string,state:string):T[]{const needle=query.trim().toLocaleLowerCase();return rows.filter((item)=>(state==='all'||item.state===state)&&(!needle||JSON.stringify(item).toLocaleLowerCase().includes(needle)));}
function Header({canManage,onAdd,onRefresh}:{canManage:boolean;onAdd:()=>void;onRefresh:()=>void}):JSX.Element{return <header className="pipe-header"><div className="pipe-header__identity"><span className="pipe-header__mark"><Network size={18}/></span><div><span className="pipe-eyebrow">OPERATE · DATA PIPELINE</span><h1>Pipeline &amp; Ingestion</h1></div></div><div className="pipe-header__actions"><span className="pipe-shortcut"><kbd>J</kbd>/<kbd>K</kbd> navigate <kbd>Esc</kbd> close</span><button className="pipe-button" type="button" onClick={onRefresh}><RefreshCw size={13}/>Refresh</button><button className="pipe-button pipe-button--primary" type="button" disabled={!canManage} onClick={onAdd}><Plus size={14}/>Add source</button></div></header>}
function Tabs({view,inventory,onChange}:{view:PipelineView;inventory?:PipelineOperationsInventory;onChange:(view:PipelineView)=>void}):JSX.Element{return <nav className="pipe-tabs" aria-label="Pipeline operations workspace">{([{id:'overview',label:'Flow',icon:<Network size={13}/>,count:inventory?.stages.length??0},{id:'sources',label:'Sources',icon:<RadioTower size={13}/>,count:inventory?.sources.length??0},{id:'parsers',label:'Parsers',icon:<Braces size={13}/>,count:inventory?.parsers.length??0},{id:'failures',label:'Failures',icon:<FileWarning size={13}/>,count:inventory?.failures.length??0},{id:'capacity',label:'Capacity',icon:<Gauge size={13}/>,count:inventory?.signals?.soakSampleCount??0}] as const).map((tab)=><button key={tab.id} type="button" role="tab" aria-selected={view===tab.id} onClick={()=>onChange(tab.id)}>{tab.icon}{tab.label}<small>{tab.count}</small></button>)}</nav>}
function Toolbar({view,query,state,onQuery,onState,onRefresh,snapshotAt}:{view:PipelineView;query:string;state:string;onQuery:(value:string)=>void;onState:(value:string)=>void;onRefresh:()=>void;snapshotAt?:string}):JSX.Element{return <div className="pipe-toolbar"><label className="pipe-search"><Search size={13}/><input value={query} onChange={(event)=>onQuery(event.target.value)} aria-label={`Search ${view}`} placeholder={`Search ${view}…`}/></label><select className="pipe-select" value={state} onChange={(event)=>onState(event.target.value)} aria-label={`Filter ${view} state`}><option value="all">All states</option>{view==='failures'?<><option value="open">Open</option><option value="reviewing">Reviewing</option><option value="replayed">Replayed</option></>:<><option value="observed">Observed</option><option value="healthy">Healthy</option><option value="attention">Needs attention</option><option value="unavailable">Unavailable</option><option value="not_reported">Not reported</option></>}</select><button className="pipe-icon-button" type="button" aria-label="Refresh current pipeline view" onClick={onRefresh}><RefreshCw size={13}/></button><span className="pipe-toolbar__end">Snapshot {fmtDate(snapshotAt)} · bounded filters</span></div>}

function Overview({inventory}:{inventory?:PipelineOperationsInventory}):JSX.Element{if(!inventory)return <></>;return <div className="pipe-overview"><section className="pipe-section-head"><div><strong>Source-to-index flow</strong><span>Direct measurements and explicit contract gaps</span></div><span>No inferred SLO thresholds</span></section><div className="pipe-stage-flow">{inventory.stages.map((stage,index)=><div className="pipe-stage-wrap" key={stage.id}><StageCard stage={stage}/>{index<inventory.stages.length-1&&<ArrowRight className="pipe-stage-arrow" size={15}/>}</div>)}</div><div className="pipe-overview-grid"><section className="pipe-panel"><header><div><strong>Operational attention</strong><span>Actionable conditions in the loaded projection</span></div><AlertTriangle size={15}/></header><ul className="pipe-attention">{inventory.sources.filter((item)=>item.state==='attention'||item.state==='unavailable').map((item)=><li key={item.id}><i data-state={item.state}/><div><strong>{item.name}</strong><span>{item.stateLabel} · last event {fmtDate(item.lastEventAt)}</span></div><ChevronRight size={13}/></li>)}{inventory.failures.slice(0,3).map((item)=><li key={item.id}><i data-state="attention"/><div><strong>{item.reasonCode}</strong><span>{item.count} events · {item.source}</span></div><ChevronRight size={13}/></li>)}{!inventory.sources.some((item)=>item.state==='attention'||item.state==='unavailable')&&inventory.failures.length===0&&<li><div><strong>No loaded attention conditions</strong><span>This is not proof that every source is healthy.</span></div></li>}</ul></section><section className="pipe-panel"><header><div><strong>Trust boundary</strong><span>What this workspace can establish</span></div><ShieldCheck size={15}/></header><dl className="pipe-metrics"><div><dt>Inventory bound</dt><dd>{inventory.bounded?'Reported':'Not reported'}</dd></div><div><dt>Tenant scope</dt><dd>{inventory.tenantScoped?'Authorized':'Not proven'}</dd></div><div><dt>Replay authority</dt><dd>Contract pending</dd></div><div><dt>Failure payloads</dt><dd>Redacted summaries only</dd></div><div><dt>Runtime thresholds</dt><dd>Not configured</dd></div></dl></section></div></div>}
function StageCard({stage}:{stage:PipelineStage}):JSX.Element{return <article className="pipe-stage" data-state={stage.state}><header><span>{stage.label}</span>{stateIcon(stage.state)}</header><strong>{stage.stateLabel}</strong><small>{stage.detail}</small><dl><div><dt>EPS</dt><dd>{fmtNumber(stage.throughput)}</dd></div><div><dt>Backlog</dt><dd>{fmtNumber(stage.backlog)}</dd></div><div><dt>Failures</dt><dd>{fmtNumber(stage.failures)}</dd></div></dl><footer>{stage.evidence}</footer></article>}

function Sources({rows,selected,onSelect}:{rows:PipelineSource[];selected?:string;onSelect:(row:PipelineSource)=>void}):JSX.Element{return <TableState empty={rows.length===0} label="source"><table className="pipe-table"><thead><tr><th>Source</th><th>State</th><th>EPS</th><th>Last event</th><th>Parser</th><th>Coverage</th><th>Queue</th><th><span className="sr-only">Open</span></th></tr></thead><tbody>{rows.map((row)=><tr key={row.id} tabIndex={0} data-selected={selected===row.id} onClick={()=>onSelect(row)} onKeyDown={(event)=>activate(event,()=>onSelect(row))}><td><div className="pipe-cell-title"><SourceIcon type={row.type}/><div><strong>{row.name}</strong><small>{row.type} · {row.transport}</small></div></div></td><td><StateBadge state={row.state} label={row.stateLabel}/></td><td className="pipe-mono">{fmtNumber(row.eps)}</td><td className="pipe-mono">{fmtDate(row.lastEventAt)}</td><td>{row.parser??'Not reported'}<small className="pipe-cell-sub">{row.parserVersion??''}</small></td><td className="pipe-mono">{row.normalizedCoverage===null?'—':`${row.normalizedCoverage.toFixed(1)}%`}</td><td className="pipe-mono">{fmtNumber(row.queueDepth)}</td><td><ChevronRight size={13}/></td></tr>)}</tbody></table></TableState>}
function Parsers({rows,selected,onSelect}:{rows:PipelineParser[];selected?:string;onSelect:(row:PipelineParser)=>void}):JSX.Element{return <TableState empty={rows.length===0} label="parser"><table className="pipe-table"><thead><tr><th>Parser</th><th>State</th><th>Version</th><th>Matched · 24h</th><th>Failed · 24h</th><th>Success</th><th>Field coverage</th><th><span className="sr-only">Open</span></th></tr></thead><tbody>{rows.map((row)=><tr key={row.id} tabIndex={0} data-selected={selected===row.id} onClick={()=>onSelect(row)} onKeyDown={(event)=>activate(event,()=>onSelect(row))}><td><div className="pipe-cell-title"><Code2 size={14}/><div><strong>{row.name}</strong><small>{row.dataType} · {row.schema}</small></div></div></td><td><StateBadge state={row.state} label={row.stateLabel}/></td><td className="pipe-mono">{row.version}</td><td className="pipe-mono">{fmtNumber(row.matched24h)}</td><td className="pipe-mono">{fmtNumber(row.failed24h)}</td><td className="pipe-mono">{row.successRate===null?'—':`${row.successRate.toFixed(2)}%`}</td><td className="pipe-mono">{row.fieldCoverage===null?'—':`${row.fieldCoverage.toFixed(1)}%`}</td><td><ChevronRight size={13}/></td></tr>)}</tbody></table></TableState>}
function Failures({rows,selected,onSelect}:{rows:PipelineFailureGroup[];selected?:string;onSelect:(row:PipelineFailureGroup)=>void}):JSX.Element{return <TableState empty={rows.length===0} label="failure group"><table className="pipe-table"><thead><tr><th>Failure group</th><th>Channel</th><th>Source</th><th>Stage</th><th>Count</th><th>Last seen</th><th>Status</th><th><span className="sr-only">Open</span></th></tr></thead><tbody>{rows.map((row)=><tr key={row.id} tabIndex={0} data-selected={selected===row.id} onClick={()=>onSelect(row)} onKeyDown={(event)=>activate(event,()=>onSelect(row))}><td><div className="pipe-cell-title"><FileWarning size={14}/><div><strong>{row.reasonCode}</strong><small>{row.reason}</small></div></div></td><td><span className="pipe-badge">{row.channel}</span></td><td>{row.source}</td><td>{row.stage}</td><td className="pipe-mono">{row.count}</td><td className="pipe-mono">{fmtDate(row.lastSeenAt)}</td><td><span className="pipe-badge" data-state={row.status}>{row.status}</span></td><td><ChevronRight size={13}/></td></tr>)}</tbody></table></TableState>}
function TableState({empty,label,children}:{empty:boolean;label:string;children:JSX.Element}):JSX.Element{return <div className="pipe-table-wrap">{empty?<State icon={<Search size={27}/>} title={`No ${label}s in this view`} detail={`Clear the filters or wait for the authorized ${label} projection.`}/>:children}</div>}
function activate(event:React.KeyboardEvent,action:()=>void):void{if(event.key==='Enter'||event.key===' '){event.preventDefault();action();}}
function SourceIcon({type}:{type:string}):JSX.Element{if(type==='agent'||type==='wineventlog')return <ServerCog size={14}/>;if(type==='aws'||type==='azure'||type==='gcp')return <Boxes size={14}/>;if(type==='kafka')return <Database size={14}/>;return <RadioTower size={14}/>}
function StateBadge({state,label}:{state:OperationalState;label:string}):JSX.Element{return <span className="pipe-state" data-state={state}>{stateIcon(state)}{label}</span>}

function Capacity({inventory}:{inventory?:PipelineOperationsInventory}):JSX.Element{const signals=inventory?.signals;if(!signals)return <State icon={<Gauge size={28}/>} title="Capacity signals unavailable" detail="The measured pipeline-signals endpoint did not return a projection."/>;return <div className="pipe-capacity"><section className="pipe-capacity-grid"><Metric label="Backend" value={signals.backendStatus}/><Metric label="OpenSearch" value={signals.opensearchStatus??'Not reported'}/><Metric label="Unassigned shards" value={fmtNumber(signals.opensearchUnassignedShards)}/><Metric label="OpenSearch store" value={fmtBytes(signals.opensearchStoreBytes)}/><Metric label="PostgreSQL store" value={fmtBytes(signals.postgresHivearmorBytes)}/><Metric label="Soak span" value={signals.soakSpanHours===null?'Not reported':`${signals.soakSpanHours.toFixed(2)} h`}/></section><section className="pipe-panel pipe-panel--history"><header><div><strong>Measured soak history</strong><span>Host sampler files · no configured SLO pass/fail interpretation</span></div><Clock3 size={15}/></header><div className="pipe-table-wrap"><table className="pipe-table pipe-table--history"><thead><tr><th>Recorded</th><th>OpenSearch</th><th>Store</th><th>Consumer lag</th><th>Sample</th></tr></thead><tbody>{[...signals.soakHistory].reverse().map((row,index)=><tr key={row.sampleFile??row.recordedAt??index}><td className="pipe-mono">{fmtDate(row.recordedAt)}</td><td>{row.opensearchStatus??'Not reported'}</td><td className="pipe-mono">{fmtBytes(row.opensearchStoreBytes)}</td><td className="pipe-mono">{fmtNumber(row.consumerLag)}</td><td className="pipe-mono">{row.sampleFile??'—'}</td></tr>)}</tbody></table></div></section></div>}
function Metric({label,value}:{label:string;value:string}):JSX.Element{return <article><span>{label}</span><strong>{value}</strong></article>}

function Detail({record,canManage,onReplay,onClose}:{record:SelectedRecord;canManage:boolean;onReplay:(failure:PipelineFailureGroup)=>void;onClose:()=>void}):JSX.Element{const value=record.value;return <aside className="pipe-drawer" aria-label="Pipeline record context"><header className="pipe-drawer__head"><div><strong>{record.kind==='failure'?(value as PipelineFailureGroup).reasonCode:(value as PipelineSource|PipelineParser).name}</strong><small>{record.kind} · {value.id}</small></div><button className="pipe-icon-button" type="button" aria-label="Close pipeline context" onClick={onClose}><X size={13}/></button></header><div className="pipe-drawer__scroll">{record.kind==='source'?<SourceDetail source={value as PipelineSource}/>:record.kind==='parser'?<ParserDetail parser={value as PipelineParser}/>:<FailureDetail failure={value as PipelineFailureGroup}/>}<div className="pipe-notice">Authoritative edits, deployment, source tests and replay require versioned backend contracts with tenant authorization and immutable audit.</div><div className="pipe-drawer__actions"><button className="pipe-button" type="button" disabled>View diagnostics</button><button className="pipe-button" type="button" disabled={!canManage}>Edit configuration</button>{record.kind==='failure'&&<button className="pipe-button pipe-button--primary" type="button" onClick={()=>onReplay(value as PipelineFailureGroup)}>Preview replay</button>}</div></div></aside>}
function SourceDetail({source}:{source:PipelineSource}):JSX.Element{return <><div className="pipe-drawer__meta"><StateBadge state={source.state} label={source.stateLabel}/><span className="pipe-badge">{source.type}</span></div><Card title="Collection and trust"><DL rows={[['Transport',source.transport],['Identity',source.identity],['Acknowledgement',source.acknowledgement],['Tenant scope',source.tenantScope]]}/></Card><Card title="Data quality"><DL rows={[['Parser',source.parser??'Not reported'],['Parser version',source.parserVersion??'Not reported'],['Normalized coverage',source.normalizedCoverage===null?'Not reported':`${source.normalizedCoverage.toFixed(1)}%`],['Last event',fmtDate(source.lastEventAt)]]}/></Card></>}
function ParserDetail({parser}:{parser:PipelineParser}):JSX.Element{return <><div className="pipe-drawer__meta"><StateBadge state={parser.state} label={parser.stateLabel}/><span className="pipe-badge">{parser.version}</span></div><Card title="Runtime readiness"><DL rows={[['Schema',parser.schema],['Deployment',parser.deployment],['Sources',fmtNumber(parser.sources)],['P95 latency',parser.latencyP95Ms===null?'Not reported':`${parser.latencyP95Ms.toFixed(1)} ms`]]}/></Card><Card title="Quality window"><DL rows={[['Matched · 24h',fmtNumber(parser.matched24h)],['Failed · 24h',fmtNumber(parser.failed24h)],['Success',parser.successRate===null?'Not reported':`${parser.successRate.toFixed(2)}%`],['Field coverage',parser.fieldCoverage===null?'Not reported':`${parser.fieldCoverage.toFixed(1)}%`]]}/></Card></>}
function FailureDetail({failure}:{failure:PipelineFailureGroup}):JSX.Element{return <><div className="pipe-drawer__meta"><span className="pipe-badge">{failure.channel}</span><span className="pipe-badge" data-state={failure.status}>{failure.status}</span></div><Card title="Failure provenance"><p>{failure.reason}</p><DL rows={[['Source',failure.source],['Stage',failure.stage],['Events',String(failure.count)],['Parser version',failure.parserVersion??'Not applicable'],['Tenant scope',failure.tenantScope]]}/></Card><Card title="Replay eligibility"><DL rows={[['Retryable',failure.retryable?'Yes · preview required':'No'],['Payload',failure.redacted?'Redacted in this view':'Not reported'],['First seen',fmtDate(failure.firstSeenAt)],['Last seen',fmtDate(failure.lastSeenAt)]]}/></Card></>}
function Card({title,children}:{title:string;children:React.ReactNode}):JSX.Element{return <section className="pipe-card"><h3>{title}</h3>{children}</section>}
function DL({rows}:{rows:[string,string][]}):JSX.Element{return <dl>{rows.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>}
function State({icon,title,detail,error=false,action}:{icon:JSX.Element;title:string;detail:string;error?:boolean;action?:()=>void}):JSX.Element{return <div className={`pipe-empty ${error?'pipe-empty--error':''}`} role={error?'alert':'status'}>{icon}<strong>{title}</strong><span>{detail}</span>{action&&<button className="pipe-button" type="button" onClick={action}>Retry</button>}</div>}

function OnboardingDialog({canSubmit,onClose}:{canSubmit:boolean;onClose:()=>void}):JSX.Element{return <div className="pipe-dialog-backdrop" role="presentation" onMouseDown={(event)=>{if(event.target===event.currentTarget)onClose();}}><section className="pipe-dialog" role="dialog" aria-modal="true" aria-labelledby="pipeline-onboarding-title"><header><div><span className="pipe-eyebrow">GOVERNED ONBOARDING</span><h2 id="pipeline-onboarding-title">Add data source</h2></div><button className="pipe-icon-button" type="button" aria-label="Close" onClick={onClose}><X size={13}/></button></header><div className="pipe-dialog__body"><div className="pipe-stepper"><span data-active="true">1 Source</span><span>2 Identity</span><span>3 Parse</span><span>4 Validate</span></div><div className="pipe-form-grid"><label className="pipe-field"><span>Source family</span><select defaultValue="syslog"><option value="syslog">Syslog / CEF / LEEF</option><option value="agent">Endpoint agent</option><option value="cloud">Cloud audit</option><option value="stream">Kafka / Event Hub</option></select></label><label className="pipe-field"><span>Tenant scope</span><select><option>All authorized tenants</option></select></label><label className="pipe-field pipe-field--wide"><span>Display name</span><input placeholder="e.g. Production firewall estate"/></label><label className="pipe-field"><span>Transport security</span><select><option>Mutual TLS</option><option>Signed workload identity</option></select></label><label className="pipe-field"><span>Acknowledgement</span><select><option>Durable broker acknowledgement</option></select></label></div><div className="pipe-notice">The current POST source endpoint is in-memory and cannot establish durable tenant ownership, secret lifecycle, validation receipts or rollback. Registration is withheld until the canonical contract is implemented.</div></div><footer><button className="pipe-button" type="button" onClick={onClose}>Cancel</button><button className="pipe-button pipe-button--primary" type="button" disabled={!canSubmit}>Continue to identity</button></footer></section></div>}
function ReplayDialog({failure,onClose}:{failure:PipelineFailureGroup;onClose:()=>void}):JSX.Element{return <div className="pipe-dialog-backdrop" role="presentation" onMouseDown={(event)=>{if(event.target===event.currentTarget)onClose();}}><section className="pipe-dialog" role="dialog" aria-modal="true" aria-labelledby="pipeline-replay-title"><header><div><span className="pipe-eyebrow">SAFE REPLAY PREVIEW</span><h2 id="pipeline-replay-title">Review {failure.reasonCode}</h2></div><button className="pipe-icon-button" type="button" aria-label="Close" onClick={onClose}><X size={13}/></button></header><div className="pipe-dialog__body"><section className="pipe-replay-summary"><div><span>Loaded group</span><strong>{failure.count} events</strong></div><div><span>Tenant scope</span><strong>{failure.tenantScope}</strong></div><div><span>Parser</span><strong>{failure.parserVersion??'Not applicable'}</strong></div><div><span>Mode</span><strong>Dry-run first</strong></div></section><div className="pipe-form-grid"><label className="pipe-field"><span>Maximum events</span><input value={Math.min(failure.count,500)} readOnly/></label><label className="pipe-field"><span>Target parser version</span><input value={failure.parserVersion??'No parser change'} readOnly/></label><label className="pipe-field pipe-field--wide"><span>Operator rationale</span><textarea placeholder="Explain why replay is safe and what changed."/></label></div><div className="pipe-notice">No raw payload is displayed here. A production preview must re-authorize the snapshot, simulate normalization and detection side effects, report duplicates and conflicts, and issue a short-lived confirmation token.</div></div><footer><button className="pipe-button" type="button" onClick={onClose}>Cancel</button><button className="pipe-button" type="button" disabled><RotateCcw size={13}/>Run dry preview</button><button className="pipe-button pipe-button--primary" type="button" disabled>Queue replay</button></footer></section></div>}
