import { useEffect, useMemo, useState } from 'react';

import { useQuery } from '@tanstack/react-query';
import { AlertTriangle, Archive, CalendarClock, CheckCircle2, ChevronRight, CircleSlash2, Clock3, FileCheck2, FileOutput, Files, FileText, Plus, RefreshCw, Search, ShieldCheck, Sparkles, X } from 'lucide-react';
import { useNavigate } from 'react-router-dom';

import './ReportingOperations.css';
import { reportingOperationsService } from './reportingOperations.service';
import type { OperationalReport, OperationalReportType, ReportSchedule, ReportTemplate, ReportingView } from './reportingOperations.types';

import { StatusDock } from '@/components/status-dock';
import { useEpsStream } from '@/hooks/useEpsStream';
import { useAuthStore } from '@/store/auth.store';

type Row = OperationalReport | ReportSchedule | ReportTemplate;
type InitialFacet = OperationalReportType | 'all';

const typeLabels: Record<OperationalReportType,string>={SITREP:'SITREP',INCIDENT:'Incident',AFTER_ACTION:'After-action',EXECUTIVE:'Executive',COMPLIANCE:'Compliance'};
const formatDate=(value?:string):string=>value?new Intl.DateTimeFormat(undefined,{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}).format(new Date(value)):'Never';
const isReport=(row:Row):row is OperationalReport=>'classification' in row;
const isSchedule=(row:Row):row is ReportSchedule=>'cadence' in row;

export function ReportingOperationsPage({initialView='generated',initialFacet='all'}:{initialView?:ReportingView;initialFacet?:InitialFacet}):JSX.Element {
  const navigate=useNavigate(); const eps=useEpsStream(); const {hasAnyRole,hasRole}=useAuthStore();
  const canView=hasAnyRole(['ROLE_ANALYST','ROLE_SOC_MANAGER','ROLE_ADMIN']); const canManage=hasAnyRole(['ROLE_SOC_MANAGER','ROLE_ADMIN']); const canAdmin=hasRole('ROLE_ADMIN');
  const [view,setView]=useState<ReportingView>(initialView); const [facet,setFacet]=useState<InitialFacet>(initialFacet); const [query,setQuery]=useState(''); const [selectedId,setSelectedId]=useState<string>(); const [dialog,setDialog]=useState(false);
  const inventoryQuery=useQuery({queryKey:['reporting-operations'],queryFn:()=>reportingOperationsService.list(),enabled:canView,staleTime:45_000});
  const inventory=inventoryQuery.data;
  const sourceRows=useMemo<Row[]>(()=>view==='generated'?(inventory?.reports??[]):view==='scheduled'?(inventory?.schedules??[]):(inventory?.templates??[]),[inventory,view]);
  const rows=useMemo(()=>{const needle=query.trim().toLocaleLowerCase();return sourceRows.filter((row)=>(facet==='all'||row.type===facet)&&(!needle||JSON.stringify(row).toLocaleLowerCase().includes(needle)));},[facet,query,sourceRows]);
  const selected=rows.find((row)=>row.id===selectedId);
  useEffect(()=>{if(selectedId&&!rows.some((row)=>row.id===selectedId))setSelectedId(undefined);},[rows,selectedId]);
  useEffect(()=>{const listener=(event:KeyboardEvent):void=>{if(event.key==='Escape'){setDialog(false);setSelectedId(undefined);}if((event.metaKey||event.ctrlKey)&&event.key.toLocaleLowerCase()==='g'&&canManage){event.preventDefault();setDialog(true);}};window.addEventListener('keydown',listener);return()=>window.removeEventListener('keydown',listener);},[canManage]);
  const withUrl=inventory?.reports.filter((item)=>item.status==='ready').length??0; const pending=inventory?.reports.filter((item)=>item.status==='review'||item.status==='generating').length??0; const deliveryIssues=inventory?.schedules.filter((item)=>item.deliveryHealth!=='healthy').length??0; const activeSchedules=inventory?.schedules.filter((item)=>item.active).length??0;
  if(!canView)return <section className="rpt-page"><Header onGenerate={()=>undefined} canGenerate={false}/><div className="rpt-empty"><CircleSlash2 size={30}/><strong>Reporting access restricted</strong><span>Reporting Operations requires Analyst or higher. Ask an administrator for an authorized reporting role.</span></div></section>;
  return <section className="rpt-page">
    <Header onGenerate={()=>setDialog(true)} canGenerate={canManage}/>
    {reportingOperationsService.fixtureMode&&<div className="rpt-trust"><ShieldCheck size={13}/><strong>Design fixture:</strong> fictional report artifacts, schedules, and templates are enabled for visual review. Production never receives these records.</div>}
    <section className="rpt-summary" aria-label="Reporting operations summary"><div><span>Legacy report records</span><strong>{inventory?.reports.length??0}</strong><small>loaded inventory</small></div><div data-tone="healthy"><span>Artifacts with URL</span><strong>{withUrl}</strong><small>approval not proven</small></div><div data-tone={pending?'warning':undefined}><span>In workflow</span><strong>{pending}</strong><small>review unknown</small></div><div><span>Active schedules</span><strong>{activeSchedules}</strong><small>schedule rows only</small></div><div data-tone={deliveryIssues?'warning':'healthy'}><span>Delivery attention</span><strong>{deliveryIssues}</strong><small>configuration or health</small></div><div><span>Published templates</span><strong>{inventory?.templates.filter((item)=>item.status==='published').length??0}</strong><small>fixture or empty live</small></div></section>
    <nav className="rpt-tabs" aria-label="Reporting workspace"><button type="button" role="tab" aria-selected={view==='generated'} onClick={()=>{setView('generated');navigate('/reports/sitrep');}}><FileOutput size={13}/>Generated <small>{inventory?.reports.length??0}</small></button><button type="button" role="tab" aria-selected={view==='scheduled'} onClick={()=>{setView('scheduled');navigate('/reports/scheduled');}}><CalendarClock size={13}/>Schedules <small>{inventory?.schedules.length??0}</small></button><button type="button" role="tab" aria-selected={view==='templates'} onClick={()=>{setView('templates');navigate('/reports/templates');}}><Files size={13}/>Templates <small>{inventory?.templates.length??0}</small></button></nav>
    <div className="rpt-toolbar"><label className="rpt-search"><Search size={13}/><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder={`Search ${view}…`} aria-label={`Search ${view}`}/></label><select className="rpt-select" value={facet} onChange={(event)=>setFacet(event.target.value as InitialFacet)} aria-label="Report type"><option value="all">All report types</option>{Object.entries(typeLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><button className="rpt-icon-button" type="button" aria-label="Refresh reporting inventory" onClick={()=>inventoryQuery.refetch()}><RefreshCw size={13}/></button><span className="rpt-toolbar__end">Snapshot {formatDate(inventory?.snapshotAt)} · {inventory?.tenantScoped?'authorized tenant scope':'scope not proven'}</span></div>
    <main className="rpt-main" data-drawer={Boolean(selected)}><section className="rpt-results"><div className="rpt-results-head"><div><strong>{view==='generated'?'Generated reports':view==='scheduled'?'Delivery schedules':'Report templates'}</strong> <span>{rows.length} loaded</span></div><span>{inventory?.bounded?'Bounded projection':'Legacy endpoint · bound not reported'}</span></div>{inventoryQuery.isLoading?<State icon={<FileText size={28}/>} title="Loading reporting inventory" detail="Retrieving the authorized reporting projection."/>:inventoryQuery.isError?<State error icon={<AlertTriangle size={28}/>} title="Reporting inventory unavailable" detail={inventoryQuery.error instanceof Error?inventoryQuery.error.message:'The inventory could not be loaded.'} action={()=>inventoryQuery.refetch()}/>:rows.length===0?<State icon={<Search size={28}/>} title={sourceRows.length?'No reports match this view':'No scheduled reports'} detail={sourceRows.length?'Clear filters or search another report lifecycle view.':'Create a governed report definition when backend generation is configured.'}/>:<ReportTable view={view} rows={rows} selectedId={selectedId} onSelect={(id)=>setSelectedId(id)}/>}</section>{selected&&<DetailDrawer row={selected} canAdmin={canAdmin} onClose={()=>setSelectedId(undefined)}/>}</main>
    <div className="rpt-status"><span><ShieldCheck size={11}/>No report is distributed without explicit authorization</span><strong>{inventory?.partial?inventory.warnings.join(' · '):reportingOperationsService.fixtureMode?'Fixture lifecycle · no messages sent':'Canonical generation contract pending · schedule run stamps last-execution only'}</strong><span>{inventory?.bounded?'Bounded inventory':'Legacy compatibility mode'}</span></div><StatusDock className="rpt-status-dock" sseConnected={reportingOperationsService.fixtureMode||eps.connected} eps={reportingOperationsService.fixtureMode?12840:eps.eps} mode={reportingOperationsService.fixtureMode?'historical':'live'} lastUpdated={inventoryQuery.dataUpdatedAt?new Date(inventoryQuery.dataUpdatedAt):undefined}/>
    {dialog&&<GenerateDialog canSubmit={false} onClose={()=>setDialog(false)}/>}
  </section>;
}

function Header({onGenerate,canGenerate}:{onGenerate:()=>void;canGenerate:boolean}):JSX.Element{return <header className="rpt-header"><div className="rpt-header__identity"><span className="rpt-header__mark"><FileCheck2 size={18}/></span><div><span className="rpt-eyebrow">OPERATE · SOC COMMUNICATIONS</span><h1>Reporting Operations</h1></div></div><div className="rpt-header__actions"><span className="rpt-shortcut"><kbd>⌘</kbd><kbd>G</kbd> generate <kbd>Esc</kbd> close</span><button className="rpt-button" type="button"><Archive size={13}/>Retention</button><button className="rpt-button rpt-button--primary" type="button" disabled={!canGenerate} title={canGenerate?undefined:'Requires SOC Manager or Administrator'} onClick={onGenerate}><Plus size={14}/>Generate report</button></div></header>}

function State({icon,title,detail,error=false,action}:{icon:JSX.Element;title:string;detail:string;error?:boolean;action?:()=>void}):JSX.Element{return <div className={`rpt-empty ${error?'rpt-empty--error':''}`} role={error?'alert':'status'}>{icon}<strong>{title}</strong><span>{detail}</span>{action&&<button className="rpt-button" type="button" onClick={action}>Retry</button>}</div>}

function ReportTable({view,rows,selectedId,onSelect}:{view:ReportingView;rows:Row[];selectedId?:string;onSelect:(id:string)=>void}):JSX.Element{return <div className="rpt-table-wrap"><table className="rpt-table"><colgroup><col style={{width:'32%'}}/><col style={{width:'12%'}}/><col style={{width:'19%'}}/><col style={{width:'18%'}}/><col style={{width:'15%'}}/><col style={{width:34}}/></colgroup><thead><tr><th>{view==='templates'?'Template':'Report'}</th><th>Type</th><th>{view==='generated'?'Scope':view==='scheduled'?'Cadence':'Owner'}</th><th>{view==='generated'?'Generated':view==='scheduled'?'Next run':'Version'}</th><th>{view==='generated'?'Status':view==='scheduled'?'Delivery':'Status'}</th><th><span className="sr-only">Open</span></th></tr></thead><tbody>{rows.map((row)=><tr key={row.id} tabIndex={0} data-selected={row.id===selectedId} onClick={()=>onSelect(row.id)} onKeyDown={(event)=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();onSelect(row.id);}}}><td><div className="rpt-cell-title"><FileText size={14}/><div><strong>{isReport(row)?row.title:isSchedule(row)?row.title:row.name}</strong><small>{isReport(row)?`${row.format} · v${row.version} · ${row.redactionProfile}`:isSchedule(row)?`${row.format} · ${row.owner}`:`${row.sections} sections · ${row.dataSources} data sources`}</small></div></div></td><td>{typeLabels[row.type]}</td><td>{isReport(row)?row.scope:isSchedule(row)?`${row.cadence} · ${row.timezone}`:row.owner}</td><td className="rpt-mono">{isReport(row)?formatDate(row.generatedAt):isSchedule(row)?formatDate(row.nextRunAt):`v${row.version} · ${formatDate(row.updatedAt)}`}</td><td>{isReport(row)?<span className="rpt-badge" data-state={row.status}>{row.status}</span>:isSchedule(row)?<span className="rpt-health" data-health={row.deliveryHealth}>{row.deliveryHealth==='healthy'?<CheckCircle2 size={12}/>:<AlertTriangle size={12}/>} {row.deliveryHealth.replace('_',' ')}</span>:<span className="rpt-badge" data-state={row.status}>{row.status}</span>}</td><td><ChevronRight size={13}/></td></tr>)}</tbody></table></div>}

function DetailDrawer({row,canAdmin,onClose}:{row:Row;canAdmin:boolean;onClose:()=>void}):JSX.Element{return <aside className="rpt-drawer" aria-label="Report context"><header className="rpt-drawer__head"><div><strong>{isReport(row)?row.title:isSchedule(row)?row.title:row.name}</strong><small>{typeLabels[row.type]} · {row.id}</small></div><button className="rpt-icon-button" type="button" aria-label="Close report context" onClick={onClose}><X size={13}/></button></header><div className="rpt-drawer__scroll"><div className="rpt-drawer__meta"><span className="rpt-badge">{row.type}</span>{isReport(row)&&<span className="rpt-badge">{row.classification}</span>}{'status' in row&&<span className="rpt-badge" data-state={row.status}>{row.status}</span>}</div><section className="rpt-card"><h3>{isReport(row)?'Artifact provenance':isSchedule(row)?'Execution policy':'Template definition'}</h3><dl>{isReport(row)?<><div><dt>Scope</dt><dd>{row.scope}</dd></div><div><dt>Period</dt><dd>{row.period}</dd></div><div><dt>Evidence</dt><dd>{row.evidenceCount} records</dd></div><div><dt>Approval</dt><dd>{row.approval}</dd></div></>:isSchedule(row)?<><div><dt>Run as</dt><dd>{row.runAs}</dd></div><div><dt>Recipients</dt><dd>{row.recipients.length}</dd></div><div><dt>Channels</dt><dd>{row.channels.join(', ')}</dd></div><div><dt>Last duration</dt><dd>{row.lastDurationMs?`${(row.lastDurationMs/1000).toFixed(1)} s`:'Not reported'}</dd></div></>:<><div><dt>Owner</dt><dd>{row.owner}</dd></div><div><dt>Sections</dt><dd>{row.sections}</dd></div><div><dt>Data sources</dt><dd>{row.dataSources}</dd></div><div><dt>Redaction</dt><dd>{row.redactionProfile}</dd></div></>}</dl></section>{isReport(row)&&<section className="rpt-card"><h3>Trust and disclosure</h3><p>This artifact is snapshot-bound and must preserve its evidence citations, tenant scope, redaction profile, generation identity, and immutable version.</p></section>}<div className="rpt-notice">Authoritative generation, approval, signed download, delivery, and retention controls require the canonical reporting backend contract.</div><div className="rpt-drawer__actions" style={{marginTop:9}}><button className="rpt-button" type="button" disabled={!isReport(row)}>Preview</button><button className="rpt-button" type="button" disabled={!canAdmin}>{isSchedule(row)&&row.active?'Pause':'Edit'}</button><button className="rpt-button rpt-button--primary" type="button" disabled>Backend action required</button></div></div></aside>}

function GenerateDialog({canSubmit,onClose}:{canSubmit:boolean;onClose:()=>void}):JSX.Element{return <div className="rpt-dialog-backdrop" role="presentation" onMouseDown={(event)=>{if(event.target===event.currentTarget)onClose();}}><section className="rpt-dialog" role="dialog" aria-modal="true" aria-labelledby="generate-report-title"><header><div><span className="rpt-eyebrow">GOVERNED GENERATION</span><h2 id="generate-report-title">Generate report</h2></div><button className="rpt-icon-button" type="button" aria-label="Close" onClick={onClose}><X size={13}/></button></header><div className="rpt-dialog__body"><div className="rpt-form-grid"><label className="rpt-field"><span>Report type</span><select defaultValue="SITREP"><option>SITREP</option><option>Incident</option><option>After-action</option><option>Executive</option></select></label><label className="rpt-field"><span>Template</span><select><option>SOC shift SITREP · v7</option></select></label><label className="rpt-field"><span>Tenant scope</span><select><option>All authorized tenants</option></select></label><label className="rpt-field"><span>Time period</span><select><option>Current shift · 8 hours</option><option>Last 24 hours</option><option>Custom range</option></select></label><label className="rpt-field"><span>Classification</span><select><option>Internal</option><option>Restricted</option><option>Executive</option></select></label><label className="rpt-field"><span>Redaction profile</span><select><option>SOC internal</option><option>Leadership summary</option></select></label><label className="rpt-field rpt-field--wide"><span>Purpose and review note</span><textarea defaultValue="Produce an evidence-backed shift handoff for the incoming SOC lead."/></label></div><div className="rpt-notice" style={{marginTop:10}}><Sparkles size={12}/> Hive Intelligence may draft narrative sections only from cited, authorized evidence. It cannot approve, distribute, or alter source evidence.</div></div><footer><button className="rpt-button" type="button" onClick={onClose}>Cancel</button><button className="rpt-button rpt-button--primary" type="button" disabled={!canSubmit}><Clock3 size={13}/>Queue generation</button></footer></section></div>}
