package llm

import (
	"bufio"
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"maps"
	"net/http"
	"strings"
	"time"

	"github.com/hivearmor/plugins/soc-ai/config"
)

// ChatMessage is a single turn in a conversation.
type ChatMessage struct {
	Role    string `json:"role"`    // "system" | "user" | "assistant"
	Content string `json:"content"`
}

// ChatContext carries optional page context from the frontend.
type ChatContext struct {
	CurrentAlertID    string         `json:"currentAlertId,omitempty"`
	CurrentIncidentID string         `json:"currentIncidentId,omitempty"`
	RecentAlerts      []interface{}  `json:"recentAlerts,omitempty"`
	TimeRange         string         `json:"timeRange,omitempty"`
}

// ChatRequest is the body of POST /api/v1/chat.
type ChatRequest struct {
	Messages []ChatMessage `json:"messages"`
	Context  *ChatContext  `json:"context,omitempty"`
	Stream   bool          `json:"stream"`
}

// ChatDelta is a single SSE payload chunk.
type ChatDelta struct {
	Delta string `json:"delta,omitempty"`
	Done  bool   `json:"done,omitempty"`
	Error string `json:"error,omitempty"`
}

// openAIStreamChunk is the SSE data shape from OpenAI-compatible streaming APIs.
type openAIStreamChunk struct {
	Choices []struct {
		Delta struct {
			Content string `json:"content"`
		} `json:"delta"`
		FinishReason string `json:"finish_reason"`
	} `json:"choices"`
}

// anthropicStreamEvent is the SSE data shape from Anthropic streaming API.
type anthropicStreamEvent struct {
	Type  string `json:"type"`
	Delta *struct {
		Type string `json:"type"`
		Text string `json:"text"`
	} `json:"delta,omitempty"`
}

const chatSystemPrompt = `You are HiveArmor's AI SOC Assistant — an expert security analyst embedded in the HiveArmor SIEM/XDR platform.

## Platform Context
HiveArmor ingests logs from endpoints (Windows/Linux/macOS agents), firewalls, IDS/IPS, proxies, antivirus, cloud trails, and more.
Events are parsed, enriched (geo-IP, threat feeds), and correlated before reaching OpenSearch.
Alerts are generated by YAML-based correlation rules. Incidents group related alerts.

## Data Model
- Alerts: name, severity (1=low→4=critical), status (1=open, 2=in-progress, 3=resolved, 4=false positive, 5=completed), category, MITRE tactics/techniques
- Incidents: group of related alerts with a shared investigation thread
- Logs: indexed under v3-hive-log-* with fields logx.srcIp, logx.dstIp, logx.username, logx.hostname, logx.processName, logx.commandLine, logx.eventId

## Your Role
- Triage alerts: is this a real threat, false positive, or standard alert?
- Explain security concepts and MITRE ATT&CK techniques in plain language
- Suggest investigation steps and response playbooks
- Answer questions about logs, alerts, incidents, and security events visible in the platform
- If the user shares an alert ID or name, reference it directly in your response

## Response Style
- Be concise and actionable — SOC analysts are busy
- Use bullet points for lists of steps or findings
- For MITRE techniques, cite the ID (e.g. T1078) and name
- If you don't know something, say so — don't guess at specific alert data you haven't been given
- You may suggest follow-up actions like "Would you like me to create an incident?" or "Shall I run the response playbook for this?"
`

// StreamChat sends messages to the LLM and writes SSE chunks to the writer.
// Each chunk is written as "data: {json}\n\n".
// The final chunk has done=true.
func StreamChat(req *ChatRequest, w http.ResponseWriter) error {
	cfg := config.GetConfig()
	if cfg == nil {
		return fmt.Errorf("plugin not configured")
	}

	messages := buildChatMessages(req)
	isAnthropic := isAnthropicProvider(cfg.URL)

	requestJSON, err := buildChatRequest(cfg, messages, isAnthropic)
	if err != nil {
		return fmt.Errorf("building request: %w", err)
	}

	headers := buildChatHeaders(cfg)

	ctx, cancel := context.WithTimeout(context.Background(), time.Duration(config.HTTP_GPT_TIMEOUT)*time.Second)
	defer cancel()

	httpReq, err := http.NewRequestWithContext(ctx, http.MethodPost, cfg.URL, bytes.NewBuffer(requestJSON))
	if err != nil {
		return fmt.Errorf("creating HTTP request: %w", err)
	}
	for k, v := range headers {
		httpReq.Header.Set(k, v)
	}

	resp, err := http.DefaultClient.Do(httpReq)
	if err != nil {
		return fmt.Errorf("LLM request: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode == http.StatusUnauthorized {
		return fmt.Errorf("invalid api-key (401)")
	}
	if resp.StatusCode != http.StatusOK {
		body, _ := io.ReadAll(resp.Body)
		return fmt.Errorf("LLM returned %d: %s", resp.StatusCode, string(body))
	}

	// Flush headers immediately so the client sees the SSE stream start
	flusher, canFlush := w.(http.Flusher)

	scanner := bufio.NewScanner(resp.Body)
	for scanner.Scan() {
		line := scanner.Text()
		if !strings.HasPrefix(line, "data:") {
			continue
		}
		data := strings.TrimSpace(strings.TrimPrefix(line, "data:"))
		if data == "[DONE]" {
			break
		}
		if data == "" {
			continue
		}

		var token string
		var done bool

		if isAnthropic {
			var evt anthropicStreamEvent
			if err := json.Unmarshal([]byte(data), &evt); err != nil {
				continue
			}
			if evt.Type == "content_block_delta" && evt.Delta != nil && evt.Delta.Type == "text_delta" {
				token = evt.Delta.Text
			} else if evt.Type == "message_stop" {
				done = true
			}
		} else {
			var chunk openAIStreamChunk
			if err := json.Unmarshal([]byte(data), &chunk); err != nil {
				continue
			}
			if len(chunk.Choices) > 0 {
				token = chunk.Choices[0].Delta.Content
				if chunk.Choices[0].FinishReason == "stop" {
					done = true
				}
			}
		}

		if token != "" {
			writeDelta(w, ChatDelta{Delta: token})
			if canFlush {
				flusher.Flush()
			}
		}
		if done {
			break
		}
	}

	if err := scanner.Err(); err != nil {
		return fmt.Errorf("reading SSE stream: %w", err)
	}

	writeDelta(w, ChatDelta{Done: true})
	if canFlush {
		flusher.Flush()
	}
	return nil
}

func writeDelta(w http.ResponseWriter, d ChatDelta) {
	b, _ := json.Marshal(d)
	fmt.Fprintf(w, "data: %s\n\n", b)
}

func buildChatMessages(req *ChatRequest) []ChatMessage {
	result := make([]ChatMessage, 0, len(req.Messages)+1)

	// Inject system prompt if the caller hasn't provided one
	hasSystem := false
	for _, m := range req.Messages {
		if m.Role == "system" {
			hasSystem = true
			break
		}
	}

	if !hasSystem {
		systemContent := chatSystemPrompt
		if req.Context != nil {
			systemContent += buildContextAddendum(req.Context)
		}
		result = append(result, ChatMessage{Role: "system", Content: systemContent})
	}

	result = append(result, req.Messages...)
	return result
}

func buildContextAddendum(ctx *ChatContext) string {
	var sb strings.Builder
	sb.WriteString("\n\n## Current User Context\n")
	if ctx.CurrentAlertID != "" {
		sb.WriteString(fmt.Sprintf("- Viewing alert ID: %s\n", ctx.CurrentAlertID))
	}
	if ctx.CurrentIncidentID != "" {
		sb.WriteString(fmt.Sprintf("- Viewing incident ID: %s\n", ctx.CurrentIncidentID))
	}
	if ctx.TimeRange != "" {
		sb.WriteString(fmt.Sprintf("- Selected time range: %s\n", ctx.TimeRange))
	}
	return sb.String()
}

// openAIChatRequest is the streaming request body for OpenAI-compatible APIs.
type openAIChatRequest struct {
	Model    string        `json:"model"`
	Messages []ChatMessage `json:"messages"`
	Stream   bool          `json:"stream"`
	MaxTokens int          `json:"max_tokens,omitempty"`
}

// anthropicChatRequest is the streaming request body for Anthropic API.
type anthropicChatRequest struct {
	Model     string        `json:"model"`
	System    string        `json:"system,omitempty"`
	Messages  []ChatMessage `json:"messages"`
	Stream    bool          `json:"stream"`
	MaxTokens int           `json:"max_tokens"`
}

func buildChatRequest(cfg *config.Config, messages []ChatMessage, isAnthropic bool) ([]byte, error) {
	if isAnthropic {
		// Anthropic puts the system message in a top-level "system" field
		systemContent := ""
		userMessages := make([]ChatMessage, 0, len(messages))
		for _, m := range messages {
			if m.Role == "system" {
				systemContent = m.Content
			} else {
				userMessages = append(userMessages, m)
			}
		}
		maxTokens := cfg.MaxTokens
		if maxTokens == 0 {
			maxTokens = 4096
		}
		req := anthropicChatRequest{
			Model:     cfg.Model,
			System:    systemContent,
			Messages:  userMessages,
			Stream:    true,
			MaxTokens: maxTokens,
		}
		return json.Marshal(req)
	}

	maxTokens := cfg.MaxTokens
	req := openAIChatRequest{
		Model:     cfg.Model,
		Messages:  messages,
		Stream:    true,
		MaxTokens: maxTokens,
	}
	return json.Marshal(req)
}

func buildChatHeaders(cfg *config.Config) map[string]string {
	headers := map[string]string{
		"Content-Type": "application/json",
		"Accept":       "text/event-stream",
	}
	if isAnthropicProvider(cfg.URL) {
		headers["anthropic-version"] = config.ANTHROPIC_API_VERSION
	}
	if cfg.AuthType == "custom-headers" {
		maps.Copy(headers, cfg.CustomHeaders)
	}
	return headers
}
