/* SPDX-License-Identifier: Apache-2.0 */
/*
 * hivearmor.bpf.c — HiveArmor eBPF telemetry programs.
 *
 * Compile with:
 *   clang -O2 -target bpf -D__TARGET_ARCH_x86 \
 *         -I/usr/include/x86_64-linux-gnu \
 *         -c hivearmor.bpf.c -o hivearmor.bpf.o
 *
 * Or via bpf2go (run from agent/collector/ebpf/):
 *   //go:generate go run github.com/cilium/ebpf/cmd/bpf2go \
 *       -cc clang -cflags "-O2 -g -Wall -Werror" \
 *       bpf ./bpf/hivearmor.bpf.c -- -I./bpf
 *
 * Tracepoints attached:
 *   syscalls/sys_enter_execve       → trace_execve
 *   syscalls/sys_exit_execve        → trace_execve_exit
 *   syscalls/sys_enter_execveat     → trace_execveat
 *   syscalls/sys_enter_openat       → trace_openat
 *   syscalls/sys_enter_connect      → trace_connect
 *   syscalls/sys_enter_accept4      → trace_accept4
 *   syscalls/sys_enter_bind         → trace_bind
 *   syscalls/sys_enter_unlinkat     → trace_unlinkat
 *   syscalls/sys_enter_renameat2    → trace_renameat2
 *   syscalls/sys_enter_fchmodat     → trace_fchmodat
 *   syscalls/sys_enter_fchownat     → trace_fchownat
 *   syscalls/sys_enter_setuid       → trace_setuid
 *   syscalls/sys_enter_setgid       → trace_setgid
 *   syscalls/sys_enter_ptrace       → trace_ptrace
 *   syscalls/sys_enter_mmap         → trace_mmap (PROT_EXEC only)
 *   syscalls/sys_enter_init_module  → trace_init_module
 *   syscalls/sys_enter_finit_module → trace_finit_module
 */

#include "vmlinux.h"            /* generated by bpftool btf dump — CO-RE headers */
#include <bpf/bpf_helpers.h>
#include <bpf/bpf_tracing.h>
#include <bpf/bpf_core_read.h>
#include "events.h"

/*
 * Per-CPU scratch space used to build events before submitting to the ring
 * buffer.  Using a per-CPU map avoids stack overflows (BPF stack limit 512B).
 */
struct {
    __uint(type, BPF_MAP_TYPE_PERCPU_ARRAY);
    __uint(max_entries, 1);
    __type(key, __u32);
    __type(value, struct event_t);
} scratch_map SEC(".maps");

/*
 * Ring buffer: the Go side reads from this via ringbuf.Reader.
 * Size must be a power of two pages; 64 pages = 256 KiB is enough for
 * ~200 events at peak burst without losing events at 1 ms read latency.
 */
struct {
    __uint(type, BPF_MAP_TYPE_RINGBUF);
    __uint(max_entries, 256 * 1024);
} events SEC(".maps");

/* ── helpers ──────────────────────────────────────────────────────────── */

static __always_inline struct event_t *get_scratch(void) {
    __u32 key = 0;
    return bpf_map_lookup_elem(&scratch_map, &key);
}

static __always_inline void fill_process_context(struct event_t *e) {
    struct task_struct *task = (struct task_struct *)bpf_get_current_task();
    e->pid   = bpf_get_current_pid_tgid() >> 32;
    e->ppid  = BPF_CORE_READ(task, real_parent, tgid);
    __u64 uid_gid = bpf_get_current_uid_gid();
    e->uid   = (__u32)uid_gid;
    e->gid   = (__u32)(uid_gid >> 32);
    e->timestamp_ns = bpf_ktime_get_ns();
    bpf_get_current_comm(e->comm, sizeof(e->comm));
}

static __always_inline void submit(struct event_t *e) {
    bpf_ringbuf_output(&events, e, sizeof(*e), 0);
}

/* ── execve ────────────────────────────────────────────────────────────── */

SEC("tracepoint/syscalls/sys_enter_execve")
int trace_execve(struct trace_event_raw_sys_enter *ctx)
{
    struct event_t *e = get_scratch();
    if (!e) return 0;
    __builtin_memset(e, 0, sizeof(*e));
    e->event_type = EVENT_EXEC;
    fill_process_context(e);
    /* filename is the first argument */
    bpf_probe_read_user_str(e->exe_path, sizeof(e->exe_path),
                            (void *)ctx->args[0]);
    /* argv[1..N] joined into argv field */
    const char **argv = (const char **)(void *)ctx->args[1];
    bpf_probe_read_user_str(e->argv, sizeof(e->argv),
                            (void *)argv); /* best effort first arg */
    submit(e);
    return 0;
}

SEC("tracepoint/syscalls/sys_exit_execve")
int trace_execve_exit(struct trace_event_raw_sys_exit *ctx)
{
    struct event_t *e = get_scratch();
    if (!e) return 0;
    __builtin_memset(e, 0, sizeof(*e));
    e->event_type = EVENT_EXEC;
    fill_process_context(e);
    e->ret_code = (int)ctx->ret;
    submit(e);
    return 0;
}

/* ── openat ────────────────────────────────────────────────────────────── */

SEC("tracepoint/syscalls/sys_enter_openat")
int trace_openat(struct trace_event_raw_sys_enter *ctx)
{
    /* Only report opens with write-related flags to reduce noise.
       O_WRONLY=1, O_RDWR=2, O_CREAT=64 (0x40), O_TRUNC=512 (0x200) */
    __u64 flags = ctx->args[2];
    if (!(flags & (1 | 2 | 64 | 512)))
        return 0;

    struct event_t *e = get_scratch();
    if (!e) return 0;
    __builtin_memset(e, 0, sizeof(*e));
    e->event_type = EVENT_OPEN;
    fill_process_context(e);
    e->flags = (__u32)flags;
    bpf_probe_read_user_str(e->file_path, sizeof(e->file_path),
                            (void *)ctx->args[1]);
    submit(e);
    return 0;
}

/* ── connect ────────────────────────────────────────────────────────────── */

SEC("tracepoint/syscalls/sys_enter_connect")
int trace_connect(struct trace_event_raw_sys_enter *ctx)
{
    struct event_t *e = get_scratch();
    if (!e) return 0;
    __builtin_memset(e, 0, sizeof(*e));
    e->event_type = EVENT_CONNECT;
    fill_process_context(e);

    /* Try to read sockaddr_in — best effort; silently skip IPv6 for now */
    struct sockaddr_in sa = {};
    if (bpf_probe_read_user(&sa, sizeof(sa), (void *)ctx->args[1]) == 0) {
        if (sa.sin_family == 2 /* AF_INET */) {
            e->dst_ip   = sa.sin_addr.s_addr;
            e->dst_port = __builtin_bswap16(sa.sin_port);
        }
    }
    submit(e);
    return 0;
}

/* ── bind ────────────────────────────────────────────────────────────────── */

SEC("tracepoint/syscalls/sys_enter_bind")
int trace_bind(struct trace_event_raw_sys_enter *ctx)
{
    struct event_t *e = get_scratch();
    if (!e) return 0;
    __builtin_memset(e, 0, sizeof(*e));
    e->event_type = EVENT_BIND;
    fill_process_context(e);
    struct sockaddr_in sa = {};
    if (bpf_probe_read_user(&sa, sizeof(sa), (void *)ctx->args[1]) == 0) {
        if (sa.sin_family == 2) {
            e->src_ip   = sa.sin_addr.s_addr;
            e->src_port = __builtin_bswap16(sa.sin_port);
        }
    }
    submit(e);
    return 0;
}

/* ── unlinkat ────────────────────────────────────────────────────────────── */

SEC("tracepoint/syscalls/sys_enter_unlinkat")
int trace_unlinkat(struct trace_event_raw_sys_enter *ctx)
{
    struct event_t *e = get_scratch();
    if (!e) return 0;
    __builtin_memset(e, 0, sizeof(*e));
    e->event_type = EVENT_UNLINK;
    fill_process_context(e);
    bpf_probe_read_user_str(e->file_path, sizeof(e->file_path),
                            (void *)ctx->args[1]);
    submit(e);
    return 0;
}

/* ── renameat2 ────────────────────────────────────────────────────────────── */

SEC("tracepoint/syscalls/sys_enter_renameat2")
int trace_renameat2(struct trace_event_raw_sys_enter *ctx)
{
    struct event_t *e = get_scratch();
    if (!e) return 0;
    __builtin_memset(e, 0, sizeof(*e));
    e->event_type = EVENT_RENAME;
    fill_process_context(e);
    bpf_probe_read_user_str(e->file_path, sizeof(e->file_path),
                            (void *)ctx->args[1]);
    bpf_probe_read_user_str(e->new_path, sizeof(e->new_path),
                            (void *)ctx->args[3]);
    submit(e);
    return 0;
}

/* ── setuid / setgid ──────────────────────────────────────────────────────── */

SEC("tracepoint/syscalls/sys_enter_setuid")
int trace_setuid(struct trace_event_raw_sys_enter *ctx)
{
    struct event_t *e = get_scratch();
    if (!e) return 0;
    __builtin_memset(e, 0, sizeof(*e));
    e->event_type = EVENT_SETUID;
    fill_process_context(e);
    e->flags = (__u32)ctx->args[0]; /* new uid */
    submit(e);
    return 0;
}

SEC("tracepoint/syscalls/sys_enter_setgid")
int trace_setgid(struct trace_event_raw_sys_enter *ctx)
{
    struct event_t *e = get_scratch();
    if (!e) return 0;
    __builtin_memset(e, 0, sizeof(*e));
    e->event_type = EVENT_SETGID;
    fill_process_context(e);
    e->flags = (__u32)ctx->args[0]; /* new gid */
    submit(e);
    return 0;
}

/* ── ptrace ────────────────────────────────────────────────────────────────── */

SEC("tracepoint/syscalls/sys_enter_ptrace")
int trace_ptrace(struct trace_event_raw_sys_enter *ctx)
{
    struct event_t *e = get_scratch();
    if (!e) return 0;
    __builtin_memset(e, 0, sizeof(*e));
    e->event_type = EVENT_PTRACE;
    fill_process_context(e);
    e->flags = (__u32)ctx->args[0]; /* request type */
    submit(e);
    return 0;
}

/* ── mmap (PROT_EXEC only) ────────────────────────────────────────────────── */

#define PROT_EXEC 0x4

SEC("tracepoint/syscalls/sys_enter_mmap")
int trace_mmap(struct trace_event_raw_sys_enter *ctx)
{
    __u64 prot = ctx->args[2];
    if (!(prot & PROT_EXEC))
        return 0; /* only care about executable mappings */

    struct event_t *e = get_scratch();
    if (!e) return 0;
    __builtin_memset(e, 0, sizeof(*e));
    e->event_type = EVENT_MMAP_EXEC;
    fill_process_context(e);
    e->mode_or_prot = (__u32)prot;
    e->flags        = (__u32)ctx->args[3]; /* MAP_ANONYMOUS etc. */
    submit(e);
    return 0;
}

/* ── init_module / finit_module ──────────────────────────────────────────── */

SEC("tracepoint/syscalls/sys_enter_init_module")
int trace_init_module(struct trace_event_raw_sys_enter *ctx)
{
    struct event_t *e = get_scratch();
    if (!e) return 0;
    __builtin_memset(e, 0, sizeof(*e));
    e->event_type = EVENT_INIT_MODULE;
    fill_process_context(e);
    /* param string contains module name */
    bpf_probe_read_user_str(e->module_name, sizeof(e->module_name),
                            (void *)ctx->args[2]);
    submit(e);
    return 0;
}

SEC("tracepoint/syscalls/sys_enter_finit_module")
int trace_finit_module(struct trace_event_raw_sys_enter *ctx)
{
    struct event_t *e = get_scratch();
    if (!e) return 0;
    __builtin_memset(e, 0, sizeof(*e));
    e->event_type = EVENT_FINIT_MODULE;
    fill_process_context(e);
    bpf_probe_read_user_str(e->module_name, sizeof(e->module_name),
                            (void *)ctx->args[2]);
    submit(e);
    return 0;
}

char LICENSE[] SEC("license") = "Apache-2.0";
