package com.hivearmor.service;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.hivearmor.ai.HaLlmService;
import com.hivearmor.multitenancy.MsspIndexResolver;
import net.jqwik.api.*;
import net.jqwik.api.lifecycle.BeforeTry;
import org.junit.jupiter.api.Tag;

import java.lang.reflect.Method;
import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.Mockito.mock;

/**
 * Property 3: LLM response parser round-trips valid JSON objects.
 *
 * <p><strong>Validates: Requirements 4.1, 4.2, 4.6</strong>
 *
 * <p>Two properties are tested:
 * <ul>
 *   <li><strong>Property A — round-trip:</strong> For any serialized {@link ObjectNode}
 *       wrapped with arbitrary brace-free prefix and suffix text,
 *       {@code parseLlmResponse} returns a non-empty {@code Optional} whose value is
 *       structurally equal to the original node.</li>
 *   <li><strong>Property B — empty when no balanced object:</strong> For strings that
 *       contain no {@code '{'} character at all, {@code parseLlmResponse} returns
 *       {@code Optional.empty()}.</li>
 * </ul>
 *
 * <h3>Access strategy</h3>
 * <p>{@code parseLlmResponse} is private. This test uses the package-private
 * {@link HaSearchService#parseLlmResponseForTesting(String)} accessor method, which
 * delegates directly to the private method without requiring reflection.
 * The reflection path documented in the task spec is also shown in a comment below
 * for completeness.
 */
@Tag("Feature: sprint-26-nl-search")
@Label("Feature: sprint-26-nl-search, Property 3: LLM response parser round-trips valid JSON objects")
class HaSearchServiceParserTest {

    // -------------------------------------------------------------------------
    // Test infrastructure — re-created before every jqwik trial
    // -------------------------------------------------------------------------

    private ObjectMapper objectMapper;
    private HaSearchService service;

    /**
     * Re-initialises mocks and service before every jqwik trial so that no
     * state leaks between iterations.
     */
    @BeforeTry
    void setUp() {
        objectMapper = new ObjectMapper();
        HaLlmService llmService = mock(HaLlmService.class);
        MsspIndexResolver msspIndexResolver = mock(MsspIndexResolver.class);
        // Real ObjectMapper is intentional: parseLlmResponse uses objectMapper.readTree.
        service = new HaSearchService(llmService, objectMapper, msspIndexResolver);
    }

    // =========================================================================
    // Property A — round-trip valid JSON objects
    // =========================================================================

    /**
     * <strong>Property A: round-trip valid JSON objects</strong>
     *
     * <p>For any {@link ObjectNode} generated by {@link #arbitraryObjectNodes()},
     * serialized to compact JSON and surrounded by arbitrary brace-free prefix and
     * suffix strings, {@code parseLlmResponse} must:
     * <ol>
     *   <li>Return a non-empty {@code Optional}.</li>
     *   <li>Return a node structurally equal (via Jackson's {@code equals}) to the
     *       original {@code ObjectNode}.</li>
     * </ol>
     *
     * <p><strong>Validates: Requirements 4.1, 4.2</strong>
     */
    @Property(tries = 100)
    @Label("Property 3-A: parser round-trips valid JSON objects with surrounding brace-free text")
    void propertyA_roundTrip(
            @ForAll("arbitraryObjectNodes") ObjectNode jsonObject,
            @ForAll("braceFreeStrings") String prefix,
            @ForAll("braceFreeStrings") String suffix) throws Exception {

        String serialized = objectMapper.writeValueAsString(jsonObject);
        String input = prefix + serialized + suffix;

        Optional<JsonNode> result = invokeParser(input);

        assertThat(result)
            .as("parseLlmResponse must return a present Optional for a valid JSON object embedded in %s...%s",
                prefix.isEmpty() ? "<empty>" : prefix.substring(0, Math.min(prefix.length(), 20)),
                suffix.isEmpty() ? "<empty>" : suffix.substring(0, Math.min(suffix.length(), 20)))
            .isPresent();

        assertThat(result.get())
            .as("Parsed node must be structurally equal to the original ObjectNode")
            .isEqualTo(jsonObject);
    }

    // =========================================================================
    // Property B — empty Optional when no balanced object present
    // =========================================================================

    /**
     * <strong>Property B: empty when no balanced object</strong>
     *
     * <p>For any string that contains no {@code '{'} character, there can be no
     * balanced JSON object substring. {@code parseLlmResponse} must return
     * {@code Optional.empty()}.
     *
     * <p><strong>Validates: Requirement 4.6</strong>
     */
    @Property(tries = 100)
    @Label("Property 3-B: parser returns Optional.empty() for strings containing no '{' character")
    void propertyB_noBrace_returnsEmpty(
            @ForAll("noBraceStrings") String input) throws Exception {

        Optional<JsonNode> result = invokeParser(input);

        assertThat(result)
            .as("parseLlmResponse must return Optional.empty() when input contains no '{': [%s]", input)
            .isEmpty();
    }

    // =========================================================================
    // Access helper — package-private test accessor (no reflection needed)
    // =========================================================================

    /**
     * Invokes {@code parseLlmResponse} via the package-private
     * {@link HaSearchService#parseLlmResponseForTesting(String)} accessor.
     *
     * <p>Reflection alternative (shown for reference, not used here):
     * <pre>{@code
     *   Method m = HaSearchService.class.getDeclaredMethod("parseLlmResponse", String.class);
     *   m.setAccessible(true);
     *   Optional<JsonNode> result = (Optional<JsonNode>) m.invoke(service, input);
     * }</pre>
     */
    @SuppressWarnings("unchecked")
    private Optional<JsonNode> invokeParser(String input) throws Exception {
        // Use package-private accessor — same package (com.hivearmor.service), no reflection.
        return service.parseLlmResponseForTesting(input);
    }

    // =========================================================================
    // Arbitrary providers (jqwik @Provide methods)
    // =========================================================================

    /**
     * Generates varied {@link ObjectNode} instances covering common LLM-response
     * shapes: flat objects, nested query structures, objects with string values
     * containing braces, numeric fields, boolean fields, and array-valued fields.
     *
     * <p>Pure recursive {@code JsonNode} generation is complex; a representative
     * fixed set exercises the parser across the shapes it will encounter in
     * production without requiring a custom recursive generator.
     */
    @Provide
    Arbitrary<ObjectNode> arbitraryObjectNodes() {
        return Arbitraries.of(
            minimalObject(),
            matchAllQuery(),
            queryWithConfidenceAndExplanation(),
            queryWithSizeField(),
            nestedBoolQuery(),
            objectWithBracesInStringValue(),
            objectWithEscapedQuotesInValue(),
            objectWithArrayField(),
            objectWithBooleanField(),
            deeplyNestedObject()
        );
    }

    /**
     * Generates strings that contain no {@code '{'} or {@code '}'} characters,
     * using lowercase ASCII letters only. This guarantees no balanced JSON object
     * substring can be present, making it safe for Property B.
     */
    @Provide
    Arbitrary<String> noBraceStrings() {
        return Arbitraries.strings()
            .withCharRange('a', 'z')
            .ofMinLength(0)
            .ofMaxLength(200);
    }

    /**
     * Generates brace-free strings using lowercase ASCII letters that are safe
     * to use as prefix/suffix surrounding a serialized JSON object.  Using only
     * {@code [a-z]} avoids all JSON structural characters ({@code {}[]":\,}) so
     * the brace-depth scanner sees no false-positive delimiters.
     */
    @Provide
    Arbitrary<String> braceFreeStrings() {
        return Arbitraries.strings()
            .withCharRange('a', 'z')
            .ofMinLength(0)
            .ofMaxLength(80);
    }

    // =========================================================================
    // ObjectNode factory helpers
    // =========================================================================

    /** Minimal single-field object. */
    private ObjectNode minimalObject() {
        ObjectNode root = objectMapper.createObjectNode();
        root.put("type", "minimal");
        return root;
    }

    /** Typical match-all DSL: {@code {"query":{"match_all":{}}}} */
    private ObjectNode matchAllQuery() {
        ObjectNode root = objectMapper.createObjectNode();
        root.set("query", objectMapper.createObjectNode()
            .set("match_all", objectMapper.createObjectNode()));
        return root;
    }

    /** Typical LLM response with confidence and explanation fields. */
    private ObjectNode queryWithConfidenceAndExplanation() {
        ObjectNode root = objectMapper.createObjectNode();
        ObjectNode query = objectMapper.createObjectNode();
        ObjectNode term = objectMapper.createObjectNode();
        term.put("severity", "critical");
        query.set("term", term);
        root.set("query", query);
        root.put("confidence", 0.87);
        root.put("explanation", "Filters critical-severity events.");
        return root;
    }

    /** Object with a numeric {@code size} field inside the valid range. */
    private ObjectNode queryWithSizeField() {
        ObjectNode root = objectMapper.createObjectNode();
        root.set("query", objectMapper.createObjectNode()
            .set("match_all", objectMapper.createObjectNode()));
        root.put("size", 250);
        return root;
    }

    /** Nested bool query simulating an authentication-failure search. */
    private ObjectNode nestedBoolQuery() {
        ObjectNode root = objectMapper.createObjectNode();
        ObjectNode bool = objectMapper.createObjectNode();
        ObjectNode matchEntry = objectMapper.createObjectNode();
        matchEntry.put("category", "authentication_failure");
        ObjectNode matchClause = objectMapper.createObjectNode();
        matchClause.set("category", matchEntry);
        ObjectNode matchOuter = objectMapper.createObjectNode();
        matchOuter.set("match", matchClause);
        com.fasterxml.jackson.databind.node.ArrayNode mustArr =
            objectMapper.createArrayNode();
        mustArr.add(matchOuter);
        bool.set("must", mustArr);
        ObjectNode query = objectMapper.createObjectNode();
        query.set("bool", bool);
        root.set("query", query);
        return root;
    }

    /**
     * Object whose string value contains literal brace characters.
     * Verifies the string-literal scanner ignores {@code {}} inside JSON strings.
     */
    private ObjectNode objectWithBracesInStringValue() {
        ObjectNode root = objectMapper.createObjectNode();
        root.set("query", objectMapper.createObjectNode()
            .set("match_all", objectMapper.createObjectNode()));
        root.put("hint", "Use {wildcard} or {range} queries for flexible filtering.");
        return root;
    }

    /** Object whose string value contains escaped double-quote characters. */
    private ObjectNode objectWithEscapedQuotesInValue() {
        ObjectNode root = objectMapper.createObjectNode();
        root.set("query", objectMapper.createObjectNode()
            .set("match_all", objectMapper.createObjectNode()));
        root.put("label", "Find \"failed\" login attempts");
        return root;
    }

    /** Object with an array-valued field. */
    private ObjectNode objectWithArrayField() {
        ObjectNode root = objectMapper.createObjectNode();
        root.set("query", objectMapper.createObjectNode()
            .set("match_all", objectMapper.createObjectNode()));
        com.fasterxml.jackson.databind.node.ArrayNode tags =
            objectMapper.createArrayNode();
        tags.add("auth");
        tags.add("critical");
        root.set("tags", tags);
        return root;
    }

    /** Object with a boolean field. */
    private ObjectNode objectWithBooleanField() {
        ObjectNode root = objectMapper.createObjectNode();
        root.set("query", objectMapper.createObjectNode()
            .set("match_all", objectMapper.createObjectNode()));
        root.put("track_total_hits", true);
        return root;
    }

    /** Three-level deeply nested object. */
    private ObjectNode deeplyNestedObject() {
        ObjectNode root = objectMapper.createObjectNode();
        ObjectNode level1 = objectMapper.createObjectNode();
        ObjectNode level2 = objectMapper.createObjectNode();
        ObjectNode level3 = objectMapper.createObjectNode();
        level3.put("field", "value");
        level2.set("deep", level3);
        level1.set("inner", level2);
        root.set("query", level1);
        root.put("confidence", 0.6);
        return root;
    }
}
