package com.hivearmor.web.rest.hunt;

import com.hivearmor.multitenancy.MsspIndexResolver;
import com.hivearmor.multitenancy.TenantContext;
import com.hivearmor.service.elasticsearch.OpensearchClientBuilder;
import com.hivearmor.service.hunt.HaSuppressionAnalysisService;
import com.hivearmor.service.hunt.dto.ExceptionPreviewRequest;
import com.hivearmor.service.hunt.dto.ExceptionPreviewResponse;
import org.opensearch.client.opensearch._types.query_dsl.Query;
import org.opensearch.client.opensearch.core.SearchRequest;
import org.opensearch.client.opensearch.core.SearchResponse;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.*;

import java.time.Instant;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * HiveArmor REST controller for detection exception preview impact analysis.
 *
 * <p>{@code POST /api/ha-detection-rules/{ruleId}/exceptions/preview} — accepts a proposed
 * exception condition and returns a read-only impact projection showing how many
 * historical alerts match, projected volume reduction, affected MITRE techniques,
 * overlap with existing exceptions, and risk assessment.
 *
 * <p><strong>Read-only guarantee:</strong> This endpoint does NOT create, update, or
 * delete any stored data. It does NOT write to any OpenSearch index. The entire
 * operation is a pure analytical read against historical alert data.
 *
 * <p>Requires {@code ROLE_SOC_MANAGER}, {@code ROLE_SOC_LEAD}, or {@code ROLE_ADMIN} authority.
 *
 * <p>Sprint 37 — ALT-021 (Requirement 2.2).
 */
@RestController
@RequestMapping("/api")
public class HaExceptionPreviewResource {

    private static final Logger log = LoggerFactory.getLogger(HaExceptionPreviewResource.class);
    private static final String CLASSNAME = "HaExceptionPreviewResource";

    private static final String EXCEPTION_PREVIEW_AUTH =
        "hasAnyAuthority('ROLE_SOC_MANAGER', 'ROLE_SOC_LEAD', 'ROLE_ADMIN')";

    private final HaSuppressionAnalysisService suppressionAnalysisService;
    private final OpensearchClientBuilder osClient;
    private final MsspIndexResolver indexResolver;

    public HaExceptionPreviewResource(HaSuppressionAnalysisService suppressionAnalysisService,
                                      OpensearchClientBuilder osClient,
                                      MsspIndexResolver indexResolver) {
        this.suppressionAnalysisService = suppressionAnalysisService;
        this.osClient = osClient;
        this.indexResolver = indexResolver;
    }

    /**
     * POST /api/ha-detection-rules/{ruleId}/exceptions/preview
     *
     * <p>Returns a read-only impact analysis for a proposed detection rule exception.
     * No mutations occur — this is a pure analytical query against historical alert data
     * in OpenSearch.
     *
     * @param ruleId  the detection rule ID to evaluate the exception against
     * @param request the request body containing the proposed exception condition tuples
     * @return ResponseEntity containing the {@link ExceptionPreviewResponse}, or an error
     */
    @PostMapping("/ha-detection-rules/{ruleId}/exceptions/preview")
    @PreAuthorize(EXCEPTION_PREVIEW_AUTH)
    public ResponseEntity<?> preview(@PathVariable String ruleId,
                                     @RequestBody ExceptionPreviewRequest request) {
        try {
            // ─── Task 4.12: Validate proposed condition is not empty ─────────────
            if (request.conditions() == null || request.conditions().isEmpty()) {
                return badRequest("INVALID_CONDITION",
                    "Proposed exception condition must contain at least one condition tuple");
            }

            // ─── Task 4.11: Verify rule exists (alerts generated by this rule) ──
            String indexPattern = indexResolver.resolveAlertIndexPattern();
            SearchRequest existsRequest = SearchRequest.of(r -> r
                .index(indexPattern)
                .query(Query.of(q -> q.bool(b -> b
                    .should(List.of(
                        Query.of(sq -> sq.term(t -> t
                            .field("ruleId.keyword")
                            .value(v -> v.stringValue(ruleId)))),
                        Query.of(sq -> sq.term(t -> t
                            .field("ruleName.keyword")
                            .value(v -> v.stringValue(ruleId))))
                    ))
                    .minimumShouldMatch("1"))))
                .size(0));

            SearchResponse<Void> existsResponse = osClient.execute(os -> os.search(existsRequest, Void.class));
            long alertCount = existsResponse.hits().total() != null
                ? existsResponse.hits().total().value() : 0;

            if (alertCount == 0) {
                return notFound("Detection rule not found: " + ruleId);
            }

            // ─── Task 4.13: Read-only analysis — no mutations, no index writes ──
            ExceptionPreviewResponse response =
                suppressionAnalysisService.analyzeExceptionImpact(ruleId, request.conditions());

            return ResponseEntity.ok(response);

        } catch (IllegalArgumentException e) {
            return badRequest("INVALID_CONDITION", e.getMessage());
        } catch (Exception e) {
            log.error("{}.preview: ruleId={}, error={}", CLASSNAME, ruleId, e.getMessage(), e);
            return ResponseEntity.internalServerError().build();
        } finally {
            TenantContext.clear();
        }
    }

    /**
     * Builds a 400 Bad Request response with a structured error body.
     */
    private ResponseEntity<Map<String, Object>> badRequest(String errorCode, String message) {
        Map<String, Object> error = new LinkedHashMap<>();
        error.put("errorCode", errorCode);
        error.put("message", message);
        error.put("timestamp", Instant.now().toString());
        return ResponseEntity.badRequest().body(error);
    }

    /**
     * Builds a 404 Not Found response with a structured error body.
     */
    private ResponseEntity<Map<String, Object>> notFound(String message) {
        Map<String, Object> error = new LinkedHashMap<>();
        error.put("message", message);
        error.put("timestamp", Instant.now().toString());
        return ResponseEntity.status(404).body(error);
    }
}
