// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: agent.proto

package agent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentCommandStatus int32

const (
	AgentCommandStatus_NOT_EXECUTED AgentCommandStatus = 0
	AgentCommandStatus_QUEUE        AgentCommandStatus = 1
	AgentCommandStatus_PENDING      AgentCommandStatus = 2
	AgentCommandStatus_EXECUTED     AgentCommandStatus = 3
	AgentCommandStatus_ERROR        AgentCommandStatus = 4
)

// Enum value maps for AgentCommandStatus.
var (
	AgentCommandStatus_name = map[int32]string{
		0: "NOT_EXECUTED",
		1: "QUEUE",
		2: "PENDING",
		3: "EXECUTED",
		4: "ERROR",
	}
	AgentCommandStatus_value = map[string]int32{
		"NOT_EXECUTED": 0,
		"QUEUE":        1,
		"PENDING":      2,
		"EXECUTED":     3,
		"ERROR":        4,
	}
)

func (x AgentCommandStatus) Enum() *AgentCommandStatus {
	p := new(AgentCommandStatus)
	*p = x
	return p
}

func (x AgentCommandStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentCommandStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_enumTypes[0].Descriptor()
}

func (AgentCommandStatus) Type() protoreflect.EnumType {
	return &file_agent_proto_enumTypes[0]
}

func (x AgentCommandStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentCommandStatus.Descriptor instead.
func (AgentCommandStatus) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

type AgentRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Ip             string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Hostname       string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os             string                 `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
	Platform       string                 `protobuf:"bytes,4,opt,name=platform,proto3" json:"platform,omitempty"`
	Version        string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	RegisterBy     string                 `protobuf:"bytes,6,opt,name=register_by,json=registerBy,proto3" json:"register_by,omitempty"`
	Mac            string                 `protobuf:"bytes,7,opt,name=mac,proto3" json:"mac,omitempty"`
	OsMajorVersion string                 `protobuf:"bytes,8,opt,name=os_major_version,json=osMajorVersion,proto3" json:"os_major_version,omitempty"`
	OsMinorVersion string                 `protobuf:"bytes,9,opt,name=os_minor_version,json=osMinorVersion,proto3" json:"os_minor_version,omitempty"`
	Aliases        string                 `protobuf:"bytes,10,opt,name=aliases,proto3" json:"aliases,omitempty"`
	Addresses      string                 `protobuf:"bytes,11,opt,name=addresses,proto3" json:"addresses,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AgentRequest) Reset() {
	*x = AgentRequest{}
	mi := &file_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRequest) ProtoMessage() {}

func (x *AgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRequest.ProtoReflect.Descriptor instead.
func (*AgentRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AgentRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *AgentRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *AgentRequest) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *AgentRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *AgentRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AgentRequest) GetRegisterBy() string {
	if x != nil {
		return x.RegisterBy
	}
	return ""
}

func (x *AgentRequest) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *AgentRequest) GetOsMajorVersion() string {
	if x != nil {
		return x.OsMajorVersion
	}
	return ""
}

func (x *AgentRequest) GetOsMinorVersion() string {
	if x != nil {
		return x.OsMinorVersion
	}
	return ""
}

func (x *AgentRequest) GetAliases() string {
	if x != nil {
		return x.Aliases
	}
	return ""
}

func (x *AgentRequest) GetAddresses() string {
	if x != nil {
		return x.Addresses
	}
	return ""
}

type ListAgentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          []*Agent               `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsResponse) Reset() {
	*x = ListAgentsResponse{}
	mi := &file_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsResponse) ProtoMessage() {}

func (x *ListAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsResponse.ProtoReflect.Descriptor instead.
func (*ListAgentsResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *ListAgentsResponse) GetRows() []*Agent {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *ListAgentsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type Agent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Ip             string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Hostname       string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os             string                 `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
	Status         Status                 `protobuf:"varint,4,opt,name=status,proto3,enum=agent.Status" json:"status,omitempty"`
	Platform       string                 `protobuf:"bytes,5,opt,name=platform,proto3" json:"platform,omitempty"`
	Version        string                 `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	AgentKey       string                 `protobuf:"bytes,7,opt,name=agent_key,json=agentKey,proto3" json:"agent_key,omitempty"`
	Id             uint32                 `protobuf:"varint,8,opt,name=id,proto3" json:"id,omitempty"`
	LastSeen       string                 `protobuf:"bytes,9,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	Mac            string                 `protobuf:"bytes,10,opt,name=mac,proto3" json:"mac,omitempty"`
	OsMajorVersion string                 `protobuf:"bytes,11,opt,name=os_major_version,json=osMajorVersion,proto3" json:"os_major_version,omitempty"`
	OsMinorVersion string                 `protobuf:"bytes,12,opt,name=os_minor_version,json=osMinorVersion,proto3" json:"os_minor_version,omitempty"`
	Aliases        string                 `protobuf:"bytes,13,opt,name=aliases,proto3" json:"aliases,omitempty"`
	Addresses      string                 `protobuf:"bytes,14,opt,name=addresses,proto3" json:"addresses,omitempty"`
	Commands       []*AgentCommand        `protobuf:"bytes,15,rep,name=commands,proto3" json:"commands,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Agent) Reset() {
	*x = Agent{}
	mi := &file_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Agent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Agent) ProtoMessage() {}

func (x *Agent) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Agent.ProtoReflect.Descriptor instead.
func (*Agent) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

func (x *Agent) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Agent) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Agent) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *Agent) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_ONLINE
}

func (x *Agent) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *Agent) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Agent) GetAgentKey() string {
	if x != nil {
		return x.AgentKey
	}
	return ""
}

func (x *Agent) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Agent) GetLastSeen() string {
	if x != nil {
		return x.LastSeen
	}
	return ""
}

func (x *Agent) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *Agent) GetOsMajorVersion() string {
	if x != nil {
		return x.OsMajorVersion
	}
	return ""
}

func (x *Agent) GetOsMinorVersion() string {
	if x != nil {
		return x.OsMinorVersion
	}
	return ""
}

func (x *Agent) GetAliases() string {
	if x != nil {
		return x.Aliases
	}
	return ""
}

func (x *Agent) GetAddresses() string {
	if x != nil {
		return x.Addresses
	}
	return ""
}

func (x *Agent) GetCommands() []*AgentCommand {
	if x != nil {
		return x.Commands
	}
	return nil
}

type BidirectionalStream struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to StreamMessage:
	//
	//	*BidirectionalStream_Command
	//	*BidirectionalStream_Result
	StreamMessage isBidirectionalStream_StreamMessage `protobuf_oneof:"stream_message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidirectionalStream) Reset() {
	*x = BidirectionalStream{}
	mi := &file_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidirectionalStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidirectionalStream) ProtoMessage() {}

func (x *BidirectionalStream) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidirectionalStream.ProtoReflect.Descriptor instead.
func (*BidirectionalStream) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

func (x *BidirectionalStream) GetStreamMessage() isBidirectionalStream_StreamMessage {
	if x != nil {
		return x.StreamMessage
	}
	return nil
}

func (x *BidirectionalStream) GetCommand() *UtmCommand {
	if x != nil {
		if x, ok := x.StreamMessage.(*BidirectionalStream_Command); ok {
			return x.Command
		}
	}
	return nil
}

func (x *BidirectionalStream) GetResult() *CommandResult {
	if x != nil {
		if x, ok := x.StreamMessage.(*BidirectionalStream_Result); ok {
			return x.Result
		}
	}
	return nil
}

type isBidirectionalStream_StreamMessage interface {
	isBidirectionalStream_StreamMessage()
}

type BidirectionalStream_Command struct {
	Command *UtmCommand `protobuf:"bytes,1,opt,name=command,proto3,oneof"`
}

type BidirectionalStream_Result struct {
	Result *CommandResult `protobuf:"bytes,2,opt,name=result,proto3,oneof"`
}

func (*BidirectionalStream_Command) isBidirectionalStream_StreamMessage() {}

func (*BidirectionalStream_Result) isBidirectionalStream_StreamMessage() {}

type UtmCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	ExecutedBy    string                 `protobuf:"bytes,3,opt,name=executed_by,json=executedBy,proto3" json:"executed_by,omitempty"`
	CmdId         string                 `protobuf:"bytes,4,opt,name=cmd_id,json=cmdId,proto3" json:"cmd_id,omitempty"`
	OriginType    string                 `protobuf:"bytes,5,opt,name=origin_type,json=originType,proto3" json:"origin_type,omitempty"`
	OriginId      string                 `protobuf:"bytes,6,opt,name=origin_id,json=originId,proto3" json:"origin_id,omitempty"`
	Reason        string                 `protobuf:"bytes,7,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UtmCommand) Reset() {
	*x = UtmCommand{}
	mi := &file_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UtmCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UtmCommand) ProtoMessage() {}

func (x *UtmCommand) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UtmCommand.ProtoReflect.Descriptor instead.
func (*UtmCommand) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

func (x *UtmCommand) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *UtmCommand) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *UtmCommand) GetExecutedBy() string {
	if x != nil {
		return x.ExecutedBy
	}
	return ""
}

func (x *UtmCommand) GetCmdId() string {
	if x != nil {
		return x.CmdId
	}
	return ""
}

func (x *UtmCommand) GetOriginType() string {
	if x != nil {
		return x.OriginType
	}
	return ""
}

func (x *UtmCommand) GetOriginId() string {
	if x != nil {
		return x.OriginId
	}
	return ""
}

func (x *UtmCommand) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CommandResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Result        string                 `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	ExecutedAt    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=executed_at,json=executedAt,proto3" json:"executed_at,omitempty"`
	CmdId         string                 `protobuf:"bytes,4,opt,name=cmd_id,json=cmdId,proto3" json:"cmd_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{5}
}

func (x *CommandResult) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *CommandResult) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *CommandResult) GetExecutedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExecutedAt
	}
	return nil
}

func (x *CommandResult) GetCmdId() string {
	if x != nil {
		return x.CmdId
	}
	return ""
}

type ListAgentsCommandsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          []*AgentCommand        `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsCommandsResponse) Reset() {
	*x = ListAgentsCommandsResponse{}
	mi := &file_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsCommandsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsCommandsResponse) ProtoMessage() {}

func (x *ListAgentsCommandsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsCommandsResponse.ProtoReflect.Descriptor instead.
func (*ListAgentsCommandsResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{6}
}

func (x *ListAgentsCommandsResponse) GetRows() []*AgentCommand {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *ListAgentsCommandsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type AgentCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	AgentId       uint32                 `protobuf:"varint,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Command       string                 `protobuf:"bytes,4,opt,name=command,proto3" json:"command,omitempty"`
	CommandStatus AgentCommandStatus     `protobuf:"varint,5,opt,name=command_status,json=commandStatus,proto3,enum=agent.AgentCommandStatus" json:"command_status,omitempty"`
	Result        string                 `protobuf:"bytes,6,opt,name=result,proto3" json:"result,omitempty"`
	ExecutedBy    string                 `protobuf:"bytes,7,opt,name=executed_by,json=executedBy,proto3" json:"executed_by,omitempty"`
	CmdId         string                 `protobuf:"bytes,8,opt,name=cmd_id,json=cmdId,proto3" json:"cmd_id,omitempty"`
	Reason        string                 `protobuf:"bytes,9,opt,name=reason,proto3" json:"reason,omitempty"`
	OriginType    string                 `protobuf:"bytes,10,opt,name=origin_type,json=originType,proto3" json:"origin_type,omitempty"`
	OriginId      string                 `protobuf:"bytes,11,opt,name=origin_id,json=originId,proto3" json:"origin_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentCommand) Reset() {
	*x = AgentCommand{}
	mi := &file_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentCommand) ProtoMessage() {}

func (x *AgentCommand) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentCommand.ProtoReflect.Descriptor instead.
func (*AgentCommand) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{7}
}

func (x *AgentCommand) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AgentCommand) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *AgentCommand) GetAgentId() uint32 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *AgentCommand) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *AgentCommand) GetCommandStatus() AgentCommandStatus {
	if x != nil {
		return x.CommandStatus
	}
	return AgentCommandStatus_NOT_EXECUTED
}

func (x *AgentCommand) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *AgentCommand) GetExecutedBy() string {
	if x != nil {
		return x.ExecutedBy
	}
	return ""
}

func (x *AgentCommand) GetCmdId() string {
	if x != nil {
		return x.CmdId
	}
	return ""
}

func (x *AgentCommand) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *AgentCommand) GetOriginType() string {
	if x != nil {
		return x.OriginType
	}
	return ""
}

func (x *AgentCommand) GetOriginId() string {
	if x != nil {
		return x.OriginId
	}
	return ""
}

type VerifyConnectorIdentityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnectorId   uint32                 `protobuf:"varint,1,opt,name=connector_id,json=connectorId,proto3" json:"connector_id,omitempty"`
	PresentedKey  string                 `protobuf:"bytes,2,opt,name=presented_key,json=presentedKey,proto3" json:"presented_key,omitempty"`
	ConnectorType ConnectorType          `protobuf:"varint,3,opt,name=connector_type,json=connectorType,proto3,enum=agent.ConnectorType" json:"connector_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyConnectorIdentityRequest) Reset() {
	*x = VerifyConnectorIdentityRequest{}
	mi := &file_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyConnectorIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyConnectorIdentityRequest) ProtoMessage() {}

func (x *VerifyConnectorIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyConnectorIdentityRequest.ProtoReflect.Descriptor instead.
func (*VerifyConnectorIdentityRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{8}
}

func (x *VerifyConnectorIdentityRequest) GetConnectorId() uint32 {
	if x != nil {
		return x.ConnectorId
	}
	return 0
}

func (x *VerifyConnectorIdentityRequest) GetPresentedKey() string {
	if x != nil {
		return x.PresentedKey
	}
	return ""
}

func (x *VerifyConnectorIdentityRequest) GetConnectorType() ConnectorType {
	if x != nil {
		return x.ConnectorType
	}
	return ConnectorType_AGENT
}

type VerifyConnectorIdentityResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uuid              string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	TenantId          int64                  `protobuf:"varint,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	CredentialVersion uint32                 `protobuf:"varint,4,opt,name=credential_version,json=credentialVersion,proto3" json:"credential_version,omitempty"`
	Revoked           bool                   `protobuf:"varint,5,opt,name=revoked,proto3" json:"revoked,omitempty"`
	ConnectorType     ConnectorType          `protobuf:"varint,6,opt,name=connector_type,json=connectorType,proto3,enum=agent.ConnectorType" json:"connector_type,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *VerifyConnectorIdentityResponse) Reset() {
	*x = VerifyConnectorIdentityResponse{}
	mi := &file_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyConnectorIdentityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyConnectorIdentityResponse) ProtoMessage() {}

func (x *VerifyConnectorIdentityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyConnectorIdentityResponse.ProtoReflect.Descriptor instead.
func (*VerifyConnectorIdentityResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{9}
}

func (x *VerifyConnectorIdentityResponse) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *VerifyConnectorIdentityResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *VerifyConnectorIdentityResponse) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *VerifyConnectorIdentityResponse) GetCredentialVersion() uint32 {
	if x != nil {
		return x.CredentialVersion
	}
	return 0
}

func (x *VerifyConnectorIdentityResponse) GetRevoked() bool {
	if x != nil {
		return x.Revoked
	}
	return false
}

func (x *VerifyConnectorIdentityResponse) GetConnectorType() ConnectorType {
	if x != nil {
		return x.ConnectorType
	}
	return ConnectorType_AGENT
}

type ListConnectorAuthorizationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnectorType ConnectorType          `protobuf:"varint,1,opt,name=connector_type,json=connectorType,proto3,enum=agent.ConnectorType" json:"connector_type,omitempty"`
	PageNumber    int32                  `protobuf:"varint,2,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConnectorAuthorizationRequest) Reset() {
	*x = ListConnectorAuthorizationRequest{}
	mi := &file_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConnectorAuthorizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConnectorAuthorizationRequest) ProtoMessage() {}

func (x *ListConnectorAuthorizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConnectorAuthorizationRequest.ProtoReflect.Descriptor instead.
func (*ListConnectorAuthorizationRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{10}
}

func (x *ListConnectorAuthorizationRequest) GetConnectorType() ConnectorType {
	if x != nil {
		return x.ConnectorType
	}
	return ConnectorType_AGENT
}

func (x *ListConnectorAuthorizationRequest) GetPageNumber() int32 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

func (x *ListConnectorAuthorizationRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ConnectorAuthorization struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uuid              string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	TenantId          int64                  `protobuf:"varint,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Revoked           bool                   `protobuf:"varint,4,opt,name=revoked,proto3" json:"revoked,omitempty"`
	CredentialVersion uint32                 `protobuf:"varint,5,opt,name=credential_version,json=credentialVersion,proto3" json:"credential_version,omitempty"`
	ConnectorType     ConnectorType          `protobuf:"varint,6,opt,name=connector_type,json=connectorType,proto3,enum=agent.ConnectorType" json:"connector_type,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ConnectorAuthorization) Reset() {
	*x = ConnectorAuthorization{}
	mi := &file_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectorAuthorization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectorAuthorization) ProtoMessage() {}

func (x *ConnectorAuthorization) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectorAuthorization.ProtoReflect.Descriptor instead.
func (*ConnectorAuthorization) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{11}
}

func (x *ConnectorAuthorization) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ConnectorAuthorization) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ConnectorAuthorization) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *ConnectorAuthorization) GetRevoked() bool {
	if x != nil {
		return x.Revoked
	}
	return false
}

func (x *ConnectorAuthorization) GetCredentialVersion() uint32 {
	if x != nil {
		return x.CredentialVersion
	}
	return 0
}

func (x *ConnectorAuthorization) GetConnectorType() ConnectorType {
	if x != nil {
		return x.ConnectorType
	}
	return ConnectorType_AGENT
}

type ListConnectorAuthorizationResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Rows          []*ConnectorAuthorization `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	Total         int32                     `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConnectorAuthorizationResponse) Reset() {
	*x = ListConnectorAuthorizationResponse{}
	mi := &file_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConnectorAuthorizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConnectorAuthorizationResponse) ProtoMessage() {}

func (x *ListConnectorAuthorizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConnectorAuthorizationResponse.ProtoReflect.Descriptor instead.
func (*ListConnectorAuthorizationResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{12}
}

func (x *ListConnectorAuthorizationResponse) GetRows() []*ConnectorAuthorization {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *ListConnectorAuthorizationResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_agent_proto protoreflect.FileDescriptor

const file_agent_proto_rawDesc = "" +
	"\n" +
	"\vagent.proto\x12\x05agent\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\fcommon.proto\"\xbf\x02\n" +
	"\fAgentRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x03 \x01(\tR\x02os\x12\x1a\n" +
	"\bplatform\x18\x04 \x01(\tR\bplatform\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x12\x1f\n" +
	"\vregister_by\x18\x06 \x01(\tR\n" +
	"registerBy\x12\x10\n" +
	"\x03mac\x18\a \x01(\tR\x03mac\x12(\n" +
	"\x10os_major_version\x18\b \x01(\tR\x0eosMajorVersion\x12(\n" +
	"\x10os_minor_version\x18\t \x01(\tR\x0eosMinorVersion\x12\x18\n" +
	"\aaliases\x18\n" +
	" \x01(\tR\aaliases\x12\x1c\n" +
	"\taddresses\x18\v \x01(\tR\taddresses\"L\n" +
	"\x12ListAgentsResponse\x12 \n" +
	"\x04rows\x18\x01 \x03(\v2\f.agent.AgentR\x04rows\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xb9\x03\n" +
	"\x05Agent\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x03 \x01(\tR\x02os\x12%\n" +
	"\x06status\x18\x04 \x01(\x0e2\r.agent.StatusR\x06status\x12\x1a\n" +
	"\bplatform\x18\x05 \x01(\tR\bplatform\x12\x18\n" +
	"\aversion\x18\x06 \x01(\tR\aversion\x12\x1b\n" +
	"\tagent_key\x18\a \x01(\tR\bagentKey\x12\x0e\n" +
	"\x02id\x18\b \x01(\rR\x02id\x12\x1b\n" +
	"\tlast_seen\x18\t \x01(\tR\blastSeen\x12\x10\n" +
	"\x03mac\x18\n" +
	" \x01(\tR\x03mac\x12(\n" +
	"\x10os_major_version\x18\v \x01(\tR\x0eosMajorVersion\x12(\n" +
	"\x10os_minor_version\x18\f \x01(\tR\x0eosMinorVersion\x12\x18\n" +
	"\aaliases\x18\r \x01(\tR\aaliases\x12\x1c\n" +
	"\taddresses\x18\x0e \x01(\tR\taddresses\x12/\n" +
	"\bcommands\x18\x0f \x03(\v2\x13.agent.AgentCommandR\bcommands\"\x86\x01\n" +
	"\x13BidirectionalStream\x12-\n" +
	"\acommand\x18\x01 \x01(\v2\x11.agent.UtmCommandH\x00R\acommand\x12.\n" +
	"\x06result\x18\x02 \x01(\v2\x14.agent.CommandResultH\x00R\x06resultB\x10\n" +
	"\x0estream_message\"\xcf\x01\n" +
	"\n" +
	"UtmCommand\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x1f\n" +
	"\vexecuted_by\x18\x03 \x01(\tR\n" +
	"executedBy\x12\x15\n" +
	"\x06cmd_id\x18\x04 \x01(\tR\x05cmdId\x12\x1f\n" +
	"\vorigin_type\x18\x05 \x01(\tR\n" +
	"originType\x12\x1b\n" +
	"\torigin_id\x18\x06 \x01(\tR\boriginId\x12\x16\n" +
	"\x06reason\x18\a \x01(\tR\x06reason\"\x96\x01\n" +
	"\rCommandResult\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x16\n" +
	"\x06result\x18\x02 \x01(\tR\x06result\x12;\n" +
	"\vexecuted_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"executedAt\x12\x15\n" +
	"\x06cmd_id\x18\x04 \x01(\tR\x05cmdId\"[\n" +
	"\x1aListAgentsCommandsResponse\x12'\n" +
	"\x04rows\x18\x01 \x03(\v2\x13.agent.AgentCommandR\x04rows\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xa1\x03\n" +
	"\fAgentCommand\x129\n" +
	"\n" +
	"created_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\rR\aagentId\x12\x18\n" +
	"\acommand\x18\x04 \x01(\tR\acommand\x12@\n" +
	"\x0ecommand_status\x18\x05 \x01(\x0e2\x19.agent.AgentCommandStatusR\rcommandStatus\x12\x16\n" +
	"\x06result\x18\x06 \x01(\tR\x06result\x12\x1f\n" +
	"\vexecuted_by\x18\a \x01(\tR\n" +
	"executedBy\x12\x15\n" +
	"\x06cmd_id\x18\b \x01(\tR\x05cmdId\x12\x16\n" +
	"\x06reason\x18\t \x01(\tR\x06reason\x12\x1f\n" +
	"\vorigin_type\x18\n" +
	" \x01(\tR\n" +
	"originType\x12\x1b\n" +
	"\torigin_id\x18\v \x01(\tR\boriginId\"\xa5\x01\n" +
	"\x1eVerifyConnectorIdentityRequest\x12!\n" +
	"\fconnector_id\x18\x01 \x01(\rR\vconnectorId\x12#\n" +
	"\rpresented_key\x18\x02 \x01(\tR\fpresentedKey\x12;\n" +
	"\x0econnector_type\x18\x03 \x01(\x0e2\x14.agent.ConnectorTypeR\rconnectorType\"\xe8\x01\n" +
	"\x1fVerifyConnectorIdentityResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\x03R\btenantId\x12-\n" +
	"\x12credential_version\x18\x04 \x01(\rR\x11credentialVersion\x12\x18\n" +
	"\arevoked\x18\x05 \x01(\bR\arevoked\x12;\n" +
	"\x0econnector_type\x18\x06 \x01(\x0e2\x14.agent.ConnectorTypeR\rconnectorType\"\x9e\x01\n" +
	"!ListConnectorAuthorizationRequest\x12;\n" +
	"\x0econnector_type\x18\x01 \x01(\x0e2\x14.agent.ConnectorTypeR\rconnectorType\x12\x1f\n" +
	"\vpage_number\x18\x02 \x01(\x05R\n" +
	"pageNumber\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\xdf\x01\n" +
	"\x16ConnectorAuthorization\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\x03R\btenantId\x12\x18\n" +
	"\arevoked\x18\x04 \x01(\bR\arevoked\x12-\n" +
	"\x12credential_version\x18\x05 \x01(\rR\x11credentialVersion\x12;\n" +
	"\x0econnector_type\x18\x06 \x01(\x0e2\x14.agent.ConnectorTypeR\rconnectorType\"m\n" +
	"\"ListConnectorAuthorizationResponse\x121\n" +
	"\x04rows\x18\x01 \x03(\v2\x1d.agent.ConnectorAuthorizationR\x04rows\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total*W\n" +
	"\x12AgentCommandStatus\x12\x10\n" +
	"\fNOT_EXECUTED\x10\x00\x12\t\n" +
	"\x05QUEUE\x10\x01\x12\v\n" +
	"\aPENDING\x10\x02\x12\f\n" +
	"\bEXECUTED\x10\x03\x12\t\n" +
	"\x05ERROR\x10\x042\xc2\x04\n" +
	"\fAgentService\x12;\n" +
	"\rRegisterAgent\x12\x13.agent.AgentRequest\x1a\x13.agent.AuthResponse\"\x00\x12:\n" +
	"\vDeleteAgent\x12\x14.agent.DeleteRequest\x1a\x13.agent.AuthResponse\"\x00\x12=\n" +
	"\n" +
	"ListAgents\x12\x12.agent.ListRequest\x1a\x19.agent.ListAgentsResponse\"\x00\x12K\n" +
	"\vAgentStream\x12\x1a.agent.BidirectionalStream\x1a\x1a.agent.BidirectionalStream\"\x00(\x010\x01\x12L\n" +
	"\x11ListAgentCommands\x12\x12.agent.ListRequest\x1a!.agent.ListAgentsCommandsResponse\"\x00\x12j\n" +
	"\x17VerifyConnectorIdentity\x12%.agent.VerifyConnectorIdentityRequest\x1a&.agent.VerifyConnectorIdentityResponse\"\x00\x12s\n" +
	"\x1aListConnectorAuthorization\x12(.agent.ListConnectorAuthorizationRequest\x1a).agent.ListConnectorAuthorizationResponse\"\x002O\n" +
	"\fPanelService\x12?\n" +
	"\x0eProcessCommand\x12\x11.agent.UtmCommand\x1a\x14.agent.CommandResult\"\x00(\x010\x01B*Z(github.com/hivearmor/agent-manager/agentb\x06proto3"

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData []byte
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)))
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_agent_proto_goTypes = []any{
	(AgentCommandStatus)(0),                    // 0: agent.AgentCommandStatus
	(*AgentRequest)(nil),                       // 1: agent.AgentRequest
	(*ListAgentsResponse)(nil),                 // 2: agent.ListAgentsResponse
	(*Agent)(nil),                              // 3: agent.Agent
	(*BidirectionalStream)(nil),                // 4: agent.BidirectionalStream
	(*UtmCommand)(nil),                         // 5: agent.UtmCommand
	(*CommandResult)(nil),                      // 6: agent.CommandResult
	(*ListAgentsCommandsResponse)(nil),         // 7: agent.ListAgentsCommandsResponse
	(*AgentCommand)(nil),                       // 8: agent.AgentCommand
	(*VerifyConnectorIdentityRequest)(nil),     // 9: agent.VerifyConnectorIdentityRequest
	(*VerifyConnectorIdentityResponse)(nil),    // 10: agent.VerifyConnectorIdentityResponse
	(*ListConnectorAuthorizationRequest)(nil),  // 11: agent.ListConnectorAuthorizationRequest
	(*ConnectorAuthorization)(nil),             // 12: agent.ConnectorAuthorization
	(*ListConnectorAuthorizationResponse)(nil), // 13: agent.ListConnectorAuthorizationResponse
	(Status)(0),                                // 14: agent.Status
	(*timestamppb.Timestamp)(nil),              // 15: google.protobuf.Timestamp
	(ConnectorType)(0),                         // 16: agent.ConnectorType
	(*DeleteRequest)(nil),                      // 17: agent.DeleteRequest
	(*ListRequest)(nil),                        // 18: agent.ListRequest
	(*AuthResponse)(nil),                       // 19: agent.AuthResponse
}
var file_agent_proto_depIdxs = []int32{
	3,  // 0: agent.ListAgentsResponse.rows:type_name -> agent.Agent
	14, // 1: agent.Agent.status:type_name -> agent.Status
	8,  // 2: agent.Agent.commands:type_name -> agent.AgentCommand
	5,  // 3: agent.BidirectionalStream.command:type_name -> agent.UtmCommand
	6,  // 4: agent.BidirectionalStream.result:type_name -> agent.CommandResult
	15, // 5: agent.CommandResult.executed_at:type_name -> google.protobuf.Timestamp
	8,  // 6: agent.ListAgentsCommandsResponse.rows:type_name -> agent.AgentCommand
	15, // 7: agent.AgentCommand.created_at:type_name -> google.protobuf.Timestamp
	15, // 8: agent.AgentCommand.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 9: agent.AgentCommand.command_status:type_name -> agent.AgentCommandStatus
	16, // 10: agent.VerifyConnectorIdentityRequest.connector_type:type_name -> agent.ConnectorType
	16, // 11: agent.VerifyConnectorIdentityResponse.connector_type:type_name -> agent.ConnectorType
	16, // 12: agent.ListConnectorAuthorizationRequest.connector_type:type_name -> agent.ConnectorType
	16, // 13: agent.ConnectorAuthorization.connector_type:type_name -> agent.ConnectorType
	12, // 14: agent.ListConnectorAuthorizationResponse.rows:type_name -> agent.ConnectorAuthorization
	1,  // 15: agent.AgentService.RegisterAgent:input_type -> agent.AgentRequest
	17, // 16: agent.AgentService.DeleteAgent:input_type -> agent.DeleteRequest
	18, // 17: agent.AgentService.ListAgents:input_type -> agent.ListRequest
	4,  // 18: agent.AgentService.AgentStream:input_type -> agent.BidirectionalStream
	18, // 19: agent.AgentService.ListAgentCommands:input_type -> agent.ListRequest
	9,  // 20: agent.AgentService.VerifyConnectorIdentity:input_type -> agent.VerifyConnectorIdentityRequest
	11, // 21: agent.AgentService.ListConnectorAuthorization:input_type -> agent.ListConnectorAuthorizationRequest
	5,  // 22: agent.PanelService.ProcessCommand:input_type -> agent.UtmCommand
	19, // 23: agent.AgentService.RegisterAgent:output_type -> agent.AuthResponse
	19, // 24: agent.AgentService.DeleteAgent:output_type -> agent.AuthResponse
	2,  // 25: agent.AgentService.ListAgents:output_type -> agent.ListAgentsResponse
	4,  // 26: agent.AgentService.AgentStream:output_type -> agent.BidirectionalStream
	7,  // 27: agent.AgentService.ListAgentCommands:output_type -> agent.ListAgentsCommandsResponse
	10, // 28: agent.AgentService.VerifyConnectorIdentity:output_type -> agent.VerifyConnectorIdentityResponse
	13, // 29: agent.AgentService.ListConnectorAuthorization:output_type -> agent.ListConnectorAuthorizationResponse
	6,  // 30: agent.PanelService.ProcessCommand:output_type -> agent.CommandResult
	23, // [23:31] is the sub-list for method output_type
	15, // [15:23] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	file_common_proto_init()
	file_agent_proto_msgTypes[3].OneofWrappers = []any{
		(*BidirectionalStream_Command)(nil),
		(*BidirectionalStream_Result)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		EnumInfos:         file_agent_proto_enumTypes,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
