blank_issues_enabled: false
contact_links:
  - name: 💬 Community Support
    url: https://github.com/encryptshellorg/hivearmor/discussions/categories/q-a
    about: Please ask and answer questions as a discussion thread

  - name: 🛟 Commercial Support
    url: https://support.hivearmor.io
    about: If you have a commercial support agreement, please file a ticket

  - name: 🏙️ HiveArmor Enterprise
    url: https://calendar.app.google/SUCGayUduYReUvxM9
    about: To learn about HiveArmor's enterprise edition and how we can assist your company, arrange a consultation with our sales representatives
