package com.hivearmor.service.rulegen;

import com.hivearmor.ai.HaLlmService;
import com.hivearmor.domain.rulegen.HaAlertSignal;
import com.hivearmor.domain.rulegen.HaRuleGenSession;
import com.hivearmor.repository.rulegen.HaAlertSignalRepository;
import com.hivearmor.repository.rulegen.HaRuleGenSessionRepository;
import com.hivearmor.service.llm.ChatMessage;
import com.hivearmor.service.llm.ChatOptions;
import com.hivearmor.service.rulegen.dto.GenerateRequest;
import com.hivearmor.service.rulegen.dto.RuleGenSessionDTO;
import com.hivearmor.service.rulegen.dto.SignalGroup;
import net.jqwik.api.*;

import java.time.Clock;
import java.time.Instant;
import java.time.ZoneOffset;
import java.util.*;
import java.util.concurrent.atomic.AtomicReference;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyLong;
import static org.mockito.Mockito.*;

/**
 * Property-based test for YAML required-key gating in the rule generation flow.
 *
 * <p><strong>Property 3: YAML validation is total on required keys</strong><br>
 * Every persisted {@code HaRuleGenSession} with status {@code pending_review} has YAML
 * that parses and contains all of {@code name}, {@code severity}, {@code dataTypes},
 * {@code definition}.
 *
 * <p>The test mocks {@code HaLlmService} to return YAML strings generated by jqwik.
 * It verifies that {@code generateRuleSuggestion} only succeeds (persists a session)
 * when the YAML contains ALL required keys. When ANY key is missing, either the method
 * throws {@code RuleGenerationException} or retries.
 *
 * <p><strong>Validates: Requirements 3.2, 3.4</strong>
 */
@Label("Feature: sprint-28-ueba-signals, Property 3: YAML validation is total on required keys")
class HaRuleGenerationServiceYamlPropertyTest {

    private static final Set<String> REQUIRED_KEYS = Set.of("name", "severity", "dataTypes", "definition");
    private static final Clock FIXED_CLOCK = Clock.fixed(Instant.parse("2026-07-25T10:00:00Z"), ZoneOffset.UTC);

    // =========================================================================
    // Property 3: Valid YAML (all keys present) => session persisted as pending_review
    // =========================================================================

    /**
     * When {@code HaLlmService.chat} returns a YAML document containing all four
     * required keys ({@code name}, {@code severity}, {@code dataTypes},
     * {@code definition}) with non-null values, {@code generateRuleSuggestion}
     * persists a {@code HaRuleGenSession} with:
     * <ul>
     *   <li>status = {@code pending_review}</li>
     *   <li>stored YAML that passes {@code YamlValidator.parseAndValidate}</li>
     *   <li>all four required keys present and non-null in the parsed YAML</li>
     * </ul>
     *
     * <p><strong>Validates: Requirements 3.2, 3.4</strong>
     */
    @Property(tries = 100)
    @Label("Property 3a: generateRuleSuggestion persists pending_review session only when YAML has all required keys")
    void validYamlProducesPendingReviewSession(
            @ForAll("completeYaml") String validYaml) {

        // -- Arrange --
        HaAlertSignalRepository signalRepo = mock(HaAlertSignalRepository.class);
        HaRuleGenSessionRepository sessionRepo = mock(HaRuleGenSessionRepository.class);
        HaLlmService llmService = mock(HaLlmService.class);

        when(signalRepo.findSignalGroupsWithMinCount(anyLong()))
            .thenReturn(List.of(new SignalGroup(
                "firewall", HaAlertSignal.SignalType.TRUE_POSITIVE,
                5, Instant.now(), Instant.now())));

        // LLM returns the jqwik-generated valid YAML
        when(llmService.chat(any(List.class), any(ChatOptions.class)))
            .thenReturn(validYaml);

        // Capture persisted session
        AtomicReference<HaRuleGenSession> captured = new AtomicReference<>();
        when(sessionRepo.save(any(HaRuleGenSession.class))).thenAnswer(inv -> {
            HaRuleGenSession session = inv.getArgument(0);
            session.setId(1L);
            captured.set(session);
            return session;
        });

        HaRuleGenerationService service = new HaRuleGenerationService(
            signalRepo, sessionRepo, llmService, FIXED_CLOCK);

        // -- Act --
        RuleGenSessionDTO result = service.generateRuleSuggestion(
            new GenerateRequest("test-signal-key", 3L));

        // -- Assert --
        // 1. A session was persisted
        assertThat(captured.get()).isNotNull();

        // 2. Status is pending_review
        assertThat(captured.get().getStatus())
            .isEqualTo(HaRuleGenSession.SessionStatus.pending_review);

        // 3. The stored YAML passes validation with all required keys
        Map<String, Object> tree = YamlValidator.parseAndValidate(captured.get().getRuleYaml());
        for (String key : REQUIRED_KEYS) {
            assertThat(tree)
                .as("Persisted YAML must contain required key '%s'", key)
                .containsKey(key);
            assertThat(tree.get(key))
                .as("Required key '%s' must not be null in persisted YAML", key)
                .isNotNull();
        }

        // 4. The returned DTO reflects pending_review
        assertThat(result.status())
            .isEqualTo(HaRuleGenSession.SessionStatus.pending_review.name());
    }

    // =========================================================================
    // Property 3: Missing keys => RuleGenerationException (no session persisted)
    // =========================================================================

    /**
     * When {@code HaLlmService.chat} consistently returns YAML missing at least one
     * required key, {@code generateRuleSuggestion} throws
     * {@code RuleGenerationException} after exhausting retries and does NOT persist
     * any session.
     *
     * <p>This verifies the gating invariant: a session can only reach
     * {@code pending_review} if its YAML contains all required keys.
     *
     * <p><strong>Validates: Requirements 3.2, 3.4</strong>
     */
    @Property(tries = 100)
    @Label("Property 3b: generateRuleSuggestion throws and persists nothing when YAML is missing required keys")
    void missingKeysNeverProduceSession(
            @ForAll("incompleteYaml") String invalidYaml) {

        // -- Arrange --
        HaAlertSignalRepository signalRepo = mock(HaAlertSignalRepository.class);
        HaRuleGenSessionRepository sessionRepo = mock(HaRuleGenSessionRepository.class);
        HaLlmService llmService = mock(HaLlmService.class);

        when(signalRepo.findSignalGroupsWithMinCount(anyLong()))
            .thenReturn(List.of(new SignalGroup(
                "endpoint", HaAlertSignal.SignalType.FALSE_POSITIVE,
                4, Instant.now(), Instant.now())));

        // LLM always returns the invalid YAML (both attempts)
        when(llmService.chat(any(List.class), any(ChatOptions.class)))
            .thenReturn(invalidYaml);

        HaRuleGenerationService service = new HaRuleGenerationService(
            signalRepo, sessionRepo, llmService, FIXED_CLOCK);

        // -- Act & Assert --
        assertThatThrownBy(() -> service.generateRuleSuggestion(
                new GenerateRequest("test-signal-key", 3L)))
            .isInstanceOf(RuleGenerationException.class);

        // No session was persisted
        verify(sessionRepo, never()).save(any());
    }

    // =========================================================================
    // Generators
    // =========================================================================

    /**
     * Generates valid YAML strings containing all four required keys with non-null
     * values. Values are quoted to prevent YAML parsing issues with special characters.
     * Additional optional keys may be present to exercise that extra content
     * does not break validation.
     */
    @Provide
    Arbitrary<String> completeYaml() {
        Arbitrary<String> names = Arbitraries.strings()
            .alpha().ofMinLength(1).ofMaxLength(30);
        Arbitrary<String> severities = Arbitraries.of("low", "medium", "high", "critical");
        Arbitrary<String> dataTypes = Arbitraries.of("firewall", "ids", "endpoint", "cloud", "auth");
        Arbitrary<String> definitions = Arbitraries.strings()
            .alpha().ofMinLength(5).ofMaxLength(60);
        Arbitrary<Integer> extraKeyCount = Arbitraries.integers().between(0, 3);

        return Combinators.combine(names, severities, dataTypes, definitions, extraKeyCount)
            .as((name, severity, dataType, definition, extras) -> {
                StringBuilder sb = new StringBuilder();
                sb.append("name: \"").append(escapeYaml(name)).append("\"\n");
                sb.append("severity: ").append(severity).append('\n');
                sb.append("dataTypes: ").append(dataType).append('\n');
                sb.append("definition: \"").append(escapeYaml(definition)).append("\"\n");
                for (int i = 0; i < extras; i++) {
                    sb.append("extra_").append(i).append(": value_").append(i).append('\n');
                }
                return sb.toString();
            });
    }

    /**
     * Generates YAML strings that are valid mappings but are missing at least one
     * of the four required keys. We randomly include a proper subset of the required
     * keys, ensuring at least one is absent.
     */
    @Provide
    Arbitrary<String> incompleteYaml() {
        Arbitrary<String> names = Arbitraries.strings()
            .alpha().ofMinLength(1).ofMaxLength(20);
        Arbitrary<String> severities = Arbitraries.of("low", "medium", "high", "critical");
        Arbitrary<String> dataTypes = Arbitraries.of("firewall", "ids", "endpoint");
        Arbitrary<String> definitions = Arbitraries.strings()
            .alpha().ofMinLength(5).ofMaxLength(40);
        // Include a proper subset of required keys (0 to 3 keys, never all 4)
        Arbitrary<Set<String>> includedKeys = Arbitraries.subsetOf(REQUIRED_KEYS)
            .filter(subset -> subset.size() < REQUIRED_KEYS.size());

        return Combinators.combine(names, severities, dataTypes, definitions, includedKeys)
            .as((name, severity, dataType, definition, included) -> {
                StringBuilder sb = new StringBuilder();
                if (included.contains("name")) {
                    sb.append("name: \"").append(escapeYaml(name)).append("\"\n");
                }
                if (included.contains("severity")) {
                    sb.append("severity: ").append(severity).append('\n');
                }
                if (included.contains("dataTypes")) {
                    sb.append("dataTypes: ").append(dataType).append('\n');
                }
                if (included.contains("definition")) {
                    sb.append("definition: \"").append(escapeYaml(definition)).append("\"\n");
                }
                // Always emit at least one key so the YAML is a valid mapping
                // (not empty/null which would trigger a different error path)
                if (sb.isEmpty()) {
                    sb.append("unrelated_key: some_value\n");
                }
                return sb.toString();
            });
    }

    // =========================================================================
    // Helpers
    // =========================================================================

    /**
     * Escapes a string for safe inclusion in a YAML double-quoted scalar.
     * Replaces backslash and double-quote characters.
     */
    private static String escapeYaml(String value) {
        if (value == null) return "";
        return value.replace("\\", "\\\\").replace("\"", "\\\"");
    }
}
