// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agent.proto
// Protobuf Java Version: 4.29.3

package com.hivearmor.service.grpc;

public interface AgentCredentialResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:agent.AgentCredentialResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 agent_id = 1;</code>
   * @return The agentId.
   */
  int getAgentId();

  /**
   * <code>string agent_uuid = 2;</code>
   * @return The agentUuid.
   */
  java.lang.String getAgentUuid();
  /**
   * <code>string agent_uuid = 2;</code>
   * @return The bytes for agentUuid.
   */
  com.google.protobuf.ByteString
      getAgentUuidBytes();

  /**
   * <code>uint32 credential_version = 3;</code>
   * @return The credentialVersion.
   */
  int getCredentialVersion();

  /**
   * <code>string key = 4;</code>
   * @return The key.
   */
  java.lang.String getKey();
  /**
   * <code>string key = 4;</code>
   * @return The bytes for key.
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <code>.google.protobuf.Timestamp revoked_at = 5;</code>
   * @return Whether the revokedAt field is set.
   */
  boolean hasRevokedAt();
  /**
   * <code>.google.protobuf.Timestamp revoked_at = 5;</code>
   * @return The revokedAt.
   */
  com.google.protobuf.Timestamp getRevokedAt();
  /**
   * <code>.google.protobuf.Timestamp revoked_at = 5;</code>
   */
  com.google.protobuf.TimestampOrBuilder getRevokedAtOrBuilder();
}
