// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agent.proto
// Protobuf Java Version: 4.29.3

package com.hivearmor.service.grpc;

/**
 * Protobuf type {@code agent.AgentCredentialResponse}
 */
public final class AgentCredentialResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:agent.AgentCredentialResponse)
    AgentCredentialResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      AgentCredentialResponse.class.getName());
  }
  // Use AgentCredentialResponse.newBuilder() to construct.
  private AgentCredentialResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private AgentCredentialResponse() {
    agentUuid_ = "";
    key_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.hivearmor.service.grpc.AgentManagerGrpc.internal_static_agent_AgentCredentialResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.hivearmor.service.grpc.AgentManagerGrpc.internal_static_agent_AgentCredentialResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.hivearmor.service.grpc.AgentCredentialResponse.class, com.hivearmor.service.grpc.AgentCredentialResponse.Builder.class);
  }

  private int bitField0_;
  public static final int AGENT_ID_FIELD_NUMBER = 1;
  private int agentId_ = 0;
  /**
   * <code>uint32 agent_id = 1;</code>
   * @return The agentId.
   */
  @java.lang.Override
  public int getAgentId() {
    return agentId_;
  }

  public static final int AGENT_UUID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object agentUuid_ = "";
  /**
   * <code>string agent_uuid = 2;</code>
   * @return The agentUuid.
   */
  @java.lang.Override
  public java.lang.String getAgentUuid() {
    java.lang.Object ref = agentUuid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      agentUuid_ = s;
      return s;
    }
  }
  /**
   * <code>string agent_uuid = 2;</code>
   * @return The bytes for agentUuid.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAgentUuidBytes() {
    java.lang.Object ref = agentUuid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      agentUuid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CREDENTIAL_VERSION_FIELD_NUMBER = 3;
  private int credentialVersion_ = 0;
  /**
   * <code>uint32 credential_version = 3;</code>
   * @return The credentialVersion.
   */
  @java.lang.Override
  public int getCredentialVersion() {
    return credentialVersion_;
  }

  public static final int KEY_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object key_ = "";
  /**
   * <code>string key = 4;</code>
   * @return The key.
   */
  @java.lang.Override
  public java.lang.String getKey() {
    java.lang.Object ref = key_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      key_ = s;
      return s;
    }
  }
  /**
   * <code>string key = 4;</code>
   * @return The bytes for key.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getKeyBytes() {
    java.lang.Object ref = key_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      key_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REVOKED_AT_FIELD_NUMBER = 5;
  private com.google.protobuf.Timestamp revokedAt_;
  /**
   * <code>.google.protobuf.Timestamp revoked_at = 5;</code>
   * @return Whether the revokedAt field is set.
   */
  @java.lang.Override
  public boolean hasRevokedAt() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.google.protobuf.Timestamp revoked_at = 5;</code>
   * @return The revokedAt.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getRevokedAt() {
    return revokedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : revokedAt_;
  }
  /**
   * <code>.google.protobuf.Timestamp revoked_at = 5;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getRevokedAtOrBuilder() {
    return revokedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : revokedAt_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (agentId_ != 0) {
      output.writeUInt32(1, agentId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(agentUuid_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, agentUuid_);
    }
    if (credentialVersion_ != 0) {
      output.writeUInt32(3, credentialVersion_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(key_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, key_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(5, getRevokedAt());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (agentId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, agentId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(agentUuid_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, agentUuid_);
    }
    if (credentialVersion_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(3, credentialVersion_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(key_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, key_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getRevokedAt());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.hivearmor.service.grpc.AgentCredentialResponse)) {
      return super.equals(obj);
    }
    com.hivearmor.service.grpc.AgentCredentialResponse other = (com.hivearmor.service.grpc.AgentCredentialResponse) obj;

    if (getAgentId()
        != other.getAgentId()) return false;
    if (!getAgentUuid()
        .equals(other.getAgentUuid())) return false;
    if (getCredentialVersion()
        != other.getCredentialVersion()) return false;
    if (!getKey()
        .equals(other.getKey())) return false;
    if (hasRevokedAt() != other.hasRevokedAt()) return false;
    if (hasRevokedAt()) {
      if (!getRevokedAt()
          .equals(other.getRevokedAt())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + AGENT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getAgentId();
    hash = (37 * hash) + AGENT_UUID_FIELD_NUMBER;
    hash = (53 * hash) + getAgentUuid().hashCode();
    hash = (37 * hash) + CREDENTIAL_VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getCredentialVersion();
    hash = (37 * hash) + KEY_FIELD_NUMBER;
    hash = (53 * hash) + getKey().hashCode();
    if (hasRevokedAt()) {
      hash = (37 * hash) + REVOKED_AT_FIELD_NUMBER;
      hash = (53 * hash) + getRevokedAt().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.hivearmor.service.grpc.AgentCredentialResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hivearmor.service.grpc.AgentCredentialResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hivearmor.service.grpc.AgentCredentialResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hivearmor.service.grpc.AgentCredentialResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hivearmor.service.grpc.AgentCredentialResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hivearmor.service.grpc.AgentCredentialResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hivearmor.service.grpc.AgentCredentialResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.hivearmor.service.grpc.AgentCredentialResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.hivearmor.service.grpc.AgentCredentialResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.hivearmor.service.grpc.AgentCredentialResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.hivearmor.service.grpc.AgentCredentialResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.hivearmor.service.grpc.AgentCredentialResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.hivearmor.service.grpc.AgentCredentialResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code agent.AgentCredentialResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:agent.AgentCredentialResponse)
      com.hivearmor.service.grpc.AgentCredentialResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hivearmor.service.grpc.AgentManagerGrpc.internal_static_agent_AgentCredentialResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hivearmor.service.grpc.AgentManagerGrpc.internal_static_agent_AgentCredentialResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hivearmor.service.grpc.AgentCredentialResponse.class, com.hivearmor.service.grpc.AgentCredentialResponse.Builder.class);
    }

    // Construct using com.hivearmor.service.grpc.AgentCredentialResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getRevokedAtFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      agentId_ = 0;
      agentUuid_ = "";
      credentialVersion_ = 0;
      key_ = "";
      revokedAt_ = null;
      if (revokedAtBuilder_ != null) {
        revokedAtBuilder_.dispose();
        revokedAtBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.hivearmor.service.grpc.AgentManagerGrpc.internal_static_agent_AgentCredentialResponse_descriptor;
    }

    @java.lang.Override
    public com.hivearmor.service.grpc.AgentCredentialResponse getDefaultInstanceForType() {
      return com.hivearmor.service.grpc.AgentCredentialResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.hivearmor.service.grpc.AgentCredentialResponse build() {
      com.hivearmor.service.grpc.AgentCredentialResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.hivearmor.service.grpc.AgentCredentialResponse buildPartial() {
      com.hivearmor.service.grpc.AgentCredentialResponse result = new com.hivearmor.service.grpc.AgentCredentialResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.hivearmor.service.grpc.AgentCredentialResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.agentId_ = agentId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.agentUuid_ = agentUuid_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.credentialVersion_ = credentialVersion_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.key_ = key_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.revokedAt_ = revokedAtBuilder_ == null
            ? revokedAt_
            : revokedAtBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.hivearmor.service.grpc.AgentCredentialResponse) {
        return mergeFrom((com.hivearmor.service.grpc.AgentCredentialResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.hivearmor.service.grpc.AgentCredentialResponse other) {
      if (other == com.hivearmor.service.grpc.AgentCredentialResponse.getDefaultInstance()) return this;
      if (other.getAgentId() != 0) {
        setAgentId(other.getAgentId());
      }
      if (!other.getAgentUuid().isEmpty()) {
        agentUuid_ = other.agentUuid_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getCredentialVersion() != 0) {
        setCredentialVersion(other.getCredentialVersion());
      }
      if (!other.getKey().isEmpty()) {
        key_ = other.key_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.hasRevokedAt()) {
        mergeRevokedAt(other.getRevokedAt());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              agentId_ = input.readUInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              agentUuid_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              credentialVersion_ = input.readUInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              key_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  getRevokedAtFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int agentId_ ;
    /**
     * <code>uint32 agent_id = 1;</code>
     * @return The agentId.
     */
    @java.lang.Override
    public int getAgentId() {
      return agentId_;
    }
    /**
     * <code>uint32 agent_id = 1;</code>
     * @param value The agentId to set.
     * @return This builder for chaining.
     */
    public Builder setAgentId(int value) {

      agentId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 agent_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAgentId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      agentId_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object agentUuid_ = "";
    /**
     * <code>string agent_uuid = 2;</code>
     * @return The agentUuid.
     */
    public java.lang.String getAgentUuid() {
      java.lang.Object ref = agentUuid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        agentUuid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string agent_uuid = 2;</code>
     * @return The bytes for agentUuid.
     */
    public com.google.protobuf.ByteString
        getAgentUuidBytes() {
      java.lang.Object ref = agentUuid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        agentUuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string agent_uuid = 2;</code>
     * @param value The agentUuid to set.
     * @return This builder for chaining.
     */
    public Builder setAgentUuid(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      agentUuid_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string agent_uuid = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAgentUuid() {
      agentUuid_ = getDefaultInstance().getAgentUuid();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string agent_uuid = 2;</code>
     * @param value The bytes for agentUuid to set.
     * @return This builder for chaining.
     */
    public Builder setAgentUuidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      agentUuid_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private int credentialVersion_ ;
    /**
     * <code>uint32 credential_version = 3;</code>
     * @return The credentialVersion.
     */
    @java.lang.Override
    public int getCredentialVersion() {
      return credentialVersion_;
    }
    /**
     * <code>uint32 credential_version = 3;</code>
     * @param value The credentialVersion to set.
     * @return This builder for chaining.
     */
    public Builder setCredentialVersion(int value) {

      credentialVersion_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 credential_version = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCredentialVersion() {
      bitField0_ = (bitField0_ & ~0x00000004);
      credentialVersion_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object key_ = "";
    /**
     * <code>string key = 4;</code>
     * @return The key.
     */
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        key_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string key = 4;</code>
     * @return The bytes for key.
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string key = 4;</code>
     * @param value The key to set.
     * @return This builder for chaining.
     */
    public Builder setKey(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      key_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string key = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearKey() {
      key_ = getDefaultInstance().getKey();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string key = 4;</code>
     * @param value The bytes for key to set.
     * @return This builder for chaining.
     */
    public Builder setKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      key_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp revokedAt_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> revokedAtBuilder_;
    /**
     * <code>.google.protobuf.Timestamp revoked_at = 5;</code>
     * @return Whether the revokedAt field is set.
     */
    public boolean hasRevokedAt() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp revoked_at = 5;</code>
     * @return The revokedAt.
     */
    public com.google.protobuf.Timestamp getRevokedAt() {
      if (revokedAtBuilder_ == null) {
        return revokedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : revokedAt_;
      } else {
        return revokedAtBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp revoked_at = 5;</code>
     */
    public Builder setRevokedAt(com.google.protobuf.Timestamp value) {
      if (revokedAtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        revokedAt_ = value;
      } else {
        revokedAtBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp revoked_at = 5;</code>
     */
    public Builder setRevokedAt(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (revokedAtBuilder_ == null) {
        revokedAt_ = builderForValue.build();
      } else {
        revokedAtBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp revoked_at = 5;</code>
     */
    public Builder mergeRevokedAt(com.google.protobuf.Timestamp value) {
      if (revokedAtBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
          revokedAt_ != null &&
          revokedAt_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getRevokedAtBuilder().mergeFrom(value);
        } else {
          revokedAt_ = value;
        }
      } else {
        revokedAtBuilder_.mergeFrom(value);
      }
      if (revokedAt_ != null) {
        bitField0_ |= 0x00000010;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp revoked_at = 5;</code>
     */
    public Builder clearRevokedAt() {
      bitField0_ = (bitField0_ & ~0x00000010);
      revokedAt_ = null;
      if (revokedAtBuilder_ != null) {
        revokedAtBuilder_.dispose();
        revokedAtBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp revoked_at = 5;</code>
     */
    public com.google.protobuf.Timestamp.Builder getRevokedAtBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return getRevokedAtFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp revoked_at = 5;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getRevokedAtOrBuilder() {
      if (revokedAtBuilder_ != null) {
        return revokedAtBuilder_.getMessageOrBuilder();
      } else {
        return revokedAt_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : revokedAt_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp revoked_at = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getRevokedAtFieldBuilder() {
      if (revokedAtBuilder_ == null) {
        revokedAtBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getRevokedAt(),
                getParentForChildren(),
                isClean());
        revokedAt_ = null;
      }
      return revokedAtBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:agent.AgentCredentialResponse)
  }

  // @@protoc_insertion_point(class_scope:agent.AgentCredentialResponse)
  private static final com.hivearmor.service.grpc.AgentCredentialResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.hivearmor.service.grpc.AgentCredentialResponse();
  }

  public static com.hivearmor.service.grpc.AgentCredentialResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AgentCredentialResponse>
      PARSER = new com.google.protobuf.AbstractParser<AgentCredentialResponse>() {
    @java.lang.Override
    public AgentCredentialResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AgentCredentialResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AgentCredentialResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.hivearmor.service.grpc.AgentCredentialResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

