// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agent.proto
// Protobuf Java Version: 4.29.3

package com.hivearmor.service.grpc;

public interface AgentCredentialRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:agent.AgentCredentialRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 agent_id = 1;</code>
   * @return The agentId.
   */
  int getAgentId();

  /**
   * <code>int64 tenant_id = 2;</code>
   * @return The tenantId.
   */
  long getTenantId();

  /**
   * <code>string actor = 3;</code>
   * @return The actor.
   */
  java.lang.String getActor();
  /**
   * <code>string actor = 3;</code>
   * @return The bytes for actor.
   */
  com.google.protobuf.ByteString
      getActorBytes();

  /**
   * <code>string reason = 4;</code>
   * @return The reason.
   */
  java.lang.String getReason();
  /**
   * <code>string reason = 4;</code>
   * @return The bytes for reason.
   */
  com.google.protobuf.ByteString
      getReasonBytes();
}
