// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agent.proto
// Protobuf Java Version: 4.29.3

package com.hivearmor.service.grpc;

public interface BidirectionalStreamOrBuilder extends
    // @@protoc_insertion_point(interface_extends:agent.BidirectionalStream)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.agent.RemoteCommand command = 1;</code>
   * @return Whether the command field is set.
   */
  boolean hasCommand();
  /**
   * <code>.agent.RemoteCommand command = 1;</code>
   * @return The command.
   */
  com.hivearmor.service.grpc.RemoteCommand getCommand();
  /**
   * <code>.agent.RemoteCommand command = 1;</code>
   */
  com.hivearmor.service.grpc.RemoteCommandOrBuilder getCommandOrBuilder();

  /**
   * <code>.agent.CommandResult result = 2;</code>
   * @return Whether the result field is set.
   */
  boolean hasResult();
  /**
   * <code>.agent.CommandResult result = 2;</code>
   * @return The result.
   */
  com.hivearmor.service.grpc.CommandResult getResult();
  /**
   * <code>.agent.CommandResult result = 2;</code>
   */
  com.hivearmor.service.grpc.CommandResultOrBuilder getResultOrBuilder();

  com.hivearmor.service.grpc.BidirectionalStream.StreamMessageCase getStreamMessageCase();
}
