// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agent.proto
// Protobuf Java Version: 4.29.3

package com.hivearmor.service.grpc;

/**
 * Protobuf type {@code agent.CreateEnrollmentTokenRequest}
 */
public final class CreateEnrollmentTokenRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:agent.CreateEnrollmentTokenRequest)
    CreateEnrollmentTokenRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      CreateEnrollmentTokenRequest.class.getName());
  }
  // Use CreateEnrollmentTokenRequest.newBuilder() to construct.
  private CreateEnrollmentTokenRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private CreateEnrollmentTokenRequest() {
    policyId_ = "";
    platform_ = "";
    createdBy_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.hivearmor.service.grpc.AgentManagerGrpc.internal_static_agent_CreateEnrollmentTokenRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.hivearmor.service.grpc.AgentManagerGrpc.internal_static_agent_CreateEnrollmentTokenRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.hivearmor.service.grpc.CreateEnrollmentTokenRequest.class, com.hivearmor.service.grpc.CreateEnrollmentTokenRequest.Builder.class);
  }

  private int bitField0_;
  public static final int TENANT_ID_FIELD_NUMBER = 1;
  private long tenantId_ = 0L;
  /**
   * <code>int64 tenant_id = 1;</code>
   * @return The tenantId.
   */
  @java.lang.Override
  public long getTenantId() {
    return tenantId_;
  }

  public static final int POLICY_ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object policyId_ = "";
  /**
   * <code>string policy_id = 2;</code>
   * @return The policyId.
   */
  @java.lang.Override
  public java.lang.String getPolicyId() {
    java.lang.Object ref = policyId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      policyId_ = s;
      return s;
    }
  }
  /**
   * <code>string policy_id = 2;</code>
   * @return The bytes for policyId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPolicyIdBytes() {
    java.lang.Object ref = policyId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      policyId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PLATFORM_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object platform_ = "";
  /**
   * <code>string platform = 3;</code>
   * @return The platform.
   */
  @java.lang.Override
  public java.lang.String getPlatform() {
    java.lang.Object ref = platform_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      platform_ = s;
      return s;
    }
  }
  /**
   * <code>string platform = 3;</code>
   * @return The bytes for platform.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPlatformBytes() {
    java.lang.Object ref = platform_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      platform_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EXPIRES_AT_FIELD_NUMBER = 4;
  private com.google.protobuf.Timestamp expiresAt_;
  /**
   * <code>.google.protobuf.Timestamp expires_at = 4;</code>
   * @return Whether the expiresAt field is set.
   */
  @java.lang.Override
  public boolean hasExpiresAt() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.google.protobuf.Timestamp expires_at = 4;</code>
   * @return The expiresAt.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getExpiresAt() {
    return expiresAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : expiresAt_;
  }
  /**
   * <code>.google.protobuf.Timestamp expires_at = 4;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getExpiresAtOrBuilder() {
    return expiresAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : expiresAt_;
  }

  public static final int MAX_USES_FIELD_NUMBER = 5;
  private int maxUses_ = 0;
  /**
   * <code>int32 max_uses = 5;</code>
   * @return The maxUses.
   */
  @java.lang.Override
  public int getMaxUses() {
    return maxUses_;
  }

  public static final int CREATED_BY_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object createdBy_ = "";
  /**
   * <code>string created_by = 6;</code>
   * @return The createdBy.
   */
  @java.lang.Override
  public java.lang.String getCreatedBy() {
    java.lang.Object ref = createdBy_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      createdBy_ = s;
      return s;
    }
  }
  /**
   * <code>string created_by = 6;</code>
   * @return The bytes for createdBy.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCreatedByBytes() {
    java.lang.Object ref = createdBy_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      createdBy_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (tenantId_ != 0L) {
      output.writeInt64(1, tenantId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(policyId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, policyId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(platform_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, platform_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(4, getExpiresAt());
    }
    if (maxUses_ != 0) {
      output.writeInt32(5, maxUses_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(createdBy_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, createdBy_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (tenantId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, tenantId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(policyId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, policyId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(platform_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, platform_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getExpiresAt());
    }
    if (maxUses_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, maxUses_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(createdBy_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(6, createdBy_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.hivearmor.service.grpc.CreateEnrollmentTokenRequest)) {
      return super.equals(obj);
    }
    com.hivearmor.service.grpc.CreateEnrollmentTokenRequest other = (com.hivearmor.service.grpc.CreateEnrollmentTokenRequest) obj;

    if (getTenantId()
        != other.getTenantId()) return false;
    if (!getPolicyId()
        .equals(other.getPolicyId())) return false;
    if (!getPlatform()
        .equals(other.getPlatform())) return false;
    if (hasExpiresAt() != other.hasExpiresAt()) return false;
    if (hasExpiresAt()) {
      if (!getExpiresAt()
          .equals(other.getExpiresAt())) return false;
    }
    if (getMaxUses()
        != other.getMaxUses()) return false;
    if (!getCreatedBy()
        .equals(other.getCreatedBy())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TENANT_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTenantId());
    hash = (37 * hash) + POLICY_ID_FIELD_NUMBER;
    hash = (53 * hash) + getPolicyId().hashCode();
    hash = (37 * hash) + PLATFORM_FIELD_NUMBER;
    hash = (53 * hash) + getPlatform().hashCode();
    if (hasExpiresAt()) {
      hash = (37 * hash) + EXPIRES_AT_FIELD_NUMBER;
      hash = (53 * hash) + getExpiresAt().hashCode();
    }
    hash = (37 * hash) + MAX_USES_FIELD_NUMBER;
    hash = (53 * hash) + getMaxUses();
    hash = (37 * hash) + CREATED_BY_FIELD_NUMBER;
    hash = (53 * hash) + getCreatedBy().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.hivearmor.service.grpc.CreateEnrollmentTokenRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hivearmor.service.grpc.CreateEnrollmentTokenRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hivearmor.service.grpc.CreateEnrollmentTokenRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hivearmor.service.grpc.CreateEnrollmentTokenRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hivearmor.service.grpc.CreateEnrollmentTokenRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hivearmor.service.grpc.CreateEnrollmentTokenRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hivearmor.service.grpc.CreateEnrollmentTokenRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.hivearmor.service.grpc.CreateEnrollmentTokenRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.hivearmor.service.grpc.CreateEnrollmentTokenRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.hivearmor.service.grpc.CreateEnrollmentTokenRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.hivearmor.service.grpc.CreateEnrollmentTokenRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.hivearmor.service.grpc.CreateEnrollmentTokenRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.hivearmor.service.grpc.CreateEnrollmentTokenRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code agent.CreateEnrollmentTokenRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:agent.CreateEnrollmentTokenRequest)
      com.hivearmor.service.grpc.CreateEnrollmentTokenRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hivearmor.service.grpc.AgentManagerGrpc.internal_static_agent_CreateEnrollmentTokenRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hivearmor.service.grpc.AgentManagerGrpc.internal_static_agent_CreateEnrollmentTokenRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hivearmor.service.grpc.CreateEnrollmentTokenRequest.class, com.hivearmor.service.grpc.CreateEnrollmentTokenRequest.Builder.class);
    }

    // Construct using com.hivearmor.service.grpc.CreateEnrollmentTokenRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getExpiresAtFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      tenantId_ = 0L;
      policyId_ = "";
      platform_ = "";
      expiresAt_ = null;
      if (expiresAtBuilder_ != null) {
        expiresAtBuilder_.dispose();
        expiresAtBuilder_ = null;
      }
      maxUses_ = 0;
      createdBy_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.hivearmor.service.grpc.AgentManagerGrpc.internal_static_agent_CreateEnrollmentTokenRequest_descriptor;
    }

    @java.lang.Override
    public com.hivearmor.service.grpc.CreateEnrollmentTokenRequest getDefaultInstanceForType() {
      return com.hivearmor.service.grpc.CreateEnrollmentTokenRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.hivearmor.service.grpc.CreateEnrollmentTokenRequest build() {
      com.hivearmor.service.grpc.CreateEnrollmentTokenRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.hivearmor.service.grpc.CreateEnrollmentTokenRequest buildPartial() {
      com.hivearmor.service.grpc.CreateEnrollmentTokenRequest result = new com.hivearmor.service.grpc.CreateEnrollmentTokenRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.hivearmor.service.grpc.CreateEnrollmentTokenRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.tenantId_ = tenantId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.policyId_ = policyId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.platform_ = platform_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.expiresAt_ = expiresAtBuilder_ == null
            ? expiresAt_
            : expiresAtBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.maxUses_ = maxUses_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.createdBy_ = createdBy_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.hivearmor.service.grpc.CreateEnrollmentTokenRequest) {
        return mergeFrom((com.hivearmor.service.grpc.CreateEnrollmentTokenRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.hivearmor.service.grpc.CreateEnrollmentTokenRequest other) {
      if (other == com.hivearmor.service.grpc.CreateEnrollmentTokenRequest.getDefaultInstance()) return this;
      if (other.getTenantId() != 0L) {
        setTenantId(other.getTenantId());
      }
      if (!other.getPolicyId().isEmpty()) {
        policyId_ = other.policyId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getPlatform().isEmpty()) {
        platform_ = other.platform_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.hasExpiresAt()) {
        mergeExpiresAt(other.getExpiresAt());
      }
      if (other.getMaxUses() != 0) {
        setMaxUses(other.getMaxUses());
      }
      if (!other.getCreatedBy().isEmpty()) {
        createdBy_ = other.createdBy_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              tenantId_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              policyId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              platform_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  getExpiresAtFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 40: {
              maxUses_ = input.readInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 50: {
              createdBy_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long tenantId_ ;
    /**
     * <code>int64 tenant_id = 1;</code>
     * @return The tenantId.
     */
    @java.lang.Override
    public long getTenantId() {
      return tenantId_;
    }
    /**
     * <code>int64 tenant_id = 1;</code>
     * @param value The tenantId to set.
     * @return This builder for chaining.
     */
    public Builder setTenantId(long value) {

      tenantId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int64 tenant_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTenantId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      tenantId_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object policyId_ = "";
    /**
     * <code>string policy_id = 2;</code>
     * @return The policyId.
     */
    public java.lang.String getPolicyId() {
      java.lang.Object ref = policyId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        policyId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string policy_id = 2;</code>
     * @return The bytes for policyId.
     */
    public com.google.protobuf.ByteString
        getPolicyIdBytes() {
      java.lang.Object ref = policyId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        policyId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string policy_id = 2;</code>
     * @param value The policyId to set.
     * @return This builder for chaining.
     */
    public Builder setPolicyId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      policyId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string policy_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPolicyId() {
      policyId_ = getDefaultInstance().getPolicyId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string policy_id = 2;</code>
     * @param value The bytes for policyId to set.
     * @return This builder for chaining.
     */
    public Builder setPolicyIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      policyId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object platform_ = "";
    /**
     * <code>string platform = 3;</code>
     * @return The platform.
     */
    public java.lang.String getPlatform() {
      java.lang.Object ref = platform_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        platform_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string platform = 3;</code>
     * @return The bytes for platform.
     */
    public com.google.protobuf.ByteString
        getPlatformBytes() {
      java.lang.Object ref = platform_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        platform_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string platform = 3;</code>
     * @param value The platform to set.
     * @return This builder for chaining.
     */
    public Builder setPlatform(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      platform_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string platform = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPlatform() {
      platform_ = getDefaultInstance().getPlatform();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string platform = 3;</code>
     * @param value The bytes for platform to set.
     * @return This builder for chaining.
     */
    public Builder setPlatformBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      platform_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp expiresAt_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> expiresAtBuilder_;
    /**
     * <code>.google.protobuf.Timestamp expires_at = 4;</code>
     * @return Whether the expiresAt field is set.
     */
    public boolean hasExpiresAt() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp expires_at = 4;</code>
     * @return The expiresAt.
     */
    public com.google.protobuf.Timestamp getExpiresAt() {
      if (expiresAtBuilder_ == null) {
        return expiresAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : expiresAt_;
      } else {
        return expiresAtBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp expires_at = 4;</code>
     */
    public Builder setExpiresAt(com.google.protobuf.Timestamp value) {
      if (expiresAtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        expiresAt_ = value;
      } else {
        expiresAtBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp expires_at = 4;</code>
     */
    public Builder setExpiresAt(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (expiresAtBuilder_ == null) {
        expiresAt_ = builderForValue.build();
      } else {
        expiresAtBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp expires_at = 4;</code>
     */
    public Builder mergeExpiresAt(com.google.protobuf.Timestamp value) {
      if (expiresAtBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          expiresAt_ != null &&
          expiresAt_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getExpiresAtBuilder().mergeFrom(value);
        } else {
          expiresAt_ = value;
        }
      } else {
        expiresAtBuilder_.mergeFrom(value);
      }
      if (expiresAt_ != null) {
        bitField0_ |= 0x00000008;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp expires_at = 4;</code>
     */
    public Builder clearExpiresAt() {
      bitField0_ = (bitField0_ & ~0x00000008);
      expiresAt_ = null;
      if (expiresAtBuilder_ != null) {
        expiresAtBuilder_.dispose();
        expiresAtBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp expires_at = 4;</code>
     */
    public com.google.protobuf.Timestamp.Builder getExpiresAtBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getExpiresAtFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp expires_at = 4;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getExpiresAtOrBuilder() {
      if (expiresAtBuilder_ != null) {
        return expiresAtBuilder_.getMessageOrBuilder();
      } else {
        return expiresAt_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : expiresAt_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp expires_at = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getExpiresAtFieldBuilder() {
      if (expiresAtBuilder_ == null) {
        expiresAtBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getExpiresAt(),
                getParentForChildren(),
                isClean());
        expiresAt_ = null;
      }
      return expiresAtBuilder_;
    }

    private int maxUses_ ;
    /**
     * <code>int32 max_uses = 5;</code>
     * @return The maxUses.
     */
    @java.lang.Override
    public int getMaxUses() {
      return maxUses_;
    }
    /**
     * <code>int32 max_uses = 5;</code>
     * @param value The maxUses to set.
     * @return This builder for chaining.
     */
    public Builder setMaxUses(int value) {

      maxUses_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>int32 max_uses = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxUses() {
      bitField0_ = (bitField0_ & ~0x00000010);
      maxUses_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object createdBy_ = "";
    /**
     * <code>string created_by = 6;</code>
     * @return The createdBy.
     */
    public java.lang.String getCreatedBy() {
      java.lang.Object ref = createdBy_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        createdBy_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string created_by = 6;</code>
     * @return The bytes for createdBy.
     */
    public com.google.protobuf.ByteString
        getCreatedByBytes() {
      java.lang.Object ref = createdBy_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        createdBy_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string created_by = 6;</code>
     * @param value The createdBy to set.
     * @return This builder for chaining.
     */
    public Builder setCreatedBy(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      createdBy_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>string created_by = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearCreatedBy() {
      createdBy_ = getDefaultInstance().getCreatedBy();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>string created_by = 6;</code>
     * @param value The bytes for createdBy to set.
     * @return This builder for chaining.
     */
    public Builder setCreatedByBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      createdBy_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:agent.CreateEnrollmentTokenRequest)
  }

  // @@protoc_insertion_point(class_scope:agent.CreateEnrollmentTokenRequest)
  private static final com.hivearmor.service.grpc.CreateEnrollmentTokenRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.hivearmor.service.grpc.CreateEnrollmentTokenRequest();
  }

  public static com.hivearmor.service.grpc.CreateEnrollmentTokenRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateEnrollmentTokenRequest>
      PARSER = new com.google.protobuf.AbstractParser<CreateEnrollmentTokenRequest>() {
    @java.lang.Override
    public CreateEnrollmentTokenRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CreateEnrollmentTokenRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateEnrollmentTokenRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.hivearmor.service.grpc.CreateEnrollmentTokenRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

