// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agent.proto
// Protobuf Java Version: 4.29.3

package com.hivearmor.service.grpc;

public interface CreateEnrollmentTokenResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:agent.CreateEnrollmentTokenResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.agent.EnrollmentToken enrollment = 1;</code>
   * @return Whether the enrollment field is set.
   */
  boolean hasEnrollment();
  /**
   * <code>.agent.EnrollmentToken enrollment = 1;</code>
   * @return The enrollment.
   */
  com.hivearmor.service.grpc.EnrollmentToken getEnrollment();
  /**
   * <code>.agent.EnrollmentToken enrollment = 1;</code>
   */
  com.hivearmor.service.grpc.EnrollmentTokenOrBuilder getEnrollmentOrBuilder();

  /**
   * <code>string token = 2;</code>
   * @return The token.
   */
  java.lang.String getToken();
  /**
   * <code>string token = 2;</code>
   * @return The bytes for token.
   */
  com.google.protobuf.ByteString
      getTokenBytes();
}
