// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agent.proto
// Protobuf Java Version: 4.29.3

package com.hivearmor.service.grpc;

public interface ListAgentsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:agent.ListAgentsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .agent.Agent rows = 1;</code>
   */
  java.util.List<com.hivearmor.service.grpc.Agent> 
      getRowsList();
  /**
   * <code>repeated .agent.Agent rows = 1;</code>
   */
  com.hivearmor.service.grpc.Agent getRows(int index);
  /**
   * <code>repeated .agent.Agent rows = 1;</code>
   */
  int getRowsCount();
  /**
   * <code>repeated .agent.Agent rows = 1;</code>
   */
  java.util.List<? extends com.hivearmor.service.grpc.AgentOrBuilder> 
      getRowsOrBuilderList();
  /**
   * <code>repeated .agent.Agent rows = 1;</code>
   */
  com.hivearmor.service.grpc.AgentOrBuilder getRowsOrBuilder(
      int index);

  /**
   * <code>int32 total = 2;</code>
   * @return The total.
   */
  int getTotal();
}
