// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agent.proto
// Protobuf Java Version: 4.29.3

package com.hivearmor.service.grpc;

/**
 * Protobuf type {@code agent.ListConnectorAuthorizationResponse}
 */
public final class ListConnectorAuthorizationResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:agent.ListConnectorAuthorizationResponse)
    ListConnectorAuthorizationResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      ListConnectorAuthorizationResponse.class.getName());
  }
  // Use ListConnectorAuthorizationResponse.newBuilder() to construct.
  private ListConnectorAuthorizationResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ListConnectorAuthorizationResponse() {
    rows_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.hivearmor.service.grpc.AgentManagerGrpc.internal_static_agent_ListConnectorAuthorizationResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.hivearmor.service.grpc.AgentManagerGrpc.internal_static_agent_ListConnectorAuthorizationResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.hivearmor.service.grpc.ListConnectorAuthorizationResponse.class, com.hivearmor.service.grpc.ListConnectorAuthorizationResponse.Builder.class);
  }

  public static final int ROWS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.hivearmor.service.grpc.ConnectorAuthorization> rows_;
  /**
   * <code>repeated .agent.ConnectorAuthorization rows = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.hivearmor.service.grpc.ConnectorAuthorization> getRowsList() {
    return rows_;
  }
  /**
   * <code>repeated .agent.ConnectorAuthorization rows = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.hivearmor.service.grpc.ConnectorAuthorizationOrBuilder> 
      getRowsOrBuilderList() {
    return rows_;
  }
  /**
   * <code>repeated .agent.ConnectorAuthorization rows = 1;</code>
   */
  @java.lang.Override
  public int getRowsCount() {
    return rows_.size();
  }
  /**
   * <code>repeated .agent.ConnectorAuthorization rows = 1;</code>
   */
  @java.lang.Override
  public com.hivearmor.service.grpc.ConnectorAuthorization getRows(int index) {
    return rows_.get(index);
  }
  /**
   * <code>repeated .agent.ConnectorAuthorization rows = 1;</code>
   */
  @java.lang.Override
  public com.hivearmor.service.grpc.ConnectorAuthorizationOrBuilder getRowsOrBuilder(
      int index) {
    return rows_.get(index);
  }

  public static final int TOTAL_FIELD_NUMBER = 2;
  private int total_ = 0;
  /**
   * <code>int32 total = 2;</code>
   * @return The total.
   */
  @java.lang.Override
  public int getTotal() {
    return total_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < rows_.size(); i++) {
      output.writeMessage(1, rows_.get(i));
    }
    if (total_ != 0) {
      output.writeInt32(2, total_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < rows_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, rows_.get(i));
    }
    if (total_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, total_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.hivearmor.service.grpc.ListConnectorAuthorizationResponse)) {
      return super.equals(obj);
    }
    com.hivearmor.service.grpc.ListConnectorAuthorizationResponse other = (com.hivearmor.service.grpc.ListConnectorAuthorizationResponse) obj;

    if (!getRowsList()
        .equals(other.getRowsList())) return false;
    if (getTotal()
        != other.getTotal()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getRowsCount() > 0) {
      hash = (37 * hash) + ROWS_FIELD_NUMBER;
      hash = (53 * hash) + getRowsList().hashCode();
    }
    hash = (37 * hash) + TOTAL_FIELD_NUMBER;
    hash = (53 * hash) + getTotal();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.hivearmor.service.grpc.ListConnectorAuthorizationResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hivearmor.service.grpc.ListConnectorAuthorizationResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hivearmor.service.grpc.ListConnectorAuthorizationResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hivearmor.service.grpc.ListConnectorAuthorizationResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hivearmor.service.grpc.ListConnectorAuthorizationResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hivearmor.service.grpc.ListConnectorAuthorizationResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hivearmor.service.grpc.ListConnectorAuthorizationResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.hivearmor.service.grpc.ListConnectorAuthorizationResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.hivearmor.service.grpc.ListConnectorAuthorizationResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.hivearmor.service.grpc.ListConnectorAuthorizationResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.hivearmor.service.grpc.ListConnectorAuthorizationResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.hivearmor.service.grpc.ListConnectorAuthorizationResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.hivearmor.service.grpc.ListConnectorAuthorizationResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code agent.ListConnectorAuthorizationResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:agent.ListConnectorAuthorizationResponse)
      com.hivearmor.service.grpc.ListConnectorAuthorizationResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hivearmor.service.grpc.AgentManagerGrpc.internal_static_agent_ListConnectorAuthorizationResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hivearmor.service.grpc.AgentManagerGrpc.internal_static_agent_ListConnectorAuthorizationResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hivearmor.service.grpc.ListConnectorAuthorizationResponse.class, com.hivearmor.service.grpc.ListConnectorAuthorizationResponse.Builder.class);
    }

    // Construct using com.hivearmor.service.grpc.ListConnectorAuthorizationResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (rowsBuilder_ == null) {
        rows_ = java.util.Collections.emptyList();
      } else {
        rows_ = null;
        rowsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      total_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.hivearmor.service.grpc.AgentManagerGrpc.internal_static_agent_ListConnectorAuthorizationResponse_descriptor;
    }

    @java.lang.Override
    public com.hivearmor.service.grpc.ListConnectorAuthorizationResponse getDefaultInstanceForType() {
      return com.hivearmor.service.grpc.ListConnectorAuthorizationResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.hivearmor.service.grpc.ListConnectorAuthorizationResponse build() {
      com.hivearmor.service.grpc.ListConnectorAuthorizationResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.hivearmor.service.grpc.ListConnectorAuthorizationResponse buildPartial() {
      com.hivearmor.service.grpc.ListConnectorAuthorizationResponse result = new com.hivearmor.service.grpc.ListConnectorAuthorizationResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.hivearmor.service.grpc.ListConnectorAuthorizationResponse result) {
      if (rowsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          rows_ = java.util.Collections.unmodifiableList(rows_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.rows_ = rows_;
      } else {
        result.rows_ = rowsBuilder_.build();
      }
    }

    private void buildPartial0(com.hivearmor.service.grpc.ListConnectorAuthorizationResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.total_ = total_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.hivearmor.service.grpc.ListConnectorAuthorizationResponse) {
        return mergeFrom((com.hivearmor.service.grpc.ListConnectorAuthorizationResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.hivearmor.service.grpc.ListConnectorAuthorizationResponse other) {
      if (other == com.hivearmor.service.grpc.ListConnectorAuthorizationResponse.getDefaultInstance()) return this;
      if (rowsBuilder_ == null) {
        if (!other.rows_.isEmpty()) {
          if (rows_.isEmpty()) {
            rows_ = other.rows_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureRowsIsMutable();
            rows_.addAll(other.rows_);
          }
          onChanged();
        }
      } else {
        if (!other.rows_.isEmpty()) {
          if (rowsBuilder_.isEmpty()) {
            rowsBuilder_.dispose();
            rowsBuilder_ = null;
            rows_ = other.rows_;
            bitField0_ = (bitField0_ & ~0x00000001);
            rowsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getRowsFieldBuilder() : null;
          } else {
            rowsBuilder_.addAllMessages(other.rows_);
          }
        }
      }
      if (other.getTotal() != 0) {
        setTotal(other.getTotal());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.hivearmor.service.grpc.ConnectorAuthorization m =
                  input.readMessage(
                      com.hivearmor.service.grpc.ConnectorAuthorization.parser(),
                      extensionRegistry);
              if (rowsBuilder_ == null) {
                ensureRowsIsMutable();
                rows_.add(m);
              } else {
                rowsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            case 16: {
              total_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.hivearmor.service.grpc.ConnectorAuthorization> rows_ =
      java.util.Collections.emptyList();
    private void ensureRowsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        rows_ = new java.util.ArrayList<com.hivearmor.service.grpc.ConnectorAuthorization>(rows_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.hivearmor.service.grpc.ConnectorAuthorization, com.hivearmor.service.grpc.ConnectorAuthorization.Builder, com.hivearmor.service.grpc.ConnectorAuthorizationOrBuilder> rowsBuilder_;

    /**
     * <code>repeated .agent.ConnectorAuthorization rows = 1;</code>
     */
    public java.util.List<com.hivearmor.service.grpc.ConnectorAuthorization> getRowsList() {
      if (rowsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(rows_);
      } else {
        return rowsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .agent.ConnectorAuthorization rows = 1;</code>
     */
    public int getRowsCount() {
      if (rowsBuilder_ == null) {
        return rows_.size();
      } else {
        return rowsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .agent.ConnectorAuthorization rows = 1;</code>
     */
    public com.hivearmor.service.grpc.ConnectorAuthorization getRows(int index) {
      if (rowsBuilder_ == null) {
        return rows_.get(index);
      } else {
        return rowsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .agent.ConnectorAuthorization rows = 1;</code>
     */
    public Builder setRows(
        int index, com.hivearmor.service.grpc.ConnectorAuthorization value) {
      if (rowsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRowsIsMutable();
        rows_.set(index, value);
        onChanged();
      } else {
        rowsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .agent.ConnectorAuthorization rows = 1;</code>
     */
    public Builder setRows(
        int index, com.hivearmor.service.grpc.ConnectorAuthorization.Builder builderForValue) {
      if (rowsBuilder_ == null) {
        ensureRowsIsMutable();
        rows_.set(index, builderForValue.build());
        onChanged();
      } else {
        rowsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .agent.ConnectorAuthorization rows = 1;</code>
     */
    public Builder addRows(com.hivearmor.service.grpc.ConnectorAuthorization value) {
      if (rowsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRowsIsMutable();
        rows_.add(value);
        onChanged();
      } else {
        rowsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .agent.ConnectorAuthorization rows = 1;</code>
     */
    public Builder addRows(
        int index, com.hivearmor.service.grpc.ConnectorAuthorization value) {
      if (rowsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRowsIsMutable();
        rows_.add(index, value);
        onChanged();
      } else {
        rowsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .agent.ConnectorAuthorization rows = 1;</code>
     */
    public Builder addRows(
        com.hivearmor.service.grpc.ConnectorAuthorization.Builder builderForValue) {
      if (rowsBuilder_ == null) {
        ensureRowsIsMutable();
        rows_.add(builderForValue.build());
        onChanged();
      } else {
        rowsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .agent.ConnectorAuthorization rows = 1;</code>
     */
    public Builder addRows(
        int index, com.hivearmor.service.grpc.ConnectorAuthorization.Builder builderForValue) {
      if (rowsBuilder_ == null) {
        ensureRowsIsMutable();
        rows_.add(index, builderForValue.build());
        onChanged();
      } else {
        rowsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .agent.ConnectorAuthorization rows = 1;</code>
     */
    public Builder addAllRows(
        java.lang.Iterable<? extends com.hivearmor.service.grpc.ConnectorAuthorization> values) {
      if (rowsBuilder_ == null) {
        ensureRowsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, rows_);
        onChanged();
      } else {
        rowsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .agent.ConnectorAuthorization rows = 1;</code>
     */
    public Builder clearRows() {
      if (rowsBuilder_ == null) {
        rows_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        rowsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .agent.ConnectorAuthorization rows = 1;</code>
     */
    public Builder removeRows(int index) {
      if (rowsBuilder_ == null) {
        ensureRowsIsMutable();
        rows_.remove(index);
        onChanged();
      } else {
        rowsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .agent.ConnectorAuthorization rows = 1;</code>
     */
    public com.hivearmor.service.grpc.ConnectorAuthorization.Builder getRowsBuilder(
        int index) {
      return getRowsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .agent.ConnectorAuthorization rows = 1;</code>
     */
    public com.hivearmor.service.grpc.ConnectorAuthorizationOrBuilder getRowsOrBuilder(
        int index) {
      if (rowsBuilder_ == null) {
        return rows_.get(index);  } else {
        return rowsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .agent.ConnectorAuthorization rows = 1;</code>
     */
    public java.util.List<? extends com.hivearmor.service.grpc.ConnectorAuthorizationOrBuilder> 
         getRowsOrBuilderList() {
      if (rowsBuilder_ != null) {
        return rowsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(rows_);
      }
    }
    /**
     * <code>repeated .agent.ConnectorAuthorization rows = 1;</code>
     */
    public com.hivearmor.service.grpc.ConnectorAuthorization.Builder addRowsBuilder() {
      return getRowsFieldBuilder().addBuilder(
          com.hivearmor.service.grpc.ConnectorAuthorization.getDefaultInstance());
    }
    /**
     * <code>repeated .agent.ConnectorAuthorization rows = 1;</code>
     */
    public com.hivearmor.service.grpc.ConnectorAuthorization.Builder addRowsBuilder(
        int index) {
      return getRowsFieldBuilder().addBuilder(
          index, com.hivearmor.service.grpc.ConnectorAuthorization.getDefaultInstance());
    }
    /**
     * <code>repeated .agent.ConnectorAuthorization rows = 1;</code>
     */
    public java.util.List<com.hivearmor.service.grpc.ConnectorAuthorization.Builder> 
         getRowsBuilderList() {
      return getRowsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.hivearmor.service.grpc.ConnectorAuthorization, com.hivearmor.service.grpc.ConnectorAuthorization.Builder, com.hivearmor.service.grpc.ConnectorAuthorizationOrBuilder> 
        getRowsFieldBuilder() {
      if (rowsBuilder_ == null) {
        rowsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.hivearmor.service.grpc.ConnectorAuthorization, com.hivearmor.service.grpc.ConnectorAuthorization.Builder, com.hivearmor.service.grpc.ConnectorAuthorizationOrBuilder>(
                rows_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        rows_ = null;
      }
      return rowsBuilder_;
    }

    private int total_ ;
    /**
     * <code>int32 total = 2;</code>
     * @return The total.
     */
    @java.lang.Override
    public int getTotal() {
      return total_;
    }
    /**
     * <code>int32 total = 2;</code>
     * @param value The total to set.
     * @return This builder for chaining.
     */
    public Builder setTotal(int value) {

      total_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 total = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotal() {
      bitField0_ = (bitField0_ & ~0x00000002);
      total_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:agent.ListConnectorAuthorizationResponse)
  }

  // @@protoc_insertion_point(class_scope:agent.ListConnectorAuthorizationResponse)
  private static final com.hivearmor.service.grpc.ListConnectorAuthorizationResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.hivearmor.service.grpc.ListConnectorAuthorizationResponse();
  }

  public static com.hivearmor.service.grpc.ListConnectorAuthorizationResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListConnectorAuthorizationResponse>
      PARSER = new com.google.protobuf.AbstractParser<ListConnectorAuthorizationResponse>() {
    @java.lang.Override
    public ListConnectorAuthorizationResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ListConnectorAuthorizationResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListConnectorAuthorizationResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.hivearmor.service.grpc.ListConnectorAuthorizationResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

