// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agent.proto
// Protobuf Java Version: 4.29.3

package com.hivearmor.service.grpc;

public interface ListEnrollmentAuditEventsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:agent.ListEnrollmentAuditEventsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .agent.EnrollmentAuditEvent rows = 1;</code>
   */
  java.util.List<com.hivearmor.service.grpc.EnrollmentAuditEvent> 
      getRowsList();
  /**
   * <code>repeated .agent.EnrollmentAuditEvent rows = 1;</code>
   */
  com.hivearmor.service.grpc.EnrollmentAuditEvent getRows(int index);
  /**
   * <code>repeated .agent.EnrollmentAuditEvent rows = 1;</code>
   */
  int getRowsCount();
  /**
   * <code>repeated .agent.EnrollmentAuditEvent rows = 1;</code>
   */
  java.util.List<? extends com.hivearmor.service.grpc.EnrollmentAuditEventOrBuilder> 
      getRowsOrBuilderList();
  /**
   * <code>repeated .agent.EnrollmentAuditEvent rows = 1;</code>
   */
  com.hivearmor.service.grpc.EnrollmentAuditEventOrBuilder getRowsOrBuilder(
      int index);

  /**
   * <code>int64 total = 2;</code>
   * @return The total.
   */
  long getTotal();
}
