// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agent.proto
// Protobuf Java Version: 4.29.3

package com.hivearmor.service.grpc;

public interface ListConnectorAuthorizationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:agent.ListConnectorAuthorizationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.agent.ConnectorType connector_type = 1;</code>
   * @return The enum numeric value on the wire for connectorType.
   */
  int getConnectorTypeValue();
  /**
   * <code>.agent.ConnectorType connector_type = 1;</code>
   * @return The connectorType.
   */
  com.hivearmor.service.grpc.ConnectorType getConnectorType();

  /**
   * <code>int32 page_number = 2;</code>
   * @return The pageNumber.
   */
  int getPageNumber();

  /**
   * <code>int32 page_size = 3;</code>
   * @return The pageSize.
   */
  int getPageSize();
}
