// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agent.proto
// Protobuf Java Version: 4.29.3

package com.hivearmor.service.grpc;

/**
 * Protobuf type {@code agent.ListEnrollmentAuditEventsRequest}
 */
public final class ListEnrollmentAuditEventsRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:agent.ListEnrollmentAuditEventsRequest)
    ListEnrollmentAuditEventsRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      ListEnrollmentAuditEventsRequest.class.getName());
  }
  // Use ListEnrollmentAuditEventsRequest.newBuilder() to construct.
  private ListEnrollmentAuditEventsRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ListEnrollmentAuditEventsRequest() {
    tokenId_ = "";
    agentUuid_ = "";
    eventType_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.hivearmor.service.grpc.AgentManagerGrpc.internal_static_agent_ListEnrollmentAuditEventsRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.hivearmor.service.grpc.AgentManagerGrpc.internal_static_agent_ListEnrollmentAuditEventsRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.hivearmor.service.grpc.ListEnrollmentAuditEventsRequest.class, com.hivearmor.service.grpc.ListEnrollmentAuditEventsRequest.Builder.class);
  }

  public static final int TENANT_ID_FIELD_NUMBER = 1;
  private long tenantId_ = 0L;
  /**
   * <code>int64 tenant_id = 1;</code>
   * @return The tenantId.
   */
  @java.lang.Override
  public long getTenantId() {
    return tenantId_;
  }

  public static final int PAGE_NUMBER_FIELD_NUMBER = 2;
  private int pageNumber_ = 0;
  /**
   * <code>int32 page_number = 2;</code>
   * @return The pageNumber.
   */
  @java.lang.Override
  public int getPageNumber() {
    return pageNumber_;
  }

  public static final int PAGE_SIZE_FIELD_NUMBER = 3;
  private int pageSize_ = 0;
  /**
   * <code>int32 page_size = 3;</code>
   * @return The pageSize.
   */
  @java.lang.Override
  public int getPageSize() {
    return pageSize_;
  }

  public static final int TOKEN_ID_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object tokenId_ = "";
  /**
   * <code>string token_id = 4;</code>
   * @return The tokenId.
   */
  @java.lang.Override
  public java.lang.String getTokenId() {
    java.lang.Object ref = tokenId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tokenId_ = s;
      return s;
    }
  }
  /**
   * <code>string token_id = 4;</code>
   * @return The bytes for tokenId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTokenIdBytes() {
    java.lang.Object ref = tokenId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tokenId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AGENT_UUID_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object agentUuid_ = "";
  /**
   * <code>string agent_uuid = 5;</code>
   * @return The agentUuid.
   */
  @java.lang.Override
  public java.lang.String getAgentUuid() {
    java.lang.Object ref = agentUuid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      agentUuid_ = s;
      return s;
    }
  }
  /**
   * <code>string agent_uuid = 5;</code>
   * @return The bytes for agentUuid.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAgentUuidBytes() {
    java.lang.Object ref = agentUuid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      agentUuid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EVENT_TYPE_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object eventType_ = "";
  /**
   * <code>string event_type = 6;</code>
   * @return The eventType.
   */
  @java.lang.Override
  public java.lang.String getEventType() {
    java.lang.Object ref = eventType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      eventType_ = s;
      return s;
    }
  }
  /**
   * <code>string event_type = 6;</code>
   * @return The bytes for eventType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEventTypeBytes() {
    java.lang.Object ref = eventType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      eventType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (tenantId_ != 0L) {
      output.writeInt64(1, tenantId_);
    }
    if (pageNumber_ != 0) {
      output.writeInt32(2, pageNumber_);
    }
    if (pageSize_ != 0) {
      output.writeInt32(3, pageSize_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(tokenId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, tokenId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(agentUuid_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, agentUuid_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(eventType_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, eventType_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (tenantId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, tenantId_);
    }
    if (pageNumber_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, pageNumber_);
    }
    if (pageSize_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, pageSize_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(tokenId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, tokenId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(agentUuid_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, agentUuid_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(eventType_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(6, eventType_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.hivearmor.service.grpc.ListEnrollmentAuditEventsRequest)) {
      return super.equals(obj);
    }
    com.hivearmor.service.grpc.ListEnrollmentAuditEventsRequest other = (com.hivearmor.service.grpc.ListEnrollmentAuditEventsRequest) obj;

    if (getTenantId()
        != other.getTenantId()) return false;
    if (getPageNumber()
        != other.getPageNumber()) return false;
    if (getPageSize()
        != other.getPageSize()) return false;
    if (!getTokenId()
        .equals(other.getTokenId())) return false;
    if (!getAgentUuid()
        .equals(other.getAgentUuid())) return false;
    if (!getEventType()
        .equals(other.getEventType())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TENANT_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTenantId());
    hash = (37 * hash) + PAGE_NUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getPageNumber();
    hash = (37 * hash) + PAGE_SIZE_FIELD_NUMBER;
    hash = (53 * hash) + getPageSize();
    hash = (37 * hash) + TOKEN_ID_FIELD_NUMBER;
    hash = (53 * hash) + getTokenId().hashCode();
    hash = (37 * hash) + AGENT_UUID_FIELD_NUMBER;
    hash = (53 * hash) + getAgentUuid().hashCode();
    hash = (37 * hash) + EVENT_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getEventType().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.hivearmor.service.grpc.ListEnrollmentAuditEventsRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hivearmor.service.grpc.ListEnrollmentAuditEventsRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hivearmor.service.grpc.ListEnrollmentAuditEventsRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hivearmor.service.grpc.ListEnrollmentAuditEventsRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hivearmor.service.grpc.ListEnrollmentAuditEventsRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hivearmor.service.grpc.ListEnrollmentAuditEventsRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hivearmor.service.grpc.ListEnrollmentAuditEventsRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.hivearmor.service.grpc.ListEnrollmentAuditEventsRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.hivearmor.service.grpc.ListEnrollmentAuditEventsRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.hivearmor.service.grpc.ListEnrollmentAuditEventsRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.hivearmor.service.grpc.ListEnrollmentAuditEventsRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.hivearmor.service.grpc.ListEnrollmentAuditEventsRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.hivearmor.service.grpc.ListEnrollmentAuditEventsRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code agent.ListEnrollmentAuditEventsRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:agent.ListEnrollmentAuditEventsRequest)
      com.hivearmor.service.grpc.ListEnrollmentAuditEventsRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hivearmor.service.grpc.AgentManagerGrpc.internal_static_agent_ListEnrollmentAuditEventsRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hivearmor.service.grpc.AgentManagerGrpc.internal_static_agent_ListEnrollmentAuditEventsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hivearmor.service.grpc.ListEnrollmentAuditEventsRequest.class, com.hivearmor.service.grpc.ListEnrollmentAuditEventsRequest.Builder.class);
    }

    // Construct using com.hivearmor.service.grpc.ListEnrollmentAuditEventsRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      tenantId_ = 0L;
      pageNumber_ = 0;
      pageSize_ = 0;
      tokenId_ = "";
      agentUuid_ = "";
      eventType_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.hivearmor.service.grpc.AgentManagerGrpc.internal_static_agent_ListEnrollmentAuditEventsRequest_descriptor;
    }

    @java.lang.Override
    public com.hivearmor.service.grpc.ListEnrollmentAuditEventsRequest getDefaultInstanceForType() {
      return com.hivearmor.service.grpc.ListEnrollmentAuditEventsRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.hivearmor.service.grpc.ListEnrollmentAuditEventsRequest build() {
      com.hivearmor.service.grpc.ListEnrollmentAuditEventsRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.hivearmor.service.grpc.ListEnrollmentAuditEventsRequest buildPartial() {
      com.hivearmor.service.grpc.ListEnrollmentAuditEventsRequest result = new com.hivearmor.service.grpc.ListEnrollmentAuditEventsRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.hivearmor.service.grpc.ListEnrollmentAuditEventsRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.tenantId_ = tenantId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.pageNumber_ = pageNumber_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.pageSize_ = pageSize_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.tokenId_ = tokenId_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.agentUuid_ = agentUuid_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.eventType_ = eventType_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.hivearmor.service.grpc.ListEnrollmentAuditEventsRequest) {
        return mergeFrom((com.hivearmor.service.grpc.ListEnrollmentAuditEventsRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.hivearmor.service.grpc.ListEnrollmentAuditEventsRequest other) {
      if (other == com.hivearmor.service.grpc.ListEnrollmentAuditEventsRequest.getDefaultInstance()) return this;
      if (other.getTenantId() != 0L) {
        setTenantId(other.getTenantId());
      }
      if (other.getPageNumber() != 0) {
        setPageNumber(other.getPageNumber());
      }
      if (other.getPageSize() != 0) {
        setPageSize(other.getPageSize());
      }
      if (!other.getTokenId().isEmpty()) {
        tokenId_ = other.tokenId_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getAgentUuid().isEmpty()) {
        agentUuid_ = other.agentUuid_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.getEventType().isEmpty()) {
        eventType_ = other.eventType_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              tenantId_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              pageNumber_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              pageSize_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              tokenId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              agentUuid_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              eventType_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long tenantId_ ;
    /**
     * <code>int64 tenant_id = 1;</code>
     * @return The tenantId.
     */
    @java.lang.Override
    public long getTenantId() {
      return tenantId_;
    }
    /**
     * <code>int64 tenant_id = 1;</code>
     * @param value The tenantId to set.
     * @return This builder for chaining.
     */
    public Builder setTenantId(long value) {

      tenantId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int64 tenant_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTenantId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      tenantId_ = 0L;
      onChanged();
      return this;
    }

    private int pageNumber_ ;
    /**
     * <code>int32 page_number = 2;</code>
     * @return The pageNumber.
     */
    @java.lang.Override
    public int getPageNumber() {
      return pageNumber_;
    }
    /**
     * <code>int32 page_number = 2;</code>
     * @param value The pageNumber to set.
     * @return This builder for chaining.
     */
    public Builder setPageNumber(int value) {

      pageNumber_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 page_number = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPageNumber() {
      bitField0_ = (bitField0_ & ~0x00000002);
      pageNumber_ = 0;
      onChanged();
      return this;
    }

    private int pageSize_ ;
    /**
     * <code>int32 page_size = 3;</code>
     * @return The pageSize.
     */
    @java.lang.Override
    public int getPageSize() {
      return pageSize_;
    }
    /**
     * <code>int32 page_size = 3;</code>
     * @param value The pageSize to set.
     * @return This builder for chaining.
     */
    public Builder setPageSize(int value) {

      pageSize_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 page_size = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPageSize() {
      bitField0_ = (bitField0_ & ~0x00000004);
      pageSize_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object tokenId_ = "";
    /**
     * <code>string token_id = 4;</code>
     * @return The tokenId.
     */
    public java.lang.String getTokenId() {
      java.lang.Object ref = tokenId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tokenId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string token_id = 4;</code>
     * @return The bytes for tokenId.
     */
    public com.google.protobuf.ByteString
        getTokenIdBytes() {
      java.lang.Object ref = tokenId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tokenId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string token_id = 4;</code>
     * @param value The tokenId to set.
     * @return This builder for chaining.
     */
    public Builder setTokenId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      tokenId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string token_id = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTokenId() {
      tokenId_ = getDefaultInstance().getTokenId();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string token_id = 4;</code>
     * @param value The bytes for tokenId to set.
     * @return This builder for chaining.
     */
    public Builder setTokenIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      tokenId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object agentUuid_ = "";
    /**
     * <code>string agent_uuid = 5;</code>
     * @return The agentUuid.
     */
    public java.lang.String getAgentUuid() {
      java.lang.Object ref = agentUuid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        agentUuid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string agent_uuid = 5;</code>
     * @return The bytes for agentUuid.
     */
    public com.google.protobuf.ByteString
        getAgentUuidBytes() {
      java.lang.Object ref = agentUuid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        agentUuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string agent_uuid = 5;</code>
     * @param value The agentUuid to set.
     * @return This builder for chaining.
     */
    public Builder setAgentUuid(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      agentUuid_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string agent_uuid = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearAgentUuid() {
      agentUuid_ = getDefaultInstance().getAgentUuid();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string agent_uuid = 5;</code>
     * @param value The bytes for agentUuid to set.
     * @return This builder for chaining.
     */
    public Builder setAgentUuidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      agentUuid_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.lang.Object eventType_ = "";
    /**
     * <code>string event_type = 6;</code>
     * @return The eventType.
     */
    public java.lang.String getEventType() {
      java.lang.Object ref = eventType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        eventType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string event_type = 6;</code>
     * @return The bytes for eventType.
     */
    public com.google.protobuf.ByteString
        getEventTypeBytes() {
      java.lang.Object ref = eventType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        eventType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string event_type = 6;</code>
     * @param value The eventType to set.
     * @return This builder for chaining.
     */
    public Builder setEventType(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      eventType_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>string event_type = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearEventType() {
      eventType_ = getDefaultInstance().getEventType();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>string event_type = 6;</code>
     * @param value The bytes for eventType to set.
     * @return This builder for chaining.
     */
    public Builder setEventTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      eventType_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:agent.ListEnrollmentAuditEventsRequest)
  }

  // @@protoc_insertion_point(class_scope:agent.ListEnrollmentAuditEventsRequest)
  private static final com.hivearmor.service.grpc.ListEnrollmentAuditEventsRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.hivearmor.service.grpc.ListEnrollmentAuditEventsRequest();
  }

  public static com.hivearmor.service.grpc.ListEnrollmentAuditEventsRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListEnrollmentAuditEventsRequest>
      PARSER = new com.google.protobuf.AbstractParser<ListEnrollmentAuditEventsRequest>() {
    @java.lang.Override
    public ListEnrollmentAuditEventsRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ListEnrollmentAuditEventsRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListEnrollmentAuditEventsRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.hivearmor.service.grpc.ListEnrollmentAuditEventsRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

