// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agent.proto
// Protobuf Java Version: 4.29.3

package com.hivearmor.service.grpc;

public interface RevokeEnrollmentTokenRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:agent.RevokeEnrollmentTokenRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>int64 tenant_id = 2;</code>
   * @return The tenantId.
   */
  long getTenantId();

  /**
   * <code>string revoked_by = 3;</code>
   * @return The revokedBy.
   */
  java.lang.String getRevokedBy();
  /**
   * <code>string revoked_by = 3;</code>
   * @return The bytes for revokedBy.
   */
  com.google.protobuf.ByteString
      getRevokedByBytes();

  /**
   * <code>string reason = 4;</code>
   * @return The reason.
   */
  java.lang.String getReason();
  /**
   * <code>string reason = 4;</code>
   * @return The bytes for reason.
   */
  com.google.protobuf.ByteString
      getReasonBytes();

  /**
   * <code>uint64 expected_version = 5;</code>
   * @return The expectedVersion.
   */
  long getExpectedVersion();
}
