// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agent.proto
// Protobuf Java Version: 4.29.3

package com.hivearmor.service.grpc;

public interface VerifyConnectorIdentityRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:agent.VerifyConnectorIdentityRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 connector_id = 1;</code>
   * @return The connectorId.
   */
  int getConnectorId();

  /**
   * <code>string presented_key = 2;</code>
   * @return The presentedKey.
   */
  java.lang.String getPresentedKey();
  /**
   * <code>string presented_key = 2;</code>
   * @return The bytes for presentedKey.
   */
  com.google.protobuf.ByteString
      getPresentedKeyBytes();

  /**
   * <code>.agent.ConnectorType connector_type = 3;</code>
   * @return The enum numeric value on the wire for connectorType.
   */
  int getConnectorTypeValue();
  /**
   * <code>.agent.ConnectorType connector_type = 3;</code>
   * @return The connectorType.
   */
  com.hivearmor.service.grpc.ConnectorType getConnectorType();
}
