// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agent.proto
// Protobuf Java Version: 4.29.3

package com.hivearmor.service.grpc;

/**
 * Protobuf type {@code agent.VerifyConnectorIdentityResponse}
 */
public final class VerifyConnectorIdentityResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:agent.VerifyConnectorIdentityResponse)
    VerifyConnectorIdentityResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      VerifyConnectorIdentityResponse.class.getName());
  }
  // Use VerifyConnectorIdentityResponse.newBuilder() to construct.
  private VerifyConnectorIdentityResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private VerifyConnectorIdentityResponse() {
    uuid_ = "";
    connectorType_ = 0;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.hivearmor.service.grpc.AgentManagerGrpc.internal_static_agent_VerifyConnectorIdentityResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.hivearmor.service.grpc.AgentManagerGrpc.internal_static_agent_VerifyConnectorIdentityResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.hivearmor.service.grpc.VerifyConnectorIdentityResponse.class, com.hivearmor.service.grpc.VerifyConnectorIdentityResponse.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private int id_ = 0;
  /**
   * <code>uint32 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public int getId() {
    return id_;
  }

  public static final int UUID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object uuid_ = "";
  /**
   * <code>string uuid = 2;</code>
   * @return The uuid.
   */
  @java.lang.Override
  public java.lang.String getUuid() {
    java.lang.Object ref = uuid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      uuid_ = s;
      return s;
    }
  }
  /**
   * <code>string uuid = 2;</code>
   * @return The bytes for uuid.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUuidBytes() {
    java.lang.Object ref = uuid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      uuid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TENANT_ID_FIELD_NUMBER = 3;
  private long tenantId_ = 0L;
  /**
   * <code>int64 tenant_id = 3;</code>
   * @return The tenantId.
   */
  @java.lang.Override
  public long getTenantId() {
    return tenantId_;
  }

  public static final int CREDENTIAL_VERSION_FIELD_NUMBER = 4;
  private int credentialVersion_ = 0;
  /**
   * <code>uint32 credential_version = 4;</code>
   * @return The credentialVersion.
   */
  @java.lang.Override
  public int getCredentialVersion() {
    return credentialVersion_;
  }

  public static final int REVOKED_FIELD_NUMBER = 5;
  private boolean revoked_ = false;
  /**
   * <code>bool revoked = 5;</code>
   * @return The revoked.
   */
  @java.lang.Override
  public boolean getRevoked() {
    return revoked_;
  }

  public static final int CONNECTOR_TYPE_FIELD_NUMBER = 6;
  private int connectorType_ = 0;
  /**
   * <code>.agent.ConnectorType connector_type = 6;</code>
   * @return The enum numeric value on the wire for connectorType.
   */
  @java.lang.Override public int getConnectorTypeValue() {
    return connectorType_;
  }
  /**
   * <code>.agent.ConnectorType connector_type = 6;</code>
   * @return The connectorType.
   */
  @java.lang.Override public com.hivearmor.service.grpc.ConnectorType getConnectorType() {
    com.hivearmor.service.grpc.ConnectorType result = com.hivearmor.service.grpc.ConnectorType.forNumber(connectorType_);
    return result == null ? com.hivearmor.service.grpc.ConnectorType.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0) {
      output.writeUInt32(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(uuid_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, uuid_);
    }
    if (tenantId_ != 0L) {
      output.writeInt64(3, tenantId_);
    }
    if (credentialVersion_ != 0) {
      output.writeUInt32(4, credentialVersion_);
    }
    if (revoked_ != false) {
      output.writeBool(5, revoked_);
    }
    if (connectorType_ != com.hivearmor.service.grpc.ConnectorType.AGENT.getNumber()) {
      output.writeEnum(6, connectorType_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(uuid_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, uuid_);
    }
    if (tenantId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, tenantId_);
    }
    if (credentialVersion_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(4, credentialVersion_);
    }
    if (revoked_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, revoked_);
    }
    if (connectorType_ != com.hivearmor.service.grpc.ConnectorType.AGENT.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(6, connectorType_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.hivearmor.service.grpc.VerifyConnectorIdentityResponse)) {
      return super.equals(obj);
    }
    com.hivearmor.service.grpc.VerifyConnectorIdentityResponse other = (com.hivearmor.service.grpc.VerifyConnectorIdentityResponse) obj;

    if (getId()
        != other.getId()) return false;
    if (!getUuid()
        .equals(other.getUuid())) return false;
    if (getTenantId()
        != other.getTenantId()) return false;
    if (getCredentialVersion()
        != other.getCredentialVersion()) return false;
    if (getRevoked()
        != other.getRevoked()) return false;
    if (connectorType_ != other.connectorType_) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (37 * hash) + UUID_FIELD_NUMBER;
    hash = (53 * hash) + getUuid().hashCode();
    hash = (37 * hash) + TENANT_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTenantId());
    hash = (37 * hash) + CREDENTIAL_VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getCredentialVersion();
    hash = (37 * hash) + REVOKED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getRevoked());
    hash = (37 * hash) + CONNECTOR_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + connectorType_;
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.hivearmor.service.grpc.VerifyConnectorIdentityResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hivearmor.service.grpc.VerifyConnectorIdentityResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hivearmor.service.grpc.VerifyConnectorIdentityResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hivearmor.service.grpc.VerifyConnectorIdentityResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hivearmor.service.grpc.VerifyConnectorIdentityResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hivearmor.service.grpc.VerifyConnectorIdentityResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hivearmor.service.grpc.VerifyConnectorIdentityResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.hivearmor.service.grpc.VerifyConnectorIdentityResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.hivearmor.service.grpc.VerifyConnectorIdentityResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.hivearmor.service.grpc.VerifyConnectorIdentityResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.hivearmor.service.grpc.VerifyConnectorIdentityResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.hivearmor.service.grpc.VerifyConnectorIdentityResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.hivearmor.service.grpc.VerifyConnectorIdentityResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code agent.VerifyConnectorIdentityResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:agent.VerifyConnectorIdentityResponse)
      com.hivearmor.service.grpc.VerifyConnectorIdentityResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hivearmor.service.grpc.AgentManagerGrpc.internal_static_agent_VerifyConnectorIdentityResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hivearmor.service.grpc.AgentManagerGrpc.internal_static_agent_VerifyConnectorIdentityResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hivearmor.service.grpc.VerifyConnectorIdentityResponse.class, com.hivearmor.service.grpc.VerifyConnectorIdentityResponse.Builder.class);
    }

    // Construct using com.hivearmor.service.grpc.VerifyConnectorIdentityResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = 0;
      uuid_ = "";
      tenantId_ = 0L;
      credentialVersion_ = 0;
      revoked_ = false;
      connectorType_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.hivearmor.service.grpc.AgentManagerGrpc.internal_static_agent_VerifyConnectorIdentityResponse_descriptor;
    }

    @java.lang.Override
    public com.hivearmor.service.grpc.VerifyConnectorIdentityResponse getDefaultInstanceForType() {
      return com.hivearmor.service.grpc.VerifyConnectorIdentityResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.hivearmor.service.grpc.VerifyConnectorIdentityResponse build() {
      com.hivearmor.service.grpc.VerifyConnectorIdentityResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.hivearmor.service.grpc.VerifyConnectorIdentityResponse buildPartial() {
      com.hivearmor.service.grpc.VerifyConnectorIdentityResponse result = new com.hivearmor.service.grpc.VerifyConnectorIdentityResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.hivearmor.service.grpc.VerifyConnectorIdentityResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.uuid_ = uuid_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.tenantId_ = tenantId_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.credentialVersion_ = credentialVersion_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.revoked_ = revoked_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.connectorType_ = connectorType_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.hivearmor.service.grpc.VerifyConnectorIdentityResponse) {
        return mergeFrom((com.hivearmor.service.grpc.VerifyConnectorIdentityResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.hivearmor.service.grpc.VerifyConnectorIdentityResponse other) {
      if (other == com.hivearmor.service.grpc.VerifyConnectorIdentityResponse.getDefaultInstance()) return this;
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (!other.getUuid().isEmpty()) {
        uuid_ = other.uuid_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getTenantId() != 0L) {
        setTenantId(other.getTenantId());
      }
      if (other.getCredentialVersion() != 0) {
        setCredentialVersion(other.getCredentialVersion());
      }
      if (other.getRevoked() != false) {
        setRevoked(other.getRevoked());
      }
      if (other.connectorType_ != 0) {
        setConnectorTypeValue(other.getConnectorTypeValue());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              id_ = input.readUInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              uuid_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              tenantId_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              credentialVersion_ = input.readUInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              revoked_ = input.readBool();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              connectorType_ = input.readEnum();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int id_ ;
    /**
     * <code>uint32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }
    /**
     * <code>uint32 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(int value) {

      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object uuid_ = "";
    /**
     * <code>string uuid = 2;</code>
     * @return The uuid.
     */
    public java.lang.String getUuid() {
      java.lang.Object ref = uuid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uuid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string uuid = 2;</code>
     * @return The bytes for uuid.
     */
    public com.google.protobuf.ByteString
        getUuidBytes() {
      java.lang.Object ref = uuid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string uuid = 2;</code>
     * @param value The uuid to set.
     * @return This builder for chaining.
     */
    public Builder setUuid(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      uuid_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string uuid = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearUuid() {
      uuid_ = getDefaultInstance().getUuid();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string uuid = 2;</code>
     * @param value The bytes for uuid to set.
     * @return This builder for chaining.
     */
    public Builder setUuidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      uuid_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private long tenantId_ ;
    /**
     * <code>int64 tenant_id = 3;</code>
     * @return The tenantId.
     */
    @java.lang.Override
    public long getTenantId() {
      return tenantId_;
    }
    /**
     * <code>int64 tenant_id = 3;</code>
     * @param value The tenantId to set.
     * @return This builder for chaining.
     */
    public Builder setTenantId(long value) {

      tenantId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int64 tenant_id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTenantId() {
      bitField0_ = (bitField0_ & ~0x00000004);
      tenantId_ = 0L;
      onChanged();
      return this;
    }

    private int credentialVersion_ ;
    /**
     * <code>uint32 credential_version = 4;</code>
     * @return The credentialVersion.
     */
    @java.lang.Override
    public int getCredentialVersion() {
      return credentialVersion_;
    }
    /**
     * <code>uint32 credential_version = 4;</code>
     * @param value The credentialVersion to set.
     * @return This builder for chaining.
     */
    public Builder setCredentialVersion(int value) {

      credentialVersion_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 credential_version = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearCredentialVersion() {
      bitField0_ = (bitField0_ & ~0x00000008);
      credentialVersion_ = 0;
      onChanged();
      return this;
    }

    private boolean revoked_ ;
    /**
     * <code>bool revoked = 5;</code>
     * @return The revoked.
     */
    @java.lang.Override
    public boolean getRevoked() {
      return revoked_;
    }
    /**
     * <code>bool revoked = 5;</code>
     * @param value The revoked to set.
     * @return This builder for chaining.
     */
    public Builder setRevoked(boolean value) {

      revoked_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>bool revoked = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearRevoked() {
      bitField0_ = (bitField0_ & ~0x00000010);
      revoked_ = false;
      onChanged();
      return this;
    }

    private int connectorType_ = 0;
    /**
     * <code>.agent.ConnectorType connector_type = 6;</code>
     * @return The enum numeric value on the wire for connectorType.
     */
    @java.lang.Override public int getConnectorTypeValue() {
      return connectorType_;
    }
    /**
     * <code>.agent.ConnectorType connector_type = 6;</code>
     * @param value The enum numeric value on the wire for connectorType to set.
     * @return This builder for chaining.
     */
    public Builder setConnectorTypeValue(int value) {
      connectorType_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.agent.ConnectorType connector_type = 6;</code>
     * @return The connectorType.
     */
    @java.lang.Override
    public com.hivearmor.service.grpc.ConnectorType getConnectorType() {
      com.hivearmor.service.grpc.ConnectorType result = com.hivearmor.service.grpc.ConnectorType.forNumber(connectorType_);
      return result == null ? com.hivearmor.service.grpc.ConnectorType.UNRECOGNIZED : result;
    }
    /**
     * <code>.agent.ConnectorType connector_type = 6;</code>
     * @param value The connectorType to set.
     * @return This builder for chaining.
     */
    public Builder setConnectorType(com.hivearmor.service.grpc.ConnectorType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000020;
      connectorType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.agent.ConnectorType connector_type = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearConnectorType() {
      bitField0_ = (bitField0_ & ~0x00000020);
      connectorType_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:agent.VerifyConnectorIdentityResponse)
  }

  // @@protoc_insertion_point(class_scope:agent.VerifyConnectorIdentityResponse)
  private static final com.hivearmor.service.grpc.VerifyConnectorIdentityResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.hivearmor.service.grpc.VerifyConnectorIdentityResponse();
  }

  public static com.hivearmor.service.grpc.VerifyConnectorIdentityResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<VerifyConnectorIdentityResponse>
      PARSER = new com.google.protobuf.AbstractParser<VerifyConnectorIdentityResponse>() {
    @java.lang.Override
    public VerifyConnectorIdentityResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<VerifyConnectorIdentityResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<VerifyConnectorIdentityResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.hivearmor.service.grpc.VerifyConnectorIdentityResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

