import { useEffect, useMemo, useRef, useState } from 'react';

import { useQuery } from '@tanstack/react-query';
import { Activity, AlertTriangle, Archive, Bot, Braces, ChevronRight, CircleSlash2, Clock3, Database, FileClock, FileKey2, Filter, History, LockKeyhole, Mail, RefreshCw, Search, Settings2, ShieldCheck, ShieldQuestion, X } from 'lucide-react';
import { Link, useNavigate } from 'react-router-dom';

import './GovernanceOperationsPage.css';
import { governanceOperationsService } from './governanceOperations.service';
import type { ApiLifecycleEntry, GovernanceAuditEvent, GovernanceChangeRequest, GovernanceInventory, GovernanceRetentionPolicy, GovernanceSelection, GovernanceView } from './governanceOperations.types';
import { ADMIN_AUDIT_PROPOSE_FAIL_CLOSED_TITLE } from '../audit/adminAudit.honesty';

import { HaIconButton } from '@/components/ha-icon-button';
import { HaStepper } from '@/components/ha-stepper';
import { StatusDock } from '@/components/status-dock';
import { ROUTES } from '@/constants/routes.constants';
import { useEpsStream } from '@/hooks/useEpsStream';
import { downloadAuditLogExport } from '@/services/auditLog.service';
import { useAuthStore } from '@/store/auth.store';

const viewRoutes:Record<GovernanceView,string>={audit:'/admin/audit',retention:'/admin/retention',configuration:'/admin/settings',changes:'/admin/audit?view=changes',lifecycle:'/admin/audit?view=lifecycle'};
const fmtDate=(value:string|null|undefined):string=>value?new Intl.DateTimeFormat(undefined,{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(value)):'Not reported';
const fmtNumber=(value:number|null|undefined):string=>value===null||value===undefined?'—':new Intl.NumberFormat().format(value);
const words=(value:string):string=>value.replace(/_/g,' ').toLowerCase().replace(/(^|\s)\S/g,(letter)=>letter.toUpperCase());

type GovernanceHonestyChrome={jobSentence:string};

export function GovernanceOperationsPage({initialView='audit',honestyChrome}:{initialView?:GovernanceView;honestyChrome?:GovernanceHonestyChrome}):JSX.Element{
  const navigate=useNavigate();const eps=useEpsStream();const {hasRole}=useAuthStore();const canAdminister=hasRole('ROLE_ADMIN');
  const [view,setView]=useState<GovernanceView>(initialView);const [query,setQuery]=useState('');const [state,setState]=useState('all');const [selected,setSelected]=useState<GovernanceSelection>();const [workflow,setWorkflow]=useState<'retention'|'configuration'|'export'>();
  const inventoryQuery=useQuery({queryKey:['governance-operations'],queryFn:({signal})=>governanceOperationsService.list(signal),enabled:canAdminister,staleTime:30_000,refetchInterval:60_000});
  useEffect(()=>{const requested=new URLSearchParams(window.location.search).get('view') as GovernanceView|null;setView(requested&&requested in viewRoutes?requested:initialView);},[initialView]);
  const inventory=inventoryQuery.data;const rows=useMemo(()=>filterRows(view,inventory,query,state),[view,inventory,query,state]);
  useEffect(()=>{const listener=(event:KeyboardEvent):void=>{const tag=(event.target as HTMLElement).tagName;if(['INPUT','SELECT','TEXTAREA'].includes(tag))return;if(event.key==='Escape'){setSelected(undefined);setWorkflow(undefined);return;}if(event.key==='/'&&!event.metaKey&&!event.ctrlKey){event.preventDefault();document.getElementById('gov-search')?.focus();return;}if(!['j','k','J','K'].includes(event.key)||!rows.length)return;event.preventDefault();const current=rows.findIndex(item=>item.id===selected?.value.id);const next=event.key.toLowerCase()==='j'?Math.min(current+1,rows.length-1):Math.max(current<0?0:current-1,0);setSelected(toSelection(view,rows[next]));};window.addEventListener('keydown',listener);return()=>window.removeEventListener('keydown',listener);},[rows,selected,view]);
  const changeView=(next:GovernanceView):void=>{setView(next);setQuery('');setState('all');setSelected(undefined);navigate(viewRoutes[next]);};
  const hasFilters=Boolean(query.trim())||state!=='all';
  const proposeDisabled=Boolean(honestyChrome&&!governanceOperationsService.fixtureMode&&(view==='retention'||view==='configuration'));
  const proposeTitle=proposeDisabled?ADMIN_AUDIT_PROPOSE_FAIL_CLOSED_TITLE:undefined;
  const showAuditEmptyHonesty=Boolean(honestyChrome&&!inventoryQuery.isLoading&&!inventoryQuery.isError&&inventory&&inventory.audit.length===0&&!governanceOperationsService.fixtureMode&&!hasFilters&&view==='audit');
  const showRetentionEmptyHonesty=Boolean(honestyChrome&&!inventoryQuery.isLoading&&!inventoryQuery.isError&&inventory&&inventory.retention.length===0&&!governanceOperationsService.fixtureMode&&!hasFilters&&view==='retention');
  const projectionNote=honestyChrome&&!governanceOperationsService.fixtureMode?inventory?.partial?'Ledger via GET /api/ha-audit-log returns a bounded page snapshot without tenant scope, integrity proofs or correlation IDs (GOV-001–GOV-002). NDJSON export uses GET /api/ha-audit-log/export with safe fields only. Change control, legal holds and versioned configuration proposals remain fail-closed.':'Ledger via GET /api/ha-audit-log with ADMIN-only NDJSON export. Retention inventory via GET /api/ha-retention-policies; secret-safe settings via GET /api/ha-admin/settings. Governed mutations and integrity verification remain fail-closed until GOV contracts land.':null;
  if(!canAdminister)return <section className="gov-page" data-governance-audit-honesty={honestyChrome?'true':undefined}><Header honestyChrome={honestyChrome} onRefresh={()=>undefined}/>{honestyChrome&&<MetaLinks/>}<PageState icon={<CircleSlash2/>} title="Governance access restricted" detail="Required permission: Platform Administrator."/></section>;
  const action=view==='audit'?{label:'Export evidence',run:()=>setWorkflow('export')}:view==='retention'?{label:'Propose policy',run:()=>setWorkflow('retention')}:view==='configuration'?{label:'Propose change',run:()=>setWorkflow('configuration')}:undefined;
  return <section className="gov-page" data-governance-audit-honesty={honestyChrome?'true':undefined}>
    <Header honestyChrome={honestyChrome} onRefresh={()=>inventoryQuery.refetch()} action={action} proposeDisabled={proposeDisabled} proposeTitle={proposeTitle}/>
    {honestyChrome&&<MetaLinks/>}
    {honestyChrome&&projectionNote&&<p className="gov-page__projection-note" role="note">{projectionNote}</p>}
    {honestyChrome&&!governanceOperationsService.fixtureMode&&<div className="gov-trust" data-testid="governance-propose-fail-closed-banner"><ShieldCheck size={13}/><strong>Governed mutations fail-closed:</strong> Retention revisions, configuration changes and async evidence manifests remain unavailable until GOV-003/GOV-005/GOV-009 contracts land. Read-only audit list and ADMIN export are authorized.</div>}
    {showRetentionEmptyHonesty&&<div className="gov-retention-empty-honesty" role="status" data-testid="gov-retention-empty-honesty"><strong>No retention policies in authorized inventory.</strong><span>An empty retention list is not an error — it means GET /api/ha-retention-policies returned no rows. Audit ledger and masked settings may still load from sibling endpoints; legal holds, impact preview and versioned revision workflows remain contract-pending.</span></div>}
    {showAuditEmptyHonesty&&<div className="gov-audit-empty-honesty" role="status" data-testid="gov-audit-empty-honesty"><strong>No audit events in authorized ledger.</strong><span>An empty audit list is not an error — it means no platform evidence rows matched the current bounded snapshot. Retention policies and masked settings may still load from sibling endpoints; integrity proofs and change-control drafts remain contract-pending.</span></div>}
    {governanceOperationsService.fixtureMode&&<div className="gov-trust"><ShieldCheck size={13}/><strong>Design fixture:</strong> fictional audit, retention and configuration-governance records are enabled.<span>Production never receives these records.</span></div>}
    <Summary inventory={inventory}/><Tabs view={view} inventory={inventory} onChange={changeView}/><Toolbar view={view} query={query} state={state} onQuery={setQuery} onState={setState} onRefresh={()=>inventoryQuery.refetch()} snapshotAt={inventory?.snapshotAt}/>
    <main className="gov-main" data-drawer={Boolean(selected)}><section className="gov-workspace">
      {inventoryQuery.isLoading?<PageState icon={<Activity/>} title="Loading governance control plane" detail="Retrieving the authorized audit, lifecycle and secret-safe configuration projection."/>:inventoryQuery.isError?<PageState error icon={<AlertTriangle/>} title="Governance operations unavailable" detail={inventoryQuery.error instanceof Error?inventoryQuery.error.message:'The governance projection could not be loaded.'} action={()=>inventoryQuery.refetch()}/>:view==='audit'?<AuditTable rows={rows as GovernanceAuditEvent[]} selected={selected?.value.id} onSelect={value=>setSelected({kind:'audit',value})}/>:view==='retention'?<RetentionWorkspace rows={rows as GovernanceRetentionPolicy[]} selected={selected?.value.id} onSelect={value=>setSelected({kind:'retention',value})}/>:view==='configuration'?<ConfigurationWorkspace inventory={inventory} onPropose={()=>setWorkflow('configuration')}/>:view==='changes'?<ChangeTable rows={rows as GovernanceChangeRequest[]} selected={selected?.value.id} onSelect={value=>setSelected({kind:'change',value})}/>:<LifecycleTable rows={rows as ApiLifecycleEntry[]} selected={selected?.value.id} onSelect={value=>setSelected({kind:'lifecycle',value})}/>}
    </section>{selected&&<Detail selection={selected} onClose={()=>setSelected(undefined)}/>}</main>
    <div className="gov-status"><span><LockKeyhole size={11}/>Read evidence is separate from change authority</span><strong>{inventory?.partial?inventory.warnings[0]:governanceOperationsService.fixtureMode?'Fixture workflow · no policy or setting changed':'Authorized governance projection current'}</strong><span>{inventory?.immutableAuditProven?'Integrity asserted by fixture':'Integrity proof not reported'}</span></div><StatusDock className="gov-status-dock" sseConnected={governanceOperationsService.fixtureMode||eps.connected} eps={governanceOperationsService.fixtureMode?12840:eps.eps} mode="historical" lastUpdated={inventoryQuery.dataUpdatedAt?new Date(inventoryQuery.dataUpdatedAt):undefined}/>
    {workflow&&<GovernanceDialog kind={workflow} fixture={governanceOperationsService.fixtureMode} onClose={()=>setWorkflow(undefined)}/>}
  </section>;
}

function Header({onRefresh,action,honestyChrome,proposeDisabled,proposeTitle}:{onRefresh:()=>void;action?:{label:string;run:()=>void};honestyChrome?:GovernanceHonestyChrome;proposeDisabled?:boolean;proposeTitle?:string}):JSX.Element{return <header className="gov-header"><div className="gov-header__identity"><span className="gov-header__mark"><FileKey2 size={18}/></span><div className="gov-header__copy">{honestyChrome?<div className="gov-header__eyebrow"><span className="gov-eyebrow">ADMINISTRATION · GOVERNANCE AUDIT</span><span className="gov-header__badge">STAGING CANDIDATE</span></div>:<span className="gov-eyebrow">ADMINISTRATION · GOVERNANCE CONTROL PLANE</span>}<h1>Audit, Retention &amp; Settings</h1>{honestyChrome&&<p className="gov-header__job">{honestyChrome.jobSentence}</p>}</div></div><div className="gov-header__actions"><span className="gov-shortcut"><kbd>J</kbd>/<kbd>K</kbd> navigate <kbd>Esc</kbd> close</span><button className="gov-button" type="button" onClick={onRefresh}><RefreshCw size={13}/>Refresh</button>{action&&<button className="gov-button gov-button--primary" type="button" onClick={action.run} disabled={proposeDisabled} title={proposeTitle} data-testid={honestyChrome&&proposeDisabled?'governance-propose-fail-closed':undefined}>{action.label}</button>}</div></header>}
function MetaLinks():JSX.Element{return <p className="gov-page__meta"><Link to={ROUTES.ADMIN_USERS}>Identity &amp; Tenancy</Link><span aria-hidden="true">·</span><Link to="/admin/retention">Retention</Link><span aria-hidden="true">·</span><Link to={ROUTES.ADMIN_SETTINGS}>Settings</Link><span aria-hidden="true">·</span><Link to={ROUTES.ADMIN_ENROLLMENT_AUDIT}>Enrollment audit</Link><span aria-hidden="true">·</span><span className="gov-page__access">Platform Administrator</span></p>}
function Summary({inventory}:{inventory?:GovernanceInventory}):JSX.Element{const values=[['Audit events',inventory?.auditTotal,'loaded or exact total'],['Denied · 24h',inventory?.denied24h,'authorization outcomes'],['Legal holds',inventory?.activeHolds,'preservation overrides'],['Pending changes',inventory?.pendingChanges,'approval required'],['Config drift',inventory?.configurationDrift,'unreconciled instances'],['Deprecated APIs',inventory?.deprecatedSurfaces,'tracked consumers']] as const;return <section className="gov-summary" aria-label="Governance operations summary">{values.map(([label,value,note])=><div key={label} data-tone={label==='Denied · 24h'&&value?'danger':(label==='Pending changes'||label==='Config drift'||label==='Deprecated APIs')&&value?'warning':undefined}><span>{label}</span><strong>{fmtNumber(value)}</strong><small>{note}</small></div>)}</section>}
function Tabs({view,inventory,onChange}:{view:GovernanceView;inventory?:GovernanceInventory;onChange:(view:GovernanceView)=>void}):JSX.Element{const tabs=[{id:'audit',label:'Audit ledger',icon:<History/>,count:inventory?.audit.length??0},{id:'retention',label:'Retention',icon:<Archive/>,count:inventory?.retention.length??0},{id:'configuration',label:'Configuration',icon:<Settings2/>,count:inventory?.settings?4:0},{id:'changes',label:'Change control',icon:<FileClock/>,count:inventory?.changes.length??0},{id:'lifecycle',label:'API lifecycle',icon:<Braces/>,count:inventory?.lifecycle.length??0}] as const;return <nav className="gov-tabs" aria-label="Governance workspaces">{tabs.map(tab=><button key={tab.id} role="tab" aria-selected={view===tab.id} type="button" onClick={()=>onChange(tab.id)}>{tab.icon}{tab.label}<small>{tab.count}</small></button>)}</nav>}
function Toolbar({view,query,state,onQuery,onState,onRefresh,snapshotAt}:{view:GovernanceView;query:string;state:string;onQuery:(value:string)=>void;onState:(value:string)=>void;onRefresh:()=>void;snapshotAt?:string}):JSX.Element{return <div className="gov-toolbar"><label className="gov-search"><Search size={13}/><input id="gov-search" aria-label={`Search ${view}`} value={query} onChange={event=>onQuery(event.target.value)} placeholder={`Search ${view}…`}/><kbd>/</kbd></label><label className="gov-filter"><Filter size={12}/><select aria-label={`Filter ${view} state`} value={state} onChange={event=>onState(event.target.value)}><option value="all">All states</option><option value="healthy">Healthy</option><option value="attention">Needs attention</option><option value="critical">Critical</option><option value="pending">Pending</option><option value="approved">Approved</option><option value="rejected">Rejected</option><option value="deprecated">Deprecated</option><option value="unknown">Not reported</option></select></label><HaIconButton className="gov-icon-button" aria-label="Refresh current view" onClick={onRefresh} icon={<RefreshCw size={13}/>}/><span className="gov-toolbar__end">Snapshot {fmtDate(snapshotAt)} · {view==='audit'?'read-only evidence':'governed administration'}</span></div>}

function AuditTable({rows,selected,onSelect}:{rows:GovernanceAuditEvent[];selected?:string;onSelect:(row:GovernanceAuditEvent)=>void}):JSX.Element{return rows.length?<div className="gov-table-wrap"><table className="gov-table gov-table--audit"><thead><tr><th>Occurred</th><th>Actor</th><th>Action</th><th>Resource</th><th>Scope</th><th>Source IP</th><th>Result</th><th/></tr></thead><tbody>{rows.map(row=><tr key={row.id} tabIndex={0} data-selected={row.id===selected} onClick={()=>onSelect(row)} onKeyDown={event=>activate(event,()=>onSelect(row))}><td className="gov-mono">{fmtDate(row.occurredAt)}</td><td><strong>{row.actor}</strong></td><td><div className="gov-cell-title"><span className="gov-row-icon"><Clock3/></span><div><strong>{words(row.action)}</strong><small>{row.details}</small></div></div></td><td>{row.resourceType?<><strong>{words(row.resourceType)}</strong><small className="gov-cell-sub">{row.resourceId??'ID not reported'}</small></>:'Not reported'}</td><td>{row.scope}</td><td className="gov-mono">{row.ipAddress??'—'}</td><td><StateBadge state={row.result}/></td><td><ChevronRight size={13}/></td></tr>)}</tbody></table></div>:<ContractState icon={<History/>} title="No audit evidence matches this view" detail="Adjust the search or state filter. The page does not synthesize audit records when the server returns none."/>}
function RetentionWorkspace({rows,selected,onSelect}:{rows:GovernanceRetentionPolicy[];selected?:string;onSelect:(row:GovernanceRetentionPolicy)=>void}):JSX.Element{return rows.length?<><section className="gov-lifecycle-guide"><div><Database/><span><strong>Hot / searchable</strong><small>Active detection and investigation</small></span></div><ChevronRight/><div><Archive/><span><strong>Archive / cold</strong><small>Cost and access trade-off</small></span></div><ChevronRight/><div><ShieldCheck/><span><strong>Hold evaluation</strong><small>Preservation overrides deletion</small></span></div><ChevronRight/><div><CircleSlash2/><span><strong>Delete</strong><small>Irreversible, policy-authorized action</small></span></div></section><div className="gov-table-wrap gov-table-wrap--retention"><table className="gov-table"><thead><tr><th>Data class</th><th>Searchable retention</th><th>Archive target</th><th>Compression</th><th>Legal holds</th><th>Volume</th><th>Last change</th><th>State</th><th/></tr></thead><tbody>{rows.map(row=><tr key={row.id} tabIndex={0} data-selected={row.id===selected} onClick={()=>onSelect(row)} onKeyDown={event=>activate(event,()=>onSelect(row))}><td><div className="gov-cell-title"><span className="gov-row-icon"><Database/></span><div><strong>{row.name}</strong><small>{row.dataType}</small></div></div></td><td className="gov-mono">{row.retentionDays} days{row.sourceImmutable&&<small className="gov-cell-sub">source immutable</small>}</td><td>{row.archiveTarget}{row.archivePath&&<small className="gov-cell-sub">{row.archivePath}</small>}</td><td>{row.compressionEnabled?'Enabled':'Disabled'}</td><td className="gov-mono">{fmtNumber(row.legalHoldCount)}</td><td className="gov-mono">{row.estimatedVolume??'Not reported'}</td><td className="gov-mono">{fmtDate(row.updatedAt)}</td><td><StateBadge state={row.lifecycleState}/></td><td><ChevronRight size={13}/></td></tr>)}</tbody></table></div></>:<ContractState icon={<Archive/>} title="No retention policies loaded" detail="The backend returned no policy inventory. No default deletion behavior is inferred in the browser."/>}
function ConfigurationWorkspace({inventory,onPropose}:{inventory?:GovernanceInventory;onPropose:()=>void}):JSX.Element{const settings=inventory?.settings;if(!settings)return <ContractState icon={<Settings2/>} title="Secret-safe configuration is unavailable" detail="The authoritative masked settings aggregate could not be loaded. Legacy bulk mutation is not used as a fallback."/>;const groups=[{title:'General',icon:<Settings2/>,status:'Loaded',items:[['Site name',settings.general.siteName],['Timezone',settings.general.timezone],['Locale',settings.general.defaultLocale]]},{title:'Security policy',icon:<ShieldCheck/>,status:settings.security.mfaRequired?'MFA required':'Attention',items:[['Session timeout',`${settings.security.sessionTimeoutMinutes} minutes`],['Minimum password',`${settings.security.passwordMinLength} characters`],['MFA',settings.security.mfaRequired?'Required':'Not required']]},{title:'Email delivery',icon:<Mail/>,status:settings.email.host?'Configured':'Not configured',items:[['SMTP endpoint',settings.email.host||'Not configured'],['Port / TLS',`${settings.email.port} / ${settings.email.useTls?'required':'not required'}`],['Credential','Masked · write only']]},{title:'Hive Intelligence',icon:<Bot/>,status:settings.ai.provider?'Configured':'Not configured',items:[['Provider',settings.ai.provider||'Not configured'],['Model',settings.ai.model||'Not configured'],['Credential','Masked · write only']]}];return <div className="gov-config"><section className="gov-config-banner"><ShieldQuestion/><div><strong>Effective configuration, not an edit form</strong><span>Values are masked where required. Submit configuration changes through review, impact preview, approval, validation and rollout.</span></div><button className="gov-button gov-button--primary" type="button" onClick={onPropose}>Propose change</button></section><div className="gov-config-grid">{groups.map(group=><article key={group.title}><header><span>{group.icon}</span><div><strong>{group.title}</strong><small>{group.status}</small></div></header><dl>{group.items.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><footer><span>Server-masked projection</span><button type="button" onClick={onPropose}>Review change path <ChevronRight/></button></footer></article>)}</div><section className="gov-config-boundary"><LockKeyhole/><div><strong>Change safety boundary</strong><span>The checked-in API applies updates immediately and does not provide version, dry-run diff, approval, rollout receipt or rollback. Production submission stays disabled until that authority exists.</span></div></section></div>}
function ChangeTable({rows,selected,onSelect}:{rows:GovernanceChangeRequest[];selected?:string;onSelect:(row:GovernanceChangeRequest)=>void}):JSX.Element{return rows.length?<div className="gov-table-wrap"><table className="gov-table"><thead><tr><th>Requested</th><th>Change</th><th>Category</th><th>Scope</th><th>Risk</th><th>Approvals</th><th>Window</th><th>State</th><th/></tr></thead><tbody>{rows.map(row=><tr key={row.id} tabIndex={0} data-selected={row.id===selected} onClick={()=>onSelect(row)} onKeyDown={event=>activate(event,()=>onSelect(row))}><td className="gov-mono">{fmtDate(row.requestedAt)}<small className="gov-cell-sub">{row.requestedBy}</small></td><td><strong>{row.title}</strong><small className="gov-cell-sub">{row.id} · {row.version}</small></td><td>{words(row.category)}</td><td>{row.scope}</td><td><RiskBadge risk={row.risk}/></td><td>{row.approvals}</td><td>{row.window}</td><td><StateBadge state={row.state}/></td><td><ChevronRight size={13}/></td></tr>)}</tbody></table></div>:<ContractState icon={<FileClock/>} title="Versioned change control is not available" detail="The backend does not expose drafts, before/after diffs, impact previews, approval decisions, deployment receipts or rollback outcomes."/>}
function LifecycleTable({rows,selected,onSelect}:{rows:ApiLifecycleEntry[];selected?:string;onSelect:(row:ApiLifecycleEntry)=>void}):JSX.Element{return rows.length?<div className="gov-table-wrap"><table className="gov-table"><thead><tr><th>API surface</th><th>Lifecycle</th><th>Successor</th><th>Deprecated</th><th>Sunset</th><th>Consumers</th><th>Owner</th><th/></tr></thead><tbody>{rows.map(row=><tr key={row.id} tabIndex={0} data-selected={row.id===selected} onClick={()=>onSelect(row)} onKeyDown={event=>activate(event,()=>onSelect(row))}><td className="gov-mono"><strong>{row.surface}</strong></td><td><StateBadge state={row.status}/></td><td className="gov-mono">{row.successor??'—'}</td><td>{fmtDate(row.deprecatedAt)}</td><td>{fmtDate(row.sunsetAt)}</td><td className="gov-mono">{fmtNumber(row.consumers)}</td><td>{row.owner??'Not reported'}</td><td><ChevronRight size={13}/></td></tr>)}</tbody></table></div>:<ContractState icon={<Braces/>} title="API lifecycle inventory is not authoritative" detail="The backend emits deprecation headers on selected compatibility routes, but does not expose a governed consumer, owner, successor and removal-gate registry."/>}

function Detail({selection,onClose}:{selection:GovernanceSelection;onClose:()=>void}):JSX.Element{const title=selection.kind==='audit'?words(selection.value.action):selection.kind==='retention'?selection.value.name:selection.kind==='change'?selection.value.title:selection.value.surface;return <aside className="gov-drawer" aria-label={`${title} context`}><header><div><span>{selection.kind.toUpperCase()} CONTEXT</span><strong>{title}</strong></div><HaIconButton className="gov-icon-button" onClick={onClose} aria-label="Close context" icon={<X size={14}/>}/></header><div className="gov-drawer__scroll">{selection.kind==='audit'?<AuditDetail value={selection.value}/>:selection.kind==='retention'?<RetentionDetail value={selection.value}/>:selection.kind==='change'?<ChangeDetail value={selection.value}/>:<LifecycleDetail value={selection.value}/>}<section className="gov-notice"><LockKeyhole/><span>Displayed evidence does not grant mutation authority. Every governed action requires server-side role, scope, policy, version and audit validation.</span></section></div><footer><button className="gov-button" type="button" onClick={onClose}>Close</button></footer></aside>}
function AuditDetail({value}:{value:GovernanceAuditEvent}):JSX.Element{return <><DetailHero icon={<History/>} title={words(value.action)} subtitle={`${value.actor} · ${fmtDate(value.occurredAt)}`} state={value.result}/><p className="gov-detail-copy">{value.details}</p><DetailCard title="Evidence identity" rows={[['Event ID',value.id],['Correlation',value.correlationId??'Not reported'],['Scope',value.scope],['Source IP',value.ipAddress??'Not reported']]}/><DetailCard title="Resource" rows={[['Type',value.resourceType??'Not reported'],['Identifier',value.resourceId??'Not reported'],['Payload','Omitted from UI (matches export safe fields)'],['Integrity proof','Not exposed by live contract']]}/></>}
function RetentionDetail({value}:{value:GovernanceRetentionPolicy}):JSX.Element{return <><DetailHero icon={<Archive/>} title={value.name} subtitle={value.dataType} state={value.lifecycleState}/><DetailCard title="Lifecycle policy" rows={[['Searchable retention',`${value.retentionDays} days`],['Archive',value.archiveTarget],['Compression',value.compressionEnabled?'Enabled':'Disabled'],['Source immutable',value.sourceImmutable?'Yes':'No']]}/><DetailCard title="Impact and exceptions" rows={[['Legal holds',fmtNumber(value.legalHoldCount)],['Estimated volume',value.estimatedVolume??'Not reported'],['Archive path',value.archivePath??'None'],['Last changed',fmtDate(value.updatedAt)]]}/><div className="gov-drawer-actions"><button className="gov-button" type="button" disabled>Preview impact</button><button className="gov-button" type="button" disabled>Propose revision</button></div></>}
function ChangeDetail({value}:{value:GovernanceChangeRequest}):JSX.Element{return <><DetailHero icon={<FileClock/>} title={value.title} subtitle={`${value.id} · ${value.version}`} state={value.state}/><DetailCard title="Governance" rows={[['Requested by',value.requestedBy],['Scope',value.scope],['Risk',words(value.risk)],['Approvals',value.approvals]]}/><DetailCard title="Execution safety" rows={[['Window',value.window],['Rollback',value.rollback],['Category',words(value.category)],['Requested',fmtDate(value.requestedAt)]]}/><div className="gov-drawer-actions"><button className="gov-button" type="button" disabled>Review diff</button><button className="gov-button" type="button" disabled>Open approval</button></div></>}
function LifecycleDetail({value}:{value:ApiLifecycleEntry}):JSX.Element{return <><DetailHero icon={<Braces/>} title={value.surface} subtitle={value.owner??'Owner not reported'} state={value.status}/><DetailCard title="Lifecycle" rows={[['Status',words(value.status)],['Successor',value.successor??'None'],['Deprecated',fmtDate(value.deprecatedAt)],['Sunset',fmtDate(value.sunsetAt)]]}/><DetailCard title="Removal gate" rows={[['Known consumers',fmtNumber(value.consumers)],['Owner',value.owner??'Not reported'],['Usage telemetry',value.consumers===null?'Not reported':'Loaded fixture count'],['Compatibility review','Required before removal']]}/></>}
function DetailHero({icon,title,subtitle,state}:{icon:JSX.Element;title:string;subtitle:string;state:string}):JSX.Element{return <section className="gov-detail-hero"><span>{icon}</span><div><strong>{title}</strong><small>{subtitle}</small></div><StateBadge state={state}/></section>}
function DetailCard({title,rows}:{title:string;rows:readonly (readonly [string,string])[]}):JSX.Element{return <section className="gov-card"><h3>{title}</h3><dl>{rows.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></section>}

function GovernanceDialog({kind,fixture,onClose}:{kind:'retention'|'configuration'|'export';fixture:boolean;onClose:()=>void}):JSX.Element{
  const dialogRef=useRef<HTMLElement>(null);
  const [exportBusy,setExportBusy]=useState(false);
  const [exportError,setExportError]=useState<string|null>(null);
  const content=kind==='retention'?{eyebrow:'DATA LIFECYCLE',title:'Propose a retention revision',description:'Stage a versioned policy change with impact, exception and rollback context.',steps:['Define','Impact','Holds','Approve','Schedule'],fields:[['Data class','Select a governed data class'],['Requested retention','365 days'],['Business reason','Regulatory or operational requirement'],['Effective scope','Authorized tenant or platform']] as const}:kind==='configuration'?{eyebrow:'PLATFORM CHANGE',title:'Propose a configuration change',description:'Create a reviewed change without exposing secret material or applying it directly.',steps:['Select','Diff','Validate','Approve','Roll out'],fields:[['Configuration group','Security policy'],['Setting','Select a setting'],['Requested value','Enter proposed value'],['Change reason','Operational justification']] as const}:{eyebrow:'AUDIT EVIDENCE',title:'Export audit evidence',description:'Download a bounded NDJSON projection via GET /api/ha-audit-log/export. Payload and secret fields are omitted.',steps:['Scope','Fields','Redact','Generate','Retrieve'],fields:[['Time range','Last 24 hours'],['Tenant scope','All authorized tenants'],['Evidence purpose','Audit or investigation reference'],['Output format','NDJSON (safe fields)']] as const};
  useEffect(()=>{dialogRef.current?.querySelector<HTMLElement>('button, select, input')?.focus();},[]);
  const containFocus=(event:React.KeyboardEvent<HTMLElement>):void=>{
    if(event.key==='Escape'){event.preventDefault();onClose();return;}
    if(event.key!=='Tab')return;
    const focusable=Array.from(event.currentTarget.querySelectorAll<HTMLElement>('button:not(:disabled), select:not(:disabled), input:not(:disabled), [tabindex]:not([tabindex="-1"])'));
    if(!focusable.length)return;
    const first=focusable[0];
    const last=focusable[focusable.length-1];
    if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}
    else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}
  };
  const primaryLabel=kind==='export'?(exportBusy?'Downloading…':'Download NDJSON'):`Continue to ${content.steps[1].toLowerCase()}`;
  const primaryDisabled=kind==='export'?fixture||exportBusy:true;
  const onPrimary=async():Promise<void>=>{
    if(kind!=='export'||fixture||exportBusy)return;
    setExportError(null);
    setExportBusy(true);
    try{
      await downloadAuditLogExport();
      onClose();
    }catch(err){
      setExportError(err instanceof Error?err.message:'Audit export failed.');
    }finally{
      setExportBusy(false);
    }
  };
  const notice=fixture
    ?'Visual fixture only. No policy, setting or export job will be created.'
    :kind==='export'
      ?'Live download uses GET /api/ha-audit-log/export (Platform Administrator). Payload is never included.'
      :'The authoritative version, preview, approval and job contract is incomplete; submission remains disabled.';
  return (
    <div className="gov-dialog-backdrop" role="presentation">
      <section ref={dialogRef} className="gov-dialog" role="dialog" aria-modal="true" aria-labelledby="gov-dialog-title" onKeyDown={containFocus}>
        <header>
          <div>
            <span>{content.eyebrow}</span>
            <h2 id="gov-dialog-title">{content.title}</h2>
          </div>
          <HaIconButton className="gov-icon-button" onClick={onClose} aria-label="Close workflow" icon={<X size={14}/>}/>
        </header>
        <div className="gov-dialog__body">
          <p>{content.description}</p>
          <HaStepper
            className="gov-stepper"
            ariaLabel={content.title}
            current={0}
            steps={content.steps.map((step) => ({ id: step, label: step }))}
          />
          <div className="gov-form-grid">
            {content.fields.map(([label,placeholder],index)=>(
              <label className={index > 1 ? 'gov-field gov-field--wide' : 'gov-field'} key={label}>
                <span>{label}</span>
                {index < 2 ? (
                  <select defaultValue="" disabled={kind==='export'}>
                    <option value="" disabled>{placeholder}</option>
                  </select>
                ) : (
                  <input placeholder={placeholder} disabled={kind==='export'}/>
                )}
              </label>
            ))}
          </div>
          <section className="gov-notice">
            <ShieldCheck/>
            <span>{notice}</span>
          </section>
          {exportError ? <p className="gov-detail-copy" role="alert">{exportError}</p> : null}
        </div>
        <footer>
          <button className="gov-button" type="button" onClick={onClose}>Cancel</button>
          <button className="gov-button gov-button--primary" type="button" disabled={primaryDisabled} onClick={()=>{void onPrimary();}}>{primaryLabel}</button>
        </footer>
      </section>
    </div>
  );
}
function StateBadge({state}:{state:string}):JSX.Element{return <span className="gov-state" data-state={state}><i/>{words(state)}</span>}
function RiskBadge({risk}:{risk:string}):JSX.Element{return <span className="gov-risk" data-risk={risk}>{words(risk)}</span>}
function ContractState({icon,title,detail}:{icon:JSX.Element;title:string;detail:string}):JSX.Element{return <div className="gov-contract-state">{icon}<strong>{title}</strong><span>{detail}</span><small><LockKeyhole size={11}/>No browser-inferred governance</small></div>}
function PageState({icon,title,detail,error,action}:{icon:JSX.Element;title:string;detail:string;error?:boolean;action?:()=>void}):JSX.Element{return <div className="gov-empty" data-error={error}>{icon}<strong>{title}</strong><span>{detail}</span>{action&&<button className="gov-button" type="button" onClick={action}>Retry</button>}</div>}
function filterRows(view:GovernanceView,inventory:GovernanceInventory|undefined,query:string,state:string):Array<GovernanceAuditEvent|GovernanceRetentionPolicy|GovernanceChangeRequest|ApiLifecycleEntry>{if(!inventory||view==='configuration')return[];const source=view==='audit'?inventory.audit:view==='retention'?inventory.retention:view==='changes'?inventory.changes:inventory.lifecycle;const needle=query.trim().toLowerCase();return source.filter(item=>{const itemState='result'in item?item.result:'lifecycleState'in item?item.lifecycleState:'status'in item?item.status:item.state;return(state==='all'||itemState===state)&&(!needle||JSON.stringify(item).toLowerCase().includes(needle));})}
function toSelection(view:GovernanceView,value:GovernanceAuditEvent|GovernanceRetentionPolicy|GovernanceChangeRequest|ApiLifecycleEntry):GovernanceSelection{if(view==='audit')return{kind:'audit',value:value as GovernanceAuditEvent};if(view==='retention')return{kind:'retention',value:value as GovernanceRetentionPolicy};if(view==='changes')return{kind:'change',value:value as GovernanceChangeRequest};return{kind:'lifecycle',value:value as ApiLifecycleEntry}}
function activate(event:React.KeyboardEvent,action:()=>void):void{if(event.key==='Enter'||event.key===' '){event.preventDefault();action()}}
