package com.hivearmor.web.rest;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.hivearmor.service.HaAiChatService;
import com.hivearmor.web.rest.dto.AiChatRequestDTO;
import com.hivearmor.web.rest.dto.ChatMessageDTO;
import net.jqwik.api.*;
import net.jqwik.api.lifecycle.BeforeTry;
import reactor.core.publisher.Flux;

import java.security.Principal;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.*;

/**
 * Property 1: SSE event-shape and termination invariant.
 *
 * <p><strong>Property 1: SSE event-shape and termination invariant</strong><br>
 * For any chat producing {@code N ≥ 0} tokens, the SSE frame sequence emitted by
 * {@link HaAiChatResource#chat} yields exactly {@code N} incremental frames matching
 * {@code {delta: <non-empty>, done: false}} followed by exactly one terminal frame
 * {@code {delta: "", done: true, totalTokens: <int ≥ 0>}}, and no frame is emitted
 * after the terminal frame or is malformed JSON.
 *
 * <h2>Approach</h2>
 * <p>Invokes {@link HaAiChatResource#chat} directly (unit-style, no servlet container).
 * {@link HaAiChatService} is mocked via Mockito so that {@code streamChat} returns
 * {@code Flux.fromIterable(tokens)} for jqwik-generated token lists.
 *
 * <p>Each {@code String} emitted by the returned {@code Flux<String>} is a JSON object
 * (the SSE frame body, without the {@code data:} prefix — Spring's SSE pipeline adds
 * that prefix when serialising over HTTP). The test parses each emitted string as JSON
 * and asserts the frame-shape invariant on the parsed sequence.
 *
 * <h2>Minimum iterations</h2>
 * <p>100 (enforced via {@code @Property(tries = 100)}).
 *
 * <p><strong>Validates: Requirements 5.3, 5.4, 7.1, 7.2, 7.3, 7.4</strong>
 *
 * @see HaAiChatResource#chat
 */
@Label("Feature: sprint-25-ai-chat, Property 1: SSE event-shape and termination invariant")
class HaAiChatSsePropertyTest {

    // =========================================================================
    // Fields — re-created before every jqwik try via @BeforeTry
    // =========================================================================

    private HaAiChatResource controller;
    private HaAiChatService   chatService;
    private final ObjectMapper mapper = new ObjectMapper().findAndRegisterModules();

    /** Fixed principal injected into every controller call. */
    private static final Principal TEST_PRINCIPAL = () -> "analyst-user";

    /**
     * Re-create mocks and controller before every jqwik trial so each iteration
     * starts from a clean Mockito state.
     */
    @BeforeTry
    void setUp() {
        chatService  = mock(HaAiChatService.class);
        controller   = new HaAiChatResource(chatService, mapper);
    }

    // =========================================================================
    // Property 1 — SSE event-shape and termination invariant
    // =========================================================================

    /**
     * **Validates: Requirements 5.3, 5.4, 7.1, 7.2, 7.3, 7.4**
     *
     * <p>For any list of {@code N ≥ 0} non-empty token strings produced by
     * {@code HaAiChatService.streamChat}:
     * <ol>
     *   <li>The total number of SSE frames emitted is exactly {@code N + 1}.</li>
     *   <li>The first {@code N} frames each have {@code "done": false} and a
     *       non-empty {@code "delta"} value.</li>
     *   <li>The last frame has {@code "done": true}, {@code "delta": ""},
     *       and {@code "totalTokens" == N}.</li>
     *   <li>Every emitted string is valid JSON (no malformed frames).</li>
     * </ol>
     *
     * @param tokens list of non-empty token strings (generated by jqwik)
     */
    @Property(tries = 100)
    @Label("Feature: sprint-25-ai-chat, Property 1: N incremental frames + exactly 1 terminal frame")
    void property1_sseEventShapeAndTermination(
            @ForAll("nonEmptyTokenLists") List<String> tokens) {

        // Arrange: mock HaAiChatService.streamChat to return Flux.fromIterable(tokens)
        when(chatService.streamChat(any(AiChatRequestDTO.class), anyString()))
            .thenReturn(Flux.fromIterable(tokens));

        // Build a minimal valid request
        AiChatRequestDTO request = new AiChatRequestDTO(
            List.of(new ChatMessageDTO("user", "test message")),
            "general",
            null
        );

        // Act: invoke the controller directly and collect all emitted frame strings
        Flux<String> sseFlux = controller.chat(request, TEST_PRINCIPAL);
        List<String> rawFrames = sseFlux.collectList().block();

        assertThat(rawFrames)
            .as("Flux<String> from chat() must not be null")
            .isNotNull();

        int N = tokens.size();

        // ---- Assertion 1: Total frame count is exactly N + 1 ----
        assertThat(rawFrames)
            .as("Expected exactly %d frames (N=%d incremental + 1 terminal), got %d",
                N + 1, N, rawFrames.size())
            .hasSize(N + 1);

        // Parse each raw string as JSON (malformed JSON will throw → property failure)
        List<JsonNode> frames = parseFrames(rawFrames);

        // ---- Assertion 2: First N frames are incremental ----
        for (int i = 0; i < N; i++) {
            JsonNode frame = frames.get(i);
            String delta = frame.get("delta").asText();
            boolean done = frame.get("done").asBoolean();

            assertThat(done)
                .as("Incremental frame[%d] must have done=false, got done=%s", i, done)
                .isFalse();
            assertThat(delta)
                .as("Incremental frame[%d] must have non-empty delta, got '%s'", i, delta)
                .isNotEmpty();
        }

        // ---- Assertion 3: Last frame is the terminal frame ----
        JsonNode terminal    = frames.get(N);
        String  termDelta    = terminal.get("delta").asText();
        boolean termDone     = terminal.get("done").asBoolean();
        int     totalTokens  = terminal.get("totalTokens").asInt();

        assertThat(termDone)
            .as("Terminal frame must have done=true")
            .isTrue();
        assertThat(termDelta)
            .as("Terminal frame must have delta=\"\" (empty string), got '%s'", termDelta)
            .isEmpty();
        assertThat(totalTokens)
            .as("Terminal frame totalTokens must be ≥ 0, got %d", totalTokens)
            .isGreaterThanOrEqualTo(0);

        // ---- Assertion 4: totalTokens == N ----
        assertThat(totalTokens)
            .as("totalTokens must equal N=%d, got %d", N, totalTokens)
            .isEqualTo(N);
    }

    /**
     * Edge case: N = 0 tokens — only the terminal frame should be emitted.
     *
     * <p><strong>Validates: Requirements 7.1, 7.3, 7.4</strong>
     */
    @Property(tries = 10)
    @Label("Feature: sprint-25-ai-chat, Property 1 (N=0): zero tokens yields exactly one terminal frame")
    void property1_zeroTokens_onlyTerminalFrame() {
        when(chatService.streamChat(any(AiChatRequestDTO.class), anyString()))
            .thenReturn(Flux.empty());

        AiChatRequestDTO request = new AiChatRequestDTO(
            List.of(new ChatMessageDTO("user", "hello")),
            "general",
            null
        );

        Flux<String> sseFlux = controller.chat(request, TEST_PRINCIPAL);
        List<String> rawFrames = sseFlux.collectList().block();

        assertThat(rawFrames).isNotNull();

        // Exactly one frame — the terminal
        assertThat(rawFrames).hasSize(1);

        List<JsonNode> frames = parseFrames(rawFrames);
        JsonNode terminal = frames.get(0);

        assertThat(terminal.get("done").asBoolean()).isTrue();
        assertThat(terminal.get("delta").asText()).isEmpty();
        assertThat(terminal.get("totalTokens").asInt()).isEqualTo(0);
    }

    // =========================================================================
    // Arbitrary providers
    // =========================================================================

    /**
     * Generates lists of 0–20 non-empty token strings.
     *
     * <p>The generator mixes short (1 char) and longer tokens, tokens containing
     * whitespace and punctuation, to exercise SSE frame serialization across diverse
     * deltas. The size range 0–20 keeps each trial fast while exercising N=0
     * (terminal-only), N=1, and multi-token scenarios.
     */
    @Provide
    Arbitrary<List<String>> nonEmptyTokenLists() {
        Arbitrary<String> nonEmptyToken = Arbitraries.strings()
            .ofMinLength(1)
            .ofMaxLength(50)
            .filter(s -> !s.isEmpty());

        return nonEmptyToken.list().ofMinSize(0).ofMaxSize(20);
    }

    // =========================================================================
    // Helpers
    // =========================================================================

    /**
     * Parses each raw SSE frame string as JSON.
     *
     * <p>Each string emitted by {@link HaAiChatResource#chat}'s {@code Flux<String>}
     * is the JSON body of one SSE frame (Spring's reactive SSE pipeline wraps it in
     * {@code data:<json>\n\n} when writing to the HTTP response). This method
     * deserializes each string and returns the list of parsed {@link JsonNode}s.
     *
     * <p>A {@link RuntimeException} wrapping any JSON parse error will propagate as
     * a property failure — satisfying the "no malformed JSON" clause of Property 1.
     *
     * @param rawFrames the ordered list of strings emitted by the controller Flux
     * @return ordered list of parsed JSON frames
     */
    private List<JsonNode> parseFrames(List<String> rawFrames) {
        return rawFrames.stream()
            .map(raw -> {
                try {
                    return mapper.readTree(raw);
                } catch (Exception e) {
                    throw new AssertionError(
                        "SSE frame is not valid JSON — violated 'no malformed frames' invariant. "
                        + "Frame content: [" + raw + "]", e);
                }
            })
            .toList();
    }
}
