package com.hivearmor.web.rest.compliance;

import com.hivearmor.domain.HaClient;
import com.hivearmor.multitenancy.TenantContext;
import com.hivearmor.repository.HaClientRepository;
import com.hivearmor.service.compliance.ComplianceReportGenerationService;
import com.hivearmor.service.dto.compliance.ComplianceReportDto;
import net.jqwik.api.*;
import net.jqwik.api.lifecycle.AfterTry;
import org.junit.jupiter.api.Tag;

import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.Mockito.*;

/**
 * Property-based test for the TenantContext.clear() invariant in
 * {@link ComplianceReportGenerationController}.
 *
 * <p><strong>Property P3 — TenantContext is cleared on every code path</strong>
 * — <strong>Validates: Requirements 6.4, 6.5, 8.1, 8.2</strong>
 *
 * <h2>What is tested</h2>
 * <ol>
 *   <li><strong>P3a (exception path)</strong> — For any {@code RuntimeException} message
 *       string (generated by jqwik), when the service throws, {@code TenantContext.getClientId()}
 *       and {@code TenantContext.getClientPrefix()} return {@code null} after the exception
 *       propagates out of {@code controller.generate(1L)}.</li>
 *   <li><strong>P3b (success path)</strong> — When the service returns normally, the same
 *       TenantContext fields are {@code null} after the call returns.</li>
 * </ol>
 *
 * <h2>Design note — no Spring context</h2>
 * <p>The controller is instantiated directly with Mockito mocks injected via constructor.
 * No Spring Boot test context is loaded, keeping the test fast and hermetic.
 *
 * <h2>Tag</h2>
 * <p>{@code Feature: sprint-24-per-tenant-compliance, Property P3}
 *
 * <h2>Minimum iterations</h2>
 * <p>50 (enforced via {@code @Property(tries = 50)}).
 */
@Tag("Feature: sprint-24-per-tenant-compliance")
@Tag("Property P3")
class ComplianceReportGenerationControllerClearTest {

    // -------------------------------------------------------------------------
    // Test infrastructure – re-created before every jqwik trial via @BeforeTry
    // -------------------------------------------------------------------------

    private ComplianceReportGenerationService complianceReportGenerationService;
    private HaClientRepository haClientRepository;
    private ComplianceReportGenerationController controller;

    /**
     * Initialises fresh mocks and a new controller instance before each trial.
     * This mirrors the jqwik {@code @BeforeTry} lifecycle, but since jqwik
     * doesn't interact with the field directly, we call this from setUp at
     * the start of each property and rely on {@link AfterTry} for cleanup.
     */
    private void resetMocks() {
        complianceReportGenerationService = mock(ComplianceReportGenerationService.class);
        haClientRepository = mock(HaClientRepository.class);
        controller = new ComplianceReportGenerationController(
                complianceReportGenerationService, haClientRepository);

        // Wire a valid HaClient for tenant id 1L
        HaClient tenant = new HaClient();
        tenant.setId(1L);
        tenant.setClientPrefix("test");
        tenant.setName("Test Tenant");
        when(haClientRepository.findById(1L)).thenReturn(Optional.of(tenant));
    }

    /**
     * After every trial: clear {@link TenantContext} to prevent state leaking between
     * trials. This is the MSSP tenant-scope hygiene requirement: every code path that
     * sets TenantContext must clear it afterward, and tests must not leave it dirty.
     */
    @AfterTry
    void afterTry() {
        TenantContext.clear();
    }

    // =========================================================================
    // Property P3a — TenantContext is cleared when the service throws
    // Validates: Requirements 6.4, 6.5
    // =========================================================================

    /**
     * For any {@code RuntimeException} message string generated by jqwik, after
     * {@code controller.generate(1L)} throws, both {@link TenantContext#getClientId()}
     * and {@link TenantContext#getClientPrefix()} MUST be {@code null}.
     *
     * <p>This verifies that the {@code finally { TenantContext.clear(); }} block in
     * {@link ComplianceReportGenerationController#generate(Long)} is reachable on
     * every exception code path — Requirement 6.4.
     *
     * <p><strong>Validates: Requirements 6.4, 6.5</strong>
     */
    @Property(tries = 50)
    void property_tenantContextClearedOnException(@ForAll String exceptionMessage) {
        resetMocks();

        // Arrange: service throws RuntimeException with the generated message
        when(complianceReportGenerationService.generate(1L))
                .thenThrow(new RuntimeException(exceptionMessage));

        // Act: controller throws — the exception must propagate
        assertThatThrownBy(() -> controller.generate(1L))
                .as("controller.generate(1L) must propagate the RuntimeException thrown by the service")
                .isInstanceOf(RuntimeException.class);

        // Assert: TenantContext is cleared after the exception propagates
        assertThat(TenantContext.getClientId())
                .as("TenantContext.getClientId() must be null after a RuntimeException propagates "
                        + "(Requirement 6.4 — finally block must call TenantContext.clear())")
                .isNull();
        assertThat(TenantContext.getClientPrefix())
                .as("TenantContext.getClientPrefix() must be null after a RuntimeException propagates "
                        + "(Requirement 6.5 — no thread-local tenant scope leak)")
                .isNull();
    }

    // =========================================================================
    // Property P3b — TenantContext is cleared when the service succeeds
    // Validates: Requirements 6.3, 6.5
    // =========================================================================

    /**
     * When the service returns a valid {@link ComplianceReportDto} normally (no exception),
     * after {@code controller.generate(1L)} returns, both {@link TenantContext#getClientId()}
     * and {@link TenantContext#getClientPrefix()} MUST be {@code null}.
     *
     * <p>This verifies that the {@code finally { TenantContext.clear(); }} block is also
     * reached on the happy path — Requirement 6.3 (the {@code try} block wraps the service
     * call and the {@code finally} runs unconditionally).
     *
     * <p><strong>Validates: Requirements 6.3, 6.5</strong>
     */
    @Property(tries = 1)
    void property_tenantContextClearedOnSuccess() {
        resetMocks();

        // Arrange: service returns a valid report (no exception)
        ComplianceReportDto report = new ComplianceReportDto();
        report.setTenantId(1L);
        report.setTenantPrefix("test");
        when(complianceReportGenerationService.generate(1L)).thenReturn(report);

        // Act: must succeed without throwing
        var response = controller.generate(1L);

        // Assert: response is 200 OK
        assertThat(response.getStatusCode().value())
                .as("controller.generate(1L) must return HTTP 200 on success")
                .isEqualTo(200);

        // Assert: TenantContext is cleared after successful return
        assertThat(TenantContext.getClientId())
                .as("TenantContext.getClientId() must be null after a successful return "
                        + "(Requirement 6.3 — finally block must call TenantContext.clear())")
                .isNull();
        assertThat(TenantContext.getClientPrefix())
                .as("TenantContext.getClientPrefix() must be null after a successful return "
                        + "(Requirement 6.5 — no thread-local tenant scope leak)")
                .isNull();
    }
}
