// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: agent.proto

package agent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentCommandStatus int32

const (
	AgentCommandStatus_NOT_EXECUTED AgentCommandStatus = 0
	AgentCommandStatus_QUEUE        AgentCommandStatus = 1
	AgentCommandStatus_PENDING      AgentCommandStatus = 2
	AgentCommandStatus_EXECUTED     AgentCommandStatus = 3
	AgentCommandStatus_ERROR        AgentCommandStatus = 4
)

// Enum value maps for AgentCommandStatus.
var (
	AgentCommandStatus_name = map[int32]string{
		0: "NOT_EXECUTED",
		1: "QUEUE",
		2: "PENDING",
		3: "EXECUTED",
		4: "ERROR",
	}
	AgentCommandStatus_value = map[string]int32{
		"NOT_EXECUTED": 0,
		"QUEUE":        1,
		"PENDING":      2,
		"EXECUTED":     3,
		"ERROR":        4,
	}
)

func (x AgentCommandStatus) Enum() *AgentCommandStatus {
	p := new(AgentCommandStatus)
	*p = x
	return p
}

func (x AgentCommandStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentCommandStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_enumTypes[0].Descriptor()
}

func (AgentCommandStatus) Type() protoreflect.EnumType {
	return &file_agent_proto_enumTypes[0]
}

func (x AgentCommandStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentCommandStatus.Descriptor instead.
func (AgentCommandStatus) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

type AgentRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Ip             string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Hostname       string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os             string                 `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
	Platform       string                 `protobuf:"bytes,4,opt,name=platform,proto3" json:"platform,omitempty"`
	Version        string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	RegisterBy     string                 `protobuf:"bytes,6,opt,name=register_by,json=registerBy,proto3" json:"register_by,omitempty"`
	Mac            string                 `protobuf:"bytes,7,opt,name=mac,proto3" json:"mac,omitempty"`
	OsMajorVersion string                 `protobuf:"bytes,8,opt,name=os_major_version,json=osMajorVersion,proto3" json:"os_major_version,omitempty"`
	OsMinorVersion string                 `protobuf:"bytes,9,opt,name=os_minor_version,json=osMinorVersion,proto3" json:"os_minor_version,omitempty"`
	Aliases        string                 `protobuf:"bytes,10,opt,name=aliases,proto3" json:"aliases,omitempty"`
	Addresses      string                 `protobuf:"bytes,11,opt,name=addresses,proto3" json:"addresses,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AgentRequest) Reset() {
	*x = AgentRequest{}
	mi := &file_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRequest) ProtoMessage() {}

func (x *AgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRequest.ProtoReflect.Descriptor instead.
func (*AgentRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AgentRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *AgentRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *AgentRequest) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *AgentRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *AgentRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AgentRequest) GetRegisterBy() string {
	if x != nil {
		return x.RegisterBy
	}
	return ""
}

func (x *AgentRequest) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *AgentRequest) GetOsMajorVersion() string {
	if x != nil {
		return x.OsMajorVersion
	}
	return ""
}

func (x *AgentRequest) GetOsMinorVersion() string {
	if x != nil {
		return x.OsMinorVersion
	}
	return ""
}

func (x *AgentRequest) GetAliases() string {
	if x != nil {
		return x.Aliases
	}
	return ""
}

func (x *AgentRequest) GetAddresses() string {
	if x != nil {
		return x.Addresses
	}
	return ""
}

type ListAgentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          []*Agent               `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsResponse) Reset() {
	*x = ListAgentsResponse{}
	mi := &file_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsResponse) ProtoMessage() {}

func (x *ListAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsResponse.ProtoReflect.Descriptor instead.
func (*ListAgentsResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *ListAgentsResponse) GetRows() []*Agent {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *ListAgentsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type Agent struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Ip                  string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Hostname            string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os                  string                 `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
	Status              Status                 `protobuf:"varint,4,opt,name=status,proto3,enum=agent.Status" json:"status,omitempty"`
	Platform            string                 `protobuf:"bytes,5,opt,name=platform,proto3" json:"platform,omitempty"`
	Version             string                 `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	AgentKey            string                 `protobuf:"bytes,7,opt,name=agent_key,json=agentKey,proto3" json:"agent_key,omitempty"`
	Id                  uint32                 `protobuf:"varint,8,opt,name=id,proto3" json:"id,omitempty"`
	LastSeen            string                 `protobuf:"bytes,9,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	Mac                 string                 `protobuf:"bytes,10,opt,name=mac,proto3" json:"mac,omitempty"`
	OsMajorVersion      string                 `protobuf:"bytes,11,opt,name=os_major_version,json=osMajorVersion,proto3" json:"os_major_version,omitempty"`
	OsMinorVersion      string                 `protobuf:"bytes,12,opt,name=os_minor_version,json=osMinorVersion,proto3" json:"os_minor_version,omitempty"`
	Aliases             string                 `protobuf:"bytes,13,opt,name=aliases,proto3" json:"aliases,omitempty"`
	Addresses           string                 `protobuf:"bytes,14,opt,name=addresses,proto3" json:"addresses,omitempty"`
	AgentUuid           string                 `protobuf:"bytes,15,opt,name=agent_uuid,json=agentUuid,proto3" json:"agent_uuid,omitempty"`
	TenantId            int64                  `protobuf:"varint,16,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	CredentialVersion   uint32                 `protobuf:"varint,17,opt,name=credential_version,json=credentialVersion,proto3" json:"credential_version,omitempty"`
	CredentialRevokedAt *timestamppb.Timestamp `protobuf:"bytes,18,opt,name=credential_revoked_at,json=credentialRevokedAt,proto3" json:"credential_revoked_at,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Agent) Reset() {
	*x = Agent{}
	mi := &file_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Agent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Agent) ProtoMessage() {}

func (x *Agent) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Agent.ProtoReflect.Descriptor instead.
func (*Agent) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

func (x *Agent) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Agent) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Agent) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *Agent) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_ONLINE
}

func (x *Agent) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *Agent) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Agent) GetAgentKey() string {
	if x != nil {
		return x.AgentKey
	}
	return ""
}

func (x *Agent) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Agent) GetLastSeen() string {
	if x != nil {
		return x.LastSeen
	}
	return ""
}

func (x *Agent) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *Agent) GetOsMajorVersion() string {
	if x != nil {
		return x.OsMajorVersion
	}
	return ""
}

func (x *Agent) GetOsMinorVersion() string {
	if x != nil {
		return x.OsMinorVersion
	}
	return ""
}

func (x *Agent) GetAliases() string {
	if x != nil {
		return x.Aliases
	}
	return ""
}

func (x *Agent) GetAddresses() string {
	if x != nil {
		return x.Addresses
	}
	return ""
}

func (x *Agent) GetAgentUuid() string {
	if x != nil {
		return x.AgentUuid
	}
	return ""
}

func (x *Agent) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *Agent) GetCredentialVersion() uint32 {
	if x != nil {
		return x.CredentialVersion
	}
	return 0
}

func (x *Agent) GetCredentialRevokedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CredentialRevokedAt
	}
	return nil
}

type CreateEnrollmentTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      int64                  `protobuf:"varint,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	PolicyId      string                 `protobuf:"bytes,2,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	Platform      string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	MaxUses       int32                  `protobuf:"varint,5,opt,name=max_uses,json=maxUses,proto3" json:"max_uses,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,6,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEnrollmentTokenRequest) Reset() {
	*x = CreateEnrollmentTokenRequest{}
	mi := &file_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEnrollmentTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEnrollmentTokenRequest) ProtoMessage() {}

func (x *CreateEnrollmentTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEnrollmentTokenRequest.ProtoReflect.Descriptor instead.
func (*CreateEnrollmentTokenRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

func (x *CreateEnrollmentTokenRequest) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *CreateEnrollmentTokenRequest) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *CreateEnrollmentTokenRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *CreateEnrollmentTokenRequest) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *CreateEnrollmentTokenRequest) GetMaxUses() int32 {
	if x != nil {
		return x.MaxUses
	}
	return 0
}

func (x *CreateEnrollmentTokenRequest) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

type EnrollmentToken struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId         int64                  `protobuf:"varint,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	PolicyId         string                 `protobuf:"bytes,3,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	Platform         string                 `protobuf:"bytes,4,opt,name=platform,proto3" json:"platform,omitempty"`
	ExpiresAt        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	MaxUses          int32                  `protobuf:"varint,6,opt,name=max_uses,json=maxUses,proto3" json:"max_uses,omitempty"`
	UseCount         int32                  `protobuf:"varint,7,opt,name=use_count,json=useCount,proto3" json:"use_count,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CreatedBy        string                 `protobuf:"bytes,9,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	LastUsedAt       *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=last_used_at,json=lastUsedAt,proto3" json:"last_used_at,omitempty"`
	RevokedAt        *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=revoked_at,json=revokedAt,proto3" json:"revoked_at,omitempty"`
	RevokedBy        string                 `protobuf:"bytes,12,opt,name=revoked_by,json=revokedBy,proto3" json:"revoked_by,omitempty"`
	RevocationReason string                 `protobuf:"bytes,13,opt,name=revocation_reason,json=revocationReason,proto3" json:"revocation_reason,omitempty"`
	Version          uint64                 `protobuf:"varint,14,opt,name=version,proto3" json:"version,omitempty"`
	Status           string                 `protobuf:"bytes,15,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EnrollmentToken) Reset() {
	*x = EnrollmentToken{}
	mi := &file_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollmentToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollmentToken) ProtoMessage() {}

func (x *EnrollmentToken) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollmentToken.ProtoReflect.Descriptor instead.
func (*EnrollmentToken) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

func (x *EnrollmentToken) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EnrollmentToken) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *EnrollmentToken) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *EnrollmentToken) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *EnrollmentToken) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *EnrollmentToken) GetMaxUses() int32 {
	if x != nil {
		return x.MaxUses
	}
	return 0
}

func (x *EnrollmentToken) GetUseCount() int32 {
	if x != nil {
		return x.UseCount
	}
	return 0
}

func (x *EnrollmentToken) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *EnrollmentToken) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *EnrollmentToken) GetLastUsedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUsedAt
	}
	return nil
}

func (x *EnrollmentToken) GetRevokedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RevokedAt
	}
	return nil
}

func (x *EnrollmentToken) GetRevokedBy() string {
	if x != nil {
		return x.RevokedBy
	}
	return ""
}

func (x *EnrollmentToken) GetRevocationReason() string {
	if x != nil {
		return x.RevocationReason
	}
	return ""
}

func (x *EnrollmentToken) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *EnrollmentToken) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CreateEnrollmentTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enrollment    *EnrollmentToken       `protobuf:"bytes,1,opt,name=enrollment,proto3" json:"enrollment,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEnrollmentTokenResponse) Reset() {
	*x = CreateEnrollmentTokenResponse{}
	mi := &file_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEnrollmentTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEnrollmentTokenResponse) ProtoMessage() {}

func (x *CreateEnrollmentTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEnrollmentTokenResponse.ProtoReflect.Descriptor instead.
func (*CreateEnrollmentTokenResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{5}
}

func (x *CreateEnrollmentTokenResponse) GetEnrollment() *EnrollmentToken {
	if x != nil {
		return x.Enrollment
	}
	return nil
}

func (x *CreateEnrollmentTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ListEnrollmentTokensRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      int64                  `protobuf:"varint,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	PageNumber    int32                  `protobuf:"varint,2,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEnrollmentTokensRequest) Reset() {
	*x = ListEnrollmentTokensRequest{}
	mi := &file_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEnrollmentTokensRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEnrollmentTokensRequest) ProtoMessage() {}

func (x *ListEnrollmentTokensRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEnrollmentTokensRequest.ProtoReflect.Descriptor instead.
func (*ListEnrollmentTokensRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{6}
}

func (x *ListEnrollmentTokensRequest) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *ListEnrollmentTokensRequest) GetPageNumber() int32 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

func (x *ListEnrollmentTokensRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListEnrollmentTokensResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          []*EnrollmentToken     `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEnrollmentTokensResponse) Reset() {
	*x = ListEnrollmentTokensResponse{}
	mi := &file_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEnrollmentTokensResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEnrollmentTokensResponse) ProtoMessage() {}

func (x *ListEnrollmentTokensResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEnrollmentTokensResponse.ProtoReflect.Descriptor instead.
func (*ListEnrollmentTokensResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{7}
}

func (x *ListEnrollmentTokensResponse) GetRows() []*EnrollmentToken {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *ListEnrollmentTokensResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type RevokeEnrollmentTokenRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId        int64                  `protobuf:"varint,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	RevokedBy       string                 `protobuf:"bytes,3,opt,name=revoked_by,json=revokedBy,proto3" json:"revoked_by,omitempty"`
	Reason          string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	ExpectedVersion uint64                 `protobuf:"varint,5,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RevokeEnrollmentTokenRequest) Reset() {
	*x = RevokeEnrollmentTokenRequest{}
	mi := &file_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeEnrollmentTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeEnrollmentTokenRequest) ProtoMessage() {}

func (x *RevokeEnrollmentTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeEnrollmentTokenRequest.ProtoReflect.Descriptor instead.
func (*RevokeEnrollmentTokenRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{8}
}

func (x *RevokeEnrollmentTokenRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RevokeEnrollmentTokenRequest) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *RevokeEnrollmentTokenRequest) GetRevokedBy() string {
	if x != nil {
		return x.RevokedBy
	}
	return ""
}

func (x *RevokeEnrollmentTokenRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RevokeEnrollmentTokenRequest) GetExpectedVersion() uint64 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

type AgentCredentialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       uint32                 `protobuf:"varint,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	TenantId      int64                  `protobuf:"varint,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Actor         string                 `protobuf:"bytes,3,opt,name=actor,proto3" json:"actor,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentCredentialRequest) Reset() {
	*x = AgentCredentialRequest{}
	mi := &file_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentCredentialRequest) ProtoMessage() {}

func (x *AgentCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentCredentialRequest.ProtoReflect.Descriptor instead.
func (*AgentCredentialRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{9}
}

func (x *AgentCredentialRequest) GetAgentId() uint32 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *AgentCredentialRequest) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *AgentCredentialRequest) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *AgentCredentialRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type AgentCredentialResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AgentId           uint32                 `protobuf:"varint,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	AgentUuid         string                 `protobuf:"bytes,2,opt,name=agent_uuid,json=agentUuid,proto3" json:"agent_uuid,omitempty"`
	CredentialVersion uint32                 `protobuf:"varint,3,opt,name=credential_version,json=credentialVersion,proto3" json:"credential_version,omitempty"`
	Key               string                 `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	RevokedAt         *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=revoked_at,json=revokedAt,proto3" json:"revoked_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AgentCredentialResponse) Reset() {
	*x = AgentCredentialResponse{}
	mi := &file_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentCredentialResponse) ProtoMessage() {}

func (x *AgentCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentCredentialResponse.ProtoReflect.Descriptor instead.
func (*AgentCredentialResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{10}
}

func (x *AgentCredentialResponse) GetAgentId() uint32 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *AgentCredentialResponse) GetAgentUuid() string {
	if x != nil {
		return x.AgentUuid
	}
	return ""
}

func (x *AgentCredentialResponse) GetCredentialVersion() uint32 {
	if x != nil {
		return x.CredentialVersion
	}
	return 0
}

func (x *AgentCredentialResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *AgentCredentialResponse) GetRevokedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RevokedAt
	}
	return nil
}

type EnrollmentAuditEvent struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId          int64                  `protobuf:"varint,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	EventType         string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Actor             string                 `protobuf:"bytes,4,opt,name=actor,proto3" json:"actor,omitempty"`
	Reason            string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	TokenId           string                 `protobuf:"bytes,6,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	AgentId           uint32                 `protobuf:"varint,7,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	AgentUuid         string                 `protobuf:"bytes,8,opt,name=agent_uuid,json=agentUuid,proto3" json:"agent_uuid,omitempty"`
	PolicyId          string                 `protobuf:"bytes,9,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	Platform          string                 `protobuf:"bytes,10,opt,name=platform,proto3" json:"platform,omitempty"`
	CredentialVersion uint32                 `protobuf:"varint,11,opt,name=credential_version,json=credentialVersion,proto3" json:"credential_version,omitempty"`
	EnrollmentVersion uint64                 `protobuf:"varint,12,opt,name=enrollment_version,json=enrollmentVersion,proto3" json:"enrollment_version,omitempty"`
	OccurredAt        *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EnrollmentAuditEvent) Reset() {
	*x = EnrollmentAuditEvent{}
	mi := &file_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollmentAuditEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollmentAuditEvent) ProtoMessage() {}

func (x *EnrollmentAuditEvent) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollmentAuditEvent.ProtoReflect.Descriptor instead.
func (*EnrollmentAuditEvent) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{11}
}

func (x *EnrollmentAuditEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EnrollmentAuditEvent) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *EnrollmentAuditEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *EnrollmentAuditEvent) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *EnrollmentAuditEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *EnrollmentAuditEvent) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *EnrollmentAuditEvent) GetAgentId() uint32 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *EnrollmentAuditEvent) GetAgentUuid() string {
	if x != nil {
		return x.AgentUuid
	}
	return ""
}

func (x *EnrollmentAuditEvent) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *EnrollmentAuditEvent) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *EnrollmentAuditEvent) GetCredentialVersion() uint32 {
	if x != nil {
		return x.CredentialVersion
	}
	return 0
}

func (x *EnrollmentAuditEvent) GetEnrollmentVersion() uint64 {
	if x != nil {
		return x.EnrollmentVersion
	}
	return 0
}

func (x *EnrollmentAuditEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

type ListEnrollmentAuditEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      int64                  `protobuf:"varint,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	PageNumber    int32                  `protobuf:"varint,2,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	TokenId       string                 `protobuf:"bytes,4,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	AgentUuid     string                 `protobuf:"bytes,5,opt,name=agent_uuid,json=agentUuid,proto3" json:"agent_uuid,omitempty"`
	EventType     string                 `protobuf:"bytes,6,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEnrollmentAuditEventsRequest) Reset() {
	*x = ListEnrollmentAuditEventsRequest{}
	mi := &file_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEnrollmentAuditEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEnrollmentAuditEventsRequest) ProtoMessage() {}

func (x *ListEnrollmentAuditEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEnrollmentAuditEventsRequest.ProtoReflect.Descriptor instead.
func (*ListEnrollmentAuditEventsRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{12}
}

func (x *ListEnrollmentAuditEventsRequest) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *ListEnrollmentAuditEventsRequest) GetPageNumber() int32 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

func (x *ListEnrollmentAuditEventsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListEnrollmentAuditEventsRequest) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *ListEnrollmentAuditEventsRequest) GetAgentUuid() string {
	if x != nil {
		return x.AgentUuid
	}
	return ""
}

func (x *ListEnrollmentAuditEventsRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

type ListEnrollmentAuditEventsResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Rows          []*EnrollmentAuditEvent `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	Total         int64                   `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEnrollmentAuditEventsResponse) Reset() {
	*x = ListEnrollmentAuditEventsResponse{}
	mi := &file_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEnrollmentAuditEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEnrollmentAuditEventsResponse) ProtoMessage() {}

func (x *ListEnrollmentAuditEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEnrollmentAuditEventsResponse.ProtoReflect.Descriptor instead.
func (*ListEnrollmentAuditEventsResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{13}
}

func (x *ListEnrollmentAuditEventsResponse) GetRows() []*EnrollmentAuditEvent {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *ListEnrollmentAuditEventsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type BidirectionalStream struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to StreamMessage:
	//
	//	*BidirectionalStream_Command
	//	*BidirectionalStream_Result
	StreamMessage isBidirectionalStream_StreamMessage `protobuf_oneof:"stream_message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidirectionalStream) Reset() {
	*x = BidirectionalStream{}
	mi := &file_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidirectionalStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidirectionalStream) ProtoMessage() {}

func (x *BidirectionalStream) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidirectionalStream.ProtoReflect.Descriptor instead.
func (*BidirectionalStream) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{14}
}

func (x *BidirectionalStream) GetStreamMessage() isBidirectionalStream_StreamMessage {
	if x != nil {
		return x.StreamMessage
	}
	return nil
}

func (x *BidirectionalStream) GetCommand() *UtmCommand {
	if x != nil {
		if x, ok := x.StreamMessage.(*BidirectionalStream_Command); ok {
			return x.Command
		}
	}
	return nil
}

func (x *BidirectionalStream) GetResult() *CommandResult {
	if x != nil {
		if x, ok := x.StreamMessage.(*BidirectionalStream_Result); ok {
			return x.Result
		}
	}
	return nil
}

type isBidirectionalStream_StreamMessage interface {
	isBidirectionalStream_StreamMessage()
}

type BidirectionalStream_Command struct {
	Command *UtmCommand `protobuf:"bytes,1,opt,name=command,proto3,oneof"`
}

type BidirectionalStream_Result struct {
	Result *CommandResult `protobuf:"bytes,2,opt,name=result,proto3,oneof"`
}

func (*BidirectionalStream_Command) isBidirectionalStream_StreamMessage() {}

func (*BidirectionalStream_Result) isBidirectionalStream_StreamMessage() {}

type UtmCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	ExecutedBy    string                 `protobuf:"bytes,3,opt,name=executed_by,json=executedBy,proto3" json:"executed_by,omitempty"`
	CmdId         string                 `protobuf:"bytes,4,opt,name=cmd_id,json=cmdId,proto3" json:"cmd_id,omitempty"`
	OriginType    string                 `protobuf:"bytes,5,opt,name=origin_type,json=originType,proto3" json:"origin_type,omitempty"`
	OriginId      string                 `protobuf:"bytes,6,opt,name=origin_id,json=originId,proto3" json:"origin_id,omitempty"`
	Reason        string                 `protobuf:"bytes,7,opt,name=reason,proto3" json:"reason,omitempty"`
	Shell         string                 `protobuf:"bytes,8,opt,name=shell,proto3" json:"shell,omitempty"` // Shell to execute command: "cmd", "powershell" (Windows), "sh", "bash" (Linux/macOS). Empty = default
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UtmCommand) Reset() {
	*x = UtmCommand{}
	mi := &file_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UtmCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UtmCommand) ProtoMessage() {}

func (x *UtmCommand) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UtmCommand.ProtoReflect.Descriptor instead.
func (*UtmCommand) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{15}
}

func (x *UtmCommand) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *UtmCommand) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *UtmCommand) GetExecutedBy() string {
	if x != nil {
		return x.ExecutedBy
	}
	return ""
}

func (x *UtmCommand) GetCmdId() string {
	if x != nil {
		return x.CmdId
	}
	return ""
}

func (x *UtmCommand) GetOriginType() string {
	if x != nil {
		return x.OriginType
	}
	return ""
}

func (x *UtmCommand) GetOriginId() string {
	if x != nil {
		return x.OriginId
	}
	return ""
}

func (x *UtmCommand) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *UtmCommand) GetShell() string {
	if x != nil {
		return x.Shell
	}
	return ""
}

type CommandResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Result        string                 `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	ExecutedAt    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=executed_at,json=executedAt,proto3" json:"executed_at,omitempty"`
	CmdId         string                 `protobuf:"bytes,4,opt,name=cmd_id,json=cmdId,proto3" json:"cmd_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{16}
}

func (x *CommandResult) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *CommandResult) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *CommandResult) GetExecutedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExecutedAt
	}
	return nil
}

func (x *CommandResult) GetCmdId() string {
	if x != nil {
		return x.CmdId
	}
	return ""
}

type ListAgentsCommandsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          []*AgentCommand        `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsCommandsResponse) Reset() {
	*x = ListAgentsCommandsResponse{}
	mi := &file_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsCommandsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsCommandsResponse) ProtoMessage() {}

func (x *ListAgentsCommandsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsCommandsResponse.ProtoReflect.Descriptor instead.
func (*ListAgentsCommandsResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{17}
}

func (x *ListAgentsCommandsResponse) GetRows() []*AgentCommand {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *ListAgentsCommandsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type AgentCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	AgentId       uint32                 `protobuf:"varint,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Command       string                 `protobuf:"bytes,4,opt,name=command,proto3" json:"command,omitempty"`
	CommandStatus AgentCommandStatus     `protobuf:"varint,5,opt,name=command_status,json=commandStatus,proto3,enum=agent.AgentCommandStatus" json:"command_status,omitempty"`
	Result        string                 `protobuf:"bytes,6,opt,name=result,proto3" json:"result,omitempty"`
	ExecutedBy    string                 `protobuf:"bytes,7,opt,name=executed_by,json=executedBy,proto3" json:"executed_by,omitempty"`
	CmdId         string                 `protobuf:"bytes,8,opt,name=cmd_id,json=cmdId,proto3" json:"cmd_id,omitempty"`
	Reason        string                 `protobuf:"bytes,9,opt,name=reason,proto3" json:"reason,omitempty"`
	OriginType    string                 `protobuf:"bytes,10,opt,name=origin_type,json=originType,proto3" json:"origin_type,omitempty"`
	OriginId      string                 `protobuf:"bytes,11,opt,name=origin_id,json=originId,proto3" json:"origin_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentCommand) Reset() {
	*x = AgentCommand{}
	mi := &file_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentCommand) ProtoMessage() {}

func (x *AgentCommand) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentCommand.ProtoReflect.Descriptor instead.
func (*AgentCommand) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{18}
}

func (x *AgentCommand) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AgentCommand) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *AgentCommand) GetAgentId() uint32 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *AgentCommand) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *AgentCommand) GetCommandStatus() AgentCommandStatus {
	if x != nil {
		return x.CommandStatus
	}
	return AgentCommandStatus_NOT_EXECUTED
}

func (x *AgentCommand) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *AgentCommand) GetExecutedBy() string {
	if x != nil {
		return x.ExecutedBy
	}
	return ""
}

func (x *AgentCommand) GetCmdId() string {
	if x != nil {
		return x.CmdId
	}
	return ""
}

func (x *AgentCommand) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *AgentCommand) GetOriginType() string {
	if x != nil {
		return x.OriginType
	}
	return ""
}

func (x *AgentCommand) GetOriginId() string {
	if x != nil {
		return x.OriginId
	}
	return ""
}

type VerifyConnectorIdentityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnectorId   uint32                 `protobuf:"varint,1,opt,name=connector_id,json=connectorId,proto3" json:"connector_id,omitempty"`
	PresentedKey  string                 `protobuf:"bytes,2,opt,name=presented_key,json=presentedKey,proto3" json:"presented_key,omitempty"`
	ConnectorType ConnectorType          `protobuf:"varint,3,opt,name=connector_type,json=connectorType,proto3,enum=agent.ConnectorType" json:"connector_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyConnectorIdentityRequest) Reset() {
	*x = VerifyConnectorIdentityRequest{}
	mi := &file_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyConnectorIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyConnectorIdentityRequest) ProtoMessage() {}

func (x *VerifyConnectorIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyConnectorIdentityRequest.ProtoReflect.Descriptor instead.
func (*VerifyConnectorIdentityRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{19}
}

func (x *VerifyConnectorIdentityRequest) GetConnectorId() uint32 {
	if x != nil {
		return x.ConnectorId
	}
	return 0
}

func (x *VerifyConnectorIdentityRequest) GetPresentedKey() string {
	if x != nil {
		return x.PresentedKey
	}
	return ""
}

func (x *VerifyConnectorIdentityRequest) GetConnectorType() ConnectorType {
	if x != nil {
		return x.ConnectorType
	}
	return ConnectorType_AGENT
}

type VerifyConnectorIdentityResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uuid              string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	TenantId          int64                  `protobuf:"varint,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	CredentialVersion uint32                 `protobuf:"varint,4,opt,name=credential_version,json=credentialVersion,proto3" json:"credential_version,omitempty"`
	Revoked           bool                   `protobuf:"varint,5,opt,name=revoked,proto3" json:"revoked,omitempty"`
	ConnectorType     ConnectorType          `protobuf:"varint,6,opt,name=connector_type,json=connectorType,proto3,enum=agent.ConnectorType" json:"connector_type,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *VerifyConnectorIdentityResponse) Reset() {
	*x = VerifyConnectorIdentityResponse{}
	mi := &file_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyConnectorIdentityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyConnectorIdentityResponse) ProtoMessage() {}

func (x *VerifyConnectorIdentityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyConnectorIdentityResponse.ProtoReflect.Descriptor instead.
func (*VerifyConnectorIdentityResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{20}
}

func (x *VerifyConnectorIdentityResponse) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *VerifyConnectorIdentityResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *VerifyConnectorIdentityResponse) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *VerifyConnectorIdentityResponse) GetCredentialVersion() uint32 {
	if x != nil {
		return x.CredentialVersion
	}
	return 0
}

func (x *VerifyConnectorIdentityResponse) GetRevoked() bool {
	if x != nil {
		return x.Revoked
	}
	return false
}

func (x *VerifyConnectorIdentityResponse) GetConnectorType() ConnectorType {
	if x != nil {
		return x.ConnectorType
	}
	return ConnectorType_AGENT
}

type ListConnectorAuthorizationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnectorType ConnectorType          `protobuf:"varint,1,opt,name=connector_type,json=connectorType,proto3,enum=agent.ConnectorType" json:"connector_type,omitempty"`
	PageNumber    int32                  `protobuf:"varint,2,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConnectorAuthorizationRequest) Reset() {
	*x = ListConnectorAuthorizationRequest{}
	mi := &file_agent_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConnectorAuthorizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConnectorAuthorizationRequest) ProtoMessage() {}

func (x *ListConnectorAuthorizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConnectorAuthorizationRequest.ProtoReflect.Descriptor instead.
func (*ListConnectorAuthorizationRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{21}
}

func (x *ListConnectorAuthorizationRequest) GetConnectorType() ConnectorType {
	if x != nil {
		return x.ConnectorType
	}
	return ConnectorType_AGENT
}

func (x *ListConnectorAuthorizationRequest) GetPageNumber() int32 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

func (x *ListConnectorAuthorizationRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ConnectorAuthorization struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uuid              string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	TenantId          int64                  `protobuf:"varint,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Revoked           bool                   `protobuf:"varint,4,opt,name=revoked,proto3" json:"revoked,omitempty"`
	CredentialVersion uint32                 `protobuf:"varint,5,opt,name=credential_version,json=credentialVersion,proto3" json:"credential_version,omitempty"`
	ConnectorType     ConnectorType          `protobuf:"varint,6,opt,name=connector_type,json=connectorType,proto3,enum=agent.ConnectorType" json:"connector_type,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ConnectorAuthorization) Reset() {
	*x = ConnectorAuthorization{}
	mi := &file_agent_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectorAuthorization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectorAuthorization) ProtoMessage() {}

func (x *ConnectorAuthorization) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectorAuthorization.ProtoReflect.Descriptor instead.
func (*ConnectorAuthorization) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{22}
}

func (x *ConnectorAuthorization) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ConnectorAuthorization) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ConnectorAuthorization) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *ConnectorAuthorization) GetRevoked() bool {
	if x != nil {
		return x.Revoked
	}
	return false
}

func (x *ConnectorAuthorization) GetCredentialVersion() uint32 {
	if x != nil {
		return x.CredentialVersion
	}
	return 0
}

func (x *ConnectorAuthorization) GetConnectorType() ConnectorType {
	if x != nil {
		return x.ConnectorType
	}
	return ConnectorType_AGENT
}

type ListConnectorAuthorizationResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Rows          []*ConnectorAuthorization `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	Total         int32                     `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConnectorAuthorizationResponse) Reset() {
	*x = ListConnectorAuthorizationResponse{}
	mi := &file_agent_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConnectorAuthorizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConnectorAuthorizationResponse) ProtoMessage() {}

func (x *ListConnectorAuthorizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConnectorAuthorizationResponse.ProtoReflect.Descriptor instead.
func (*ListConnectorAuthorizationResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{23}
}

func (x *ListConnectorAuthorizationResponse) GetRows() []*ConnectorAuthorization {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *ListConnectorAuthorizationResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_agent_proto protoreflect.FileDescriptor

const file_agent_proto_rawDesc = "" +
	"\n" +
	"\vagent.proto\x12\x05agent\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\fcommon.proto\"\xbf\x02\n" +
	"\fAgentRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x03 \x01(\tR\x02os\x12\x1a\n" +
	"\bplatform\x18\x04 \x01(\tR\bplatform\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x12\x1f\n" +
	"\vregister_by\x18\x06 \x01(\tR\n" +
	"registerBy\x12\x10\n" +
	"\x03mac\x18\a \x01(\tR\x03mac\x12(\n" +
	"\x10os_major_version\x18\b \x01(\tR\x0eosMajorVersion\x12(\n" +
	"\x10os_minor_version\x18\t \x01(\tR\x0eosMinorVersion\x12\x18\n" +
	"\aaliases\x18\n" +
	" \x01(\tR\aaliases\x12\x1c\n" +
	"\taddresses\x18\v \x01(\tR\taddresses\"L\n" +
	"\x12ListAgentsResponse\x12 \n" +
	"\x04rows\x18\x01 \x03(\v2\f.agent.AgentR\x04rows\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xc3\x04\n" +
	"\x05Agent\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x03 \x01(\tR\x02os\x12%\n" +
	"\x06status\x18\x04 \x01(\x0e2\r.agent.StatusR\x06status\x12\x1a\n" +
	"\bplatform\x18\x05 \x01(\tR\bplatform\x12\x18\n" +
	"\aversion\x18\x06 \x01(\tR\aversion\x12\x1b\n" +
	"\tagent_key\x18\a \x01(\tR\bagentKey\x12\x0e\n" +
	"\x02id\x18\b \x01(\rR\x02id\x12\x1b\n" +
	"\tlast_seen\x18\t \x01(\tR\blastSeen\x12\x10\n" +
	"\x03mac\x18\n" +
	" \x01(\tR\x03mac\x12(\n" +
	"\x10os_major_version\x18\v \x01(\tR\x0eosMajorVersion\x12(\n" +
	"\x10os_minor_version\x18\f \x01(\tR\x0eosMinorVersion\x12\x18\n" +
	"\aaliases\x18\r \x01(\tR\aaliases\x12\x1c\n" +
	"\taddresses\x18\x0e \x01(\tR\taddresses\x12\x1d\n" +
	"\n" +
	"agent_uuid\x18\x0f \x01(\tR\tagentUuid\x12\x1b\n" +
	"\ttenant_id\x18\x10 \x01(\x03R\btenantId\x12-\n" +
	"\x12credential_version\x18\x11 \x01(\rR\x11credentialVersion\x12N\n" +
	"\x15credential_revoked_at\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampR\x13credentialRevokedAt\"\xe9\x01\n" +
	"\x1cCreateEnrollmentTokenRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\x03R\btenantId\x12\x1b\n" +
	"\tpolicy_id\x18\x02 \x01(\tR\bpolicyId\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x19\n" +
	"\bmax_uses\x18\x05 \x01(\x05R\amaxUses\x12\x1d\n" +
	"\n" +
	"created_by\x18\x06 \x01(\tR\tcreatedBy\"\xbb\x04\n" +
	"\x0fEnrollmentToken\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\x03R\btenantId\x12\x1b\n" +
	"\tpolicy_id\x18\x03 \x01(\tR\bpolicyId\x12\x1a\n" +
	"\bplatform\x18\x04 \x01(\tR\bplatform\x129\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x19\n" +
	"\bmax_uses\x18\x06 \x01(\x05R\amaxUses\x12\x1b\n" +
	"\tuse_count\x18\a \x01(\x05R\buseCount\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"created_by\x18\t \x01(\tR\tcreatedBy\x12<\n" +
	"\flast_used_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastUsedAt\x129\n" +
	"\n" +
	"revoked_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\trevokedAt\x12\x1d\n" +
	"\n" +
	"revoked_by\x18\f \x01(\tR\trevokedBy\x12+\n" +
	"\x11revocation_reason\x18\r \x01(\tR\x10revocationReason\x12\x18\n" +
	"\aversion\x18\x0e \x01(\x04R\aversion\x12\x16\n" +
	"\x06status\x18\x0f \x01(\tR\x06status\"m\n" +
	"\x1dCreateEnrollmentTokenResponse\x126\n" +
	"\n" +
	"enrollment\x18\x01 \x01(\v2\x16.agent.EnrollmentTokenR\n" +
	"enrollment\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"x\n" +
	"\x1bListEnrollmentTokensRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\x03R\btenantId\x12\x1f\n" +
	"\vpage_number\x18\x02 \x01(\x05R\n" +
	"pageNumber\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"`\n" +
	"\x1cListEnrollmentTokensResponse\x12*\n" +
	"\x04rows\x18\x01 \x03(\v2\x16.agent.EnrollmentTokenR\x04rows\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xad\x01\n" +
	"\x1cRevokeEnrollmentTokenRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\x03R\btenantId\x12\x1d\n" +
	"\n" +
	"revoked_by\x18\x03 \x01(\tR\trevokedBy\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12)\n" +
	"\x10expected_version\x18\x05 \x01(\x04R\x0fexpectedVersion\"~\n" +
	"\x16AgentCredentialRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\rR\aagentId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\x03R\btenantId\x12\x14\n" +
	"\x05actor\x18\x03 \x01(\tR\x05actor\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"\xcf\x01\n" +
	"\x17AgentCredentialResponse\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\rR\aagentId\x12\x1d\n" +
	"\n" +
	"agent_uuid\x18\x02 \x01(\tR\tagentUuid\x12-\n" +
	"\x12credential_version\x18\x03 \x01(\rR\x11credentialVersion\x12\x10\n" +
	"\x03key\x18\x04 \x01(\tR\x03key\x129\n" +
	"\n" +
	"revoked_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\trevokedAt\"\xb9\x03\n" +
	"\x14EnrollmentAuditEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\x03R\btenantId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x12\x14\n" +
	"\x05actor\x18\x04 \x01(\tR\x05actor\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x12\x19\n" +
	"\btoken_id\x18\x06 \x01(\tR\atokenId\x12\x19\n" +
	"\bagent_id\x18\a \x01(\rR\aagentId\x12\x1d\n" +
	"\n" +
	"agent_uuid\x18\b \x01(\tR\tagentUuid\x12\x1b\n" +
	"\tpolicy_id\x18\t \x01(\tR\bpolicyId\x12\x1a\n" +
	"\bplatform\x18\n" +
	" \x01(\tR\bplatform\x12-\n" +
	"\x12credential_version\x18\v \x01(\rR\x11credentialVersion\x12-\n" +
	"\x12enrollment_version\x18\f \x01(\x04R\x11enrollmentVersion\x12;\n" +
	"\voccurred_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\"\xd6\x01\n" +
	" ListEnrollmentAuditEventsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\x03R\btenantId\x12\x1f\n" +
	"\vpage_number\x18\x02 \x01(\x05R\n" +
	"pageNumber\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x19\n" +
	"\btoken_id\x18\x04 \x01(\tR\atokenId\x12\x1d\n" +
	"\n" +
	"agent_uuid\x18\x05 \x01(\tR\tagentUuid\x12\x1d\n" +
	"\n" +
	"event_type\x18\x06 \x01(\tR\teventType\"j\n" +
	"!ListEnrollmentAuditEventsResponse\x12/\n" +
	"\x04rows\x18\x01 \x03(\v2\x1b.agent.EnrollmentAuditEventR\x04rows\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\x86\x01\n" +
	"\x13BidirectionalStream\x12-\n" +
	"\acommand\x18\x01 \x01(\v2\x11.agent.UtmCommandH\x00R\acommand\x12.\n" +
	"\x06result\x18\x02 \x01(\v2\x14.agent.CommandResultH\x00R\x06resultB\x10\n" +
	"\x0estream_message\"\xe5\x01\n" +
	"\n" +
	"UtmCommand\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x1f\n" +
	"\vexecuted_by\x18\x03 \x01(\tR\n" +
	"executedBy\x12\x15\n" +
	"\x06cmd_id\x18\x04 \x01(\tR\x05cmdId\x12\x1f\n" +
	"\vorigin_type\x18\x05 \x01(\tR\n" +
	"originType\x12\x1b\n" +
	"\torigin_id\x18\x06 \x01(\tR\boriginId\x12\x16\n" +
	"\x06reason\x18\a \x01(\tR\x06reason\x12\x14\n" +
	"\x05shell\x18\b \x01(\tR\x05shell\"\x96\x01\n" +
	"\rCommandResult\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x16\n" +
	"\x06result\x18\x02 \x01(\tR\x06result\x12;\n" +
	"\vexecuted_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"executedAt\x12\x15\n" +
	"\x06cmd_id\x18\x04 \x01(\tR\x05cmdId\"[\n" +
	"\x1aListAgentsCommandsResponse\x12'\n" +
	"\x04rows\x18\x01 \x03(\v2\x13.agent.AgentCommandR\x04rows\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xa1\x03\n" +
	"\fAgentCommand\x129\n" +
	"\n" +
	"created_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\rR\aagentId\x12\x18\n" +
	"\acommand\x18\x04 \x01(\tR\acommand\x12@\n" +
	"\x0ecommand_status\x18\x05 \x01(\x0e2\x19.agent.AgentCommandStatusR\rcommandStatus\x12\x16\n" +
	"\x06result\x18\x06 \x01(\tR\x06result\x12\x1f\n" +
	"\vexecuted_by\x18\a \x01(\tR\n" +
	"executedBy\x12\x15\n" +
	"\x06cmd_id\x18\b \x01(\tR\x05cmdId\x12\x16\n" +
	"\x06reason\x18\t \x01(\tR\x06reason\x12\x1f\n" +
	"\vorigin_type\x18\n" +
	" \x01(\tR\n" +
	"originType\x12\x1b\n" +
	"\torigin_id\x18\v \x01(\tR\boriginId\"\xa5\x01\n" +
	"\x1eVerifyConnectorIdentityRequest\x12!\n" +
	"\fconnector_id\x18\x01 \x01(\rR\vconnectorId\x12#\n" +
	"\rpresented_key\x18\x02 \x01(\tR\fpresentedKey\x12;\n" +
	"\x0econnector_type\x18\x03 \x01(\x0e2\x14.agent.ConnectorTypeR\rconnectorType\"\xe8\x01\n" +
	"\x1fVerifyConnectorIdentityResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\x03R\btenantId\x12-\n" +
	"\x12credential_version\x18\x04 \x01(\rR\x11credentialVersion\x12\x18\n" +
	"\arevoked\x18\x05 \x01(\bR\arevoked\x12;\n" +
	"\x0econnector_type\x18\x06 \x01(\x0e2\x14.agent.ConnectorTypeR\rconnectorType\"\x9e\x01\n" +
	"!ListConnectorAuthorizationRequest\x12;\n" +
	"\x0econnector_type\x18\x01 \x01(\x0e2\x14.agent.ConnectorTypeR\rconnectorType\x12\x1f\n" +
	"\vpage_number\x18\x02 \x01(\x05R\n" +
	"pageNumber\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\xdf\x01\n" +
	"\x16ConnectorAuthorization\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\x03R\btenantId\x12\x18\n" +
	"\arevoked\x18\x04 \x01(\bR\arevoked\x12-\n" +
	"\x12credential_version\x18\x05 \x01(\rR\x11credentialVersion\x12;\n" +
	"\x0econnector_type\x18\x06 \x01(\x0e2\x14.agent.ConnectorTypeR\rconnectorType\"m\n" +
	"\"ListConnectorAuthorizationResponse\x121\n" +
	"\x04rows\x18\x01 \x03(\v2\x1d.agent.ConnectorAuthorizationR\x04rows\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total*W\n" +
	"\x12AgentCommandStatus\x12\x10\n" +
	"\fNOT_EXECUTED\x10\x00\x12\t\n" +
	"\x05QUEUE\x10\x01\x12\v\n" +
	"\aPENDING\x10\x02\x12\f\n" +
	"\bEXECUTED\x10\x03\x12\t\n" +
	"\x05ERROR\x10\x042\xc4\t\n" +
	"\fAgentService\x12;\n" +
	"\rRegisterAgent\x12\x13.agent.AgentRequest\x1a\x13.agent.AuthResponse\"\x00\x129\n" +
	"\vUpdateAgent\x12\x13.agent.AgentRequest\x1a\x13.agent.AuthResponse\"\x00\x12:\n" +
	"\vDeleteAgent\x12\x14.agent.DeleteRequest\x1a\x13.agent.AuthResponse\"\x00\x12=\n" +
	"\n" +
	"ListAgents\x12\x12.agent.ListRequest\x1a\x19.agent.ListAgentsResponse\"\x00\x12K\n" +
	"\vAgentStream\x12\x1a.agent.BidirectionalStream\x1a\x1a.agent.BidirectionalStream\"\x00(\x010\x01\x12L\n" +
	"\x11ListAgentCommands\x12\x12.agent.ListRequest\x1a!.agent.ListAgentsCommandsResponse\"\x00\x12d\n" +
	"\x15CreateEnrollmentToken\x12#.agent.CreateEnrollmentTokenRequest\x1a$.agent.CreateEnrollmentTokenResponse\"\x00\x12a\n" +
	"\x14ListEnrollmentTokens\x12\".agent.ListEnrollmentTokensRequest\x1a#.agent.ListEnrollmentTokensResponse\"\x00\x12V\n" +
	"\x15RevokeEnrollmentToken\x12#.agent.RevokeEnrollmentTokenRequest\x1a\x16.agent.EnrollmentToken\"\x00\x12X\n" +
	"\x15RotateAgentCredential\x12\x1d.agent.AgentCredentialRequest\x1a\x1e.agent.AgentCredentialResponse\"\x00\x12X\n" +
	"\x15RevokeAgentCredential\x12\x1d.agent.AgentCredentialRequest\x1a\x1e.agent.AgentCredentialResponse\"\x00\x12p\n" +
	"\x19ListEnrollmentAuditEvents\x12'.agent.ListEnrollmentAuditEventsRequest\x1a(.agent.ListEnrollmentAuditEventsResponse\"\x00\x12j\n" +
	"\x17VerifyConnectorIdentity\x12%.agent.VerifyConnectorIdentityRequest\x1a&.agent.VerifyConnectorIdentityResponse\"\x00\x12s\n" +
	"\x1aListConnectorAuthorization\x12(.agent.ListConnectorAuthorizationRequest\x1a).agent.ListConnectorAuthorizationResponse\"\x002O\n" +
	"\fPanelService\x12?\n" +
	"\x0eProcessCommand\x12\x11.agent.UtmCommand\x1a\x14.agent.CommandResult\"\x00(\x010\x01B*Z(github.com/hivearmor/agent-manager/agentb\x06proto3"

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData []byte
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)))
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_agent_proto_goTypes = []any{
	(AgentCommandStatus)(0),                    // 0: agent.AgentCommandStatus
	(*AgentRequest)(nil),                       // 1: agent.AgentRequest
	(*ListAgentsResponse)(nil),                 // 2: agent.ListAgentsResponse
	(*Agent)(nil),                              // 3: agent.Agent
	(*CreateEnrollmentTokenRequest)(nil),       // 4: agent.CreateEnrollmentTokenRequest
	(*EnrollmentToken)(nil),                    // 5: agent.EnrollmentToken
	(*CreateEnrollmentTokenResponse)(nil),      // 6: agent.CreateEnrollmentTokenResponse
	(*ListEnrollmentTokensRequest)(nil),        // 7: agent.ListEnrollmentTokensRequest
	(*ListEnrollmentTokensResponse)(nil),       // 8: agent.ListEnrollmentTokensResponse
	(*RevokeEnrollmentTokenRequest)(nil),       // 9: agent.RevokeEnrollmentTokenRequest
	(*AgentCredentialRequest)(nil),             // 10: agent.AgentCredentialRequest
	(*AgentCredentialResponse)(nil),            // 11: agent.AgentCredentialResponse
	(*EnrollmentAuditEvent)(nil),               // 12: agent.EnrollmentAuditEvent
	(*ListEnrollmentAuditEventsRequest)(nil),   // 13: agent.ListEnrollmentAuditEventsRequest
	(*ListEnrollmentAuditEventsResponse)(nil),  // 14: agent.ListEnrollmentAuditEventsResponse
	(*BidirectionalStream)(nil),                // 15: agent.BidirectionalStream
	(*UtmCommand)(nil),                         // 16: agent.UtmCommand
	(*CommandResult)(nil),                      // 17: agent.CommandResult
	(*ListAgentsCommandsResponse)(nil),         // 18: agent.ListAgentsCommandsResponse
	(*AgentCommand)(nil),                       // 19: agent.AgentCommand
	(*VerifyConnectorIdentityRequest)(nil),     // 20: agent.VerifyConnectorIdentityRequest
	(*VerifyConnectorIdentityResponse)(nil),    // 21: agent.VerifyConnectorIdentityResponse
	(*ListConnectorAuthorizationRequest)(nil),  // 22: agent.ListConnectorAuthorizationRequest
	(*ConnectorAuthorization)(nil),             // 23: agent.ConnectorAuthorization
	(*ListConnectorAuthorizationResponse)(nil), // 24: agent.ListConnectorAuthorizationResponse
	(Status)(0),                   // 25: agent.Status
	(*timestamppb.Timestamp)(nil), // 26: google.protobuf.Timestamp
	(ConnectorType)(0),            // 27: agent.ConnectorType
	(*DeleteRequest)(nil),         // 28: agent.DeleteRequest
	(*ListRequest)(nil),           // 29: agent.ListRequest
	(*AuthResponse)(nil),          // 30: agent.AuthResponse
}
var file_agent_proto_depIdxs = []int32{
	3,  // 0: agent.ListAgentsResponse.rows:type_name -> agent.Agent
	25, // 1: agent.Agent.status:type_name -> agent.Status
	26, // 2: agent.Agent.credential_revoked_at:type_name -> google.protobuf.Timestamp
	26, // 3: agent.CreateEnrollmentTokenRequest.expires_at:type_name -> google.protobuf.Timestamp
	26, // 4: agent.EnrollmentToken.expires_at:type_name -> google.protobuf.Timestamp
	26, // 5: agent.EnrollmentToken.created_at:type_name -> google.protobuf.Timestamp
	26, // 6: agent.EnrollmentToken.last_used_at:type_name -> google.protobuf.Timestamp
	26, // 7: agent.EnrollmentToken.revoked_at:type_name -> google.protobuf.Timestamp
	5,  // 8: agent.CreateEnrollmentTokenResponse.enrollment:type_name -> agent.EnrollmentToken
	5,  // 9: agent.ListEnrollmentTokensResponse.rows:type_name -> agent.EnrollmentToken
	26, // 10: agent.AgentCredentialResponse.revoked_at:type_name -> google.protobuf.Timestamp
	26, // 11: agent.EnrollmentAuditEvent.occurred_at:type_name -> google.protobuf.Timestamp
	12, // 12: agent.ListEnrollmentAuditEventsResponse.rows:type_name -> agent.EnrollmentAuditEvent
	16, // 13: agent.BidirectionalStream.command:type_name -> agent.UtmCommand
	17, // 14: agent.BidirectionalStream.result:type_name -> agent.CommandResult
	26, // 15: agent.CommandResult.executed_at:type_name -> google.protobuf.Timestamp
	19, // 16: agent.ListAgentsCommandsResponse.rows:type_name -> agent.AgentCommand
	26, // 17: agent.AgentCommand.created_at:type_name -> google.protobuf.Timestamp
	26, // 18: agent.AgentCommand.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 19: agent.AgentCommand.command_status:type_name -> agent.AgentCommandStatus
	27, // 20: agent.VerifyConnectorIdentityRequest.connector_type:type_name -> agent.ConnectorType
	27, // 21: agent.VerifyConnectorIdentityResponse.connector_type:type_name -> agent.ConnectorType
	27, // 22: agent.ListConnectorAuthorizationRequest.connector_type:type_name -> agent.ConnectorType
	27, // 23: agent.ConnectorAuthorization.connector_type:type_name -> agent.ConnectorType
	23, // 24: agent.ListConnectorAuthorizationResponse.rows:type_name -> agent.ConnectorAuthorization
	1,  // 25: agent.AgentService.RegisterAgent:input_type -> agent.AgentRequest
	1,  // 26: agent.AgentService.UpdateAgent:input_type -> agent.AgentRequest
	28, // 27: agent.AgentService.DeleteAgent:input_type -> agent.DeleteRequest
	29, // 28: agent.AgentService.ListAgents:input_type -> agent.ListRequest
	15, // 29: agent.AgentService.AgentStream:input_type -> agent.BidirectionalStream
	29, // 30: agent.AgentService.ListAgentCommands:input_type -> agent.ListRequest
	4,  // 31: agent.AgentService.CreateEnrollmentToken:input_type -> agent.CreateEnrollmentTokenRequest
	7,  // 32: agent.AgentService.ListEnrollmentTokens:input_type -> agent.ListEnrollmentTokensRequest
	9,  // 33: agent.AgentService.RevokeEnrollmentToken:input_type -> agent.RevokeEnrollmentTokenRequest
	10, // 34: agent.AgentService.RotateAgentCredential:input_type -> agent.AgentCredentialRequest
	10, // 35: agent.AgentService.RevokeAgentCredential:input_type -> agent.AgentCredentialRequest
	13, // 36: agent.AgentService.ListEnrollmentAuditEvents:input_type -> agent.ListEnrollmentAuditEventsRequest
	20, // 37: agent.AgentService.VerifyConnectorIdentity:input_type -> agent.VerifyConnectorIdentityRequest
	22, // 38: agent.AgentService.ListConnectorAuthorization:input_type -> agent.ListConnectorAuthorizationRequest
	16, // 39: agent.PanelService.ProcessCommand:input_type -> agent.UtmCommand
	30, // 40: agent.AgentService.RegisterAgent:output_type -> agent.AuthResponse
	30, // 41: agent.AgentService.UpdateAgent:output_type -> agent.AuthResponse
	30, // 42: agent.AgentService.DeleteAgent:output_type -> agent.AuthResponse
	2,  // 43: agent.AgentService.ListAgents:output_type -> agent.ListAgentsResponse
	15, // 44: agent.AgentService.AgentStream:output_type -> agent.BidirectionalStream
	18, // 45: agent.AgentService.ListAgentCommands:output_type -> agent.ListAgentsCommandsResponse
	6,  // 46: agent.AgentService.CreateEnrollmentToken:output_type -> agent.CreateEnrollmentTokenResponse
	8,  // 47: agent.AgentService.ListEnrollmentTokens:output_type -> agent.ListEnrollmentTokensResponse
	5,  // 48: agent.AgentService.RevokeEnrollmentToken:output_type -> agent.EnrollmentToken
	11, // 49: agent.AgentService.RotateAgentCredential:output_type -> agent.AgentCredentialResponse
	11, // 50: agent.AgentService.RevokeAgentCredential:output_type -> agent.AgentCredentialResponse
	14, // 51: agent.AgentService.ListEnrollmentAuditEvents:output_type -> agent.ListEnrollmentAuditEventsResponse
	21, // 52: agent.AgentService.VerifyConnectorIdentity:output_type -> agent.VerifyConnectorIdentityResponse
	24, // 53: agent.AgentService.ListConnectorAuthorization:output_type -> agent.ListConnectorAuthorizationResponse
	17, // 54: agent.PanelService.ProcessCommand:output_type -> agent.CommandResult
	40, // [40:55] is the sub-list for method output_type
	25, // [25:40] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	file_common_proto_init()
	file_agent_proto_msgTypes[14].OneofWrappers = []any{
		(*BidirectionalStream_Command)(nil),
		(*BidirectionalStream_Result)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		EnumInfos:         file_agent_proto_enumTypes,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
