import { existsSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { render, screen } from '@testing-library/react';
import { describe, it, expect } from 'vitest';

import { AiProvenanceFrame } from './AiProvenanceFrame';

const __dirname = dirname(fileURLToPath(import.meta.url));

describe('AiProvenanceFrame — conventions', () => {
  it('files exist + export', () => {
    expect(existsSync(join(__dirname, 'AiProvenanceFrame.tsx'))).toBe(true);
    expect(existsSync(join(__dirname, 'AiProvenanceFrame.css'))).toBe(true);
    expect(typeof AiProvenanceFrame).toBe('function');
  });

  it('no hardcoded hex; uses intelligence-violet', () => {
    const tsx = readFileSync(join(__dirname, 'AiProvenanceFrame.tsx'), 'utf-8');
    const css = readFileSync(join(__dirname, 'AiProvenanceFrame.css'), 'utf-8');
    expect(tsx.match(/#[0-9a-fA-F]{3,8}\b/)).toBeFalsy();
    expect(css.match(/#[0-9a-fA-F]{3,8}\b/)).toBeFalsy();
    expect(css).toContain('var(--ha-intelligence-primary)');
  });
});

describe('AiProvenanceFrame — render', () => {
  it('frames children with a default provenance label + caveat', () => {
    render(
      <AiProvenanceFrame>
        <p>AI summary text</p>
      </AiProvenanceFrame>,
    );
    expect(screen.getByRole('group', { name: 'AI-generated content' })).toBeInTheDocument();
    expect(screen.getByText('AI-generated')).toBeInTheDocument();
    expect(screen.getByText('AI summary text')).toBeInTheDocument();
    expect(screen.getByText('Verify before acting')).toBeInTheDocument();
  });

  it('uses a custom label and hides the caveat when off', () => {
    render(
      <AiProvenanceFrame label="Generated by Hive AI" caveat={false}>
        <span>x</span>
      </AiProvenanceFrame>,
    );
    expect(screen.getByText('Generated by Hive AI')).toBeInTheDocument();
    expect(screen.queryByText('Verify before acting')).not.toBeInTheDocument();
  });

  it('applies the subtle variant class', () => {
    const { container } = render(
      <AiProvenanceFrame variant="subtle">
        <span>x</span>
      </AiProvenanceFrame>,
    );
    expect(container.querySelector('.ha-provenance--subtle')).not.toBeNull();
  });
});
