import type { Meta, StoryObj } from '@storybook/react';

import { AiProvenanceFrame } from './AiProvenanceFrame';

/** Lifecycle: **alpha**. Codifies the AI provenance rule (design §5a/C) — wraps any AI output. */
const meta = {
  title: 'HaUI/AI Kit/AiProvenanceFrame',
  component: AiProvenanceFrame,
  tags: ['autodocs'],
  parameters: { layout: 'padded', lifecycle: 'alpha' },
} satisfies Meta<typeof AiProvenanceFrame>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Rule: Story = {
  args: {
    label: 'Generated by Hive AI',
    children: (
      <p style={{ margin: 0, font: 'var(--ha-type-body)' }}>
        This host shows brute-force auth followed by a successful login and SMB access to three
        peers — consistent with credential access into lateral movement.
      </p>
    ),
  },
};

export const Subtle: Story = {
  args: {
    variant: 'subtle',
    caveat: false,
    children: (
      <span style={{ font: 'var(--ha-type-compact)' }}>
        Suggested next step: isolate HOST-1000 pending review.
      </span>
    ),
  },
};

export const NoCaveat: Story = {
  args: { caveat: false, children: <span>AI-labeled content without the caveat footer.</span> },
};
