import { useEffect, useMemo, useState } from 'react';

import { useQuery } from '@tanstack/react-query';
import { Activity, AlertTriangle, ArrowRight, Building2, ChevronRight, CircleSlash2, Clock3, Fingerprint, KeyRound, LockKeyhole, Plus, RefreshCw, Search, ShieldCheck, ShieldQuestion, SlidersHorizontal, UserCog, UserRoundCheck, UsersRound, X } from 'lucide-react';
import { useNavigate } from 'react-router-dom';

import './IdentityAdministrationPage.css';
import { identityAdministrationService } from './identityAdministration.service';
import type { AccessReview, AdminTenant, FederationConnection, IdentityAdministrationInventory, IdentityAdministrationView, IdentityAuditEvent, IdentityPrincipal, IdentitySelection } from './identityAdministration.types';

import { HaIconButton } from '@/components/ha-icon-button';
import { HaStepper } from '@/components/ha-stepper';
import { StatusDock } from '@/components/status-dock';
import { useEpsStream } from '@/hooks/useEpsStream';
import { useAuthStore } from '@/store/auth.store';

const viewRoutes:Record<IdentityAdministrationView,string>={directory:'/admin/users',tenants:'/admin/tenants',access:'/admin/users?view=access',federation:'/admin/users?view=federation',activity:'/admin/users?view=activity'};
const fmtDate=(value:string|null|undefined):string=>value?new Intl.DateTimeFormat(undefined,{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}).format(new Date(value)):'Not reported';
const fmtNumber=(value:number|null|undefined):string=>value===null||value===undefined?'—':new Intl.NumberFormat().format(value);
const words=(value:string):string=>value.replace(/_/g,' ');
const roleLabel=(role:string):string=>words(role.replace(/^ROLE_/,'')).toLowerCase().replace(/(^|\s)\S/g,(value:string)=>value.toUpperCase());

export function IdentityAdministrationPage({initialView='directory'}:{initialView?:IdentityAdministrationView}):JSX.Element{
  const navigate=useNavigate();const eps=useEpsStream();const {hasRole}=useAuthStore();const canAdminister=hasRole('ROLE_ADMIN');
  const [view,setView]=useState<IdentityAdministrationView>(initialView);const [query,setQuery]=useState('');const [state,setState]=useState('all');const [selected,setSelected]=useState<IdentitySelection>();const [setup,setSetup]=useState<'invite'|'tenant'|'review'>();
  const inventoryQuery=useQuery({queryKey:['identity-administration'],queryFn:({signal})=>identityAdministrationService.list(signal),enabled:canAdminister,staleTime:30_000,refetchInterval:60_000});
  useEffect(()=>{const requested=new URLSearchParams(window.location.search).get('view') as IdentityAdministrationView|null;setView(requested&&requested in viewRoutes?requested:initialView);},[initialView]);
  const inventory=inventoryQuery.data;const rows=useMemo(()=>filterRows(view,inventory,query,state),[view,inventory,query,state]);
  useEffect(()=>{const listener=(event:KeyboardEvent):void=>{const tag=(event.target as HTMLElement).tagName;if(['INPUT','SELECT','TEXTAREA'].includes(tag))return;if(event.key==='Escape'){setSelected(undefined);setSetup(undefined);return;}if(!['j','k','J','K'].includes(event.key)||!rows.length)return;event.preventDefault();const current=rows.findIndex(item=>item.id===selected?.value.id);const next=event.key.toLowerCase()==='j'?Math.min(current+1,rows.length-1):Math.max(current<0?0:current-1,0);setSelected(toSelection(view,rows[next]));};window.addEventListener('keydown',listener);return()=>window.removeEventListener('keydown',listener);},[rows,selected,view]);
  const changeView=(next:IdentityAdministrationView):void=>{setView(next);setSelected(undefined);setQuery('');setState('all');navigate(viewRoutes[next]);};
  if(!canAdminister)return <section className="iam-page"><Header onRefresh={()=>undefined}/><PageState icon={<CircleSlash2/>} title="Identity administration access restricted" detail="Platform identity and tenant governance requires an administrator role."/></section>;
  const primaryAction=view==='directory'?{label:'Invite principal',run:()=>setSetup('invite')}:view==='tenants'?{label:'Onboard tenant',run:()=>setSetup('tenant')}:view==='access'?{label:'Schedule review',run:()=>setSetup('review')}:view==='federation'?{label:'Configure federation',run:()=>navigate('/admin/sso')}:undefined;
  return <section className="iam-page">
    <Header onRefresh={()=>inventoryQuery.refetch()} onCreate={primaryAction?.run} createLabel={primaryAction?.label}/>
    {identityAdministrationService.fixtureMode&&<div className="iam-trust"><ShieldCheck size={13}/><strong>Design fixture:</strong> fictional identity, tenant and access-governance records are enabled for visual review.<span>Production never receives these records.</span></div>}
    <Summary inventory={inventory}/><Tabs view={view} inventory={inventory} onChange={changeView}/><Toolbar view={view} query={query} state={state} onQuery={setQuery} onState={setState} onRefresh={()=>inventoryQuery.refetch()} snapshotAt={inventory?.snapshotAt}/>
    <main className="iam-main" data-drawer={Boolean(selected)}><section className="iam-workspace">
      {inventoryQuery.isLoading?<PageState icon={<Activity/>} title="Loading identity control plane" detail="Retrieving the authorized platform directory, tenant and federation projection."/>:inventoryQuery.isError?<PageState error icon={<AlertTriangle/>} title="Identity administration unavailable" detail={inventoryQuery.error instanceof Error?inventoryQuery.error.message:'The administration projection could not be loaded.'} action={()=>inventoryQuery.refetch()}/>:view==='directory'?<DirectoryTable rows={rows as IdentityPrincipal[]} selected={selected?.value.id} onSelect={value=>setSelected({kind:'user',value})}/>:view==='tenants'?<TenantTable rows={rows as AdminTenant[]} selected={selected?.value.id} onSelect={value=>setSelected({kind:'tenant',value})}/>:view==='access'?<ReviewTable rows={rows as AccessReview[]} selected={selected?.value.id} onSelect={value=>setSelected({kind:'review',value})}/>:view==='federation'?<FederationWorkspace rows={rows as FederationConnection[]} selected={selected?.value.id} onSelect={value=>setSelected({kind:'federation',value})} onOpen={target=>navigate(target)}/>:<ActivityTable rows={rows as IdentityAuditEvent[]} selected={selected?.value.id} onSelect={value=>setSelected({kind:'activity',value})}/>}
    </section>{selected&&<Detail selection={selected} onClose={()=>setSelected(undefined)} onNavigate={navigate}/>}</main>
    <div className="iam-status"><span><LockKeyhole size={11}/>Global, delegated and tenant-local authority remain separate</span><strong>{inventory?.partial?inventory.warnings[0]:identityAdministrationService.fixtureMode?'Fixture lifecycle · no identities changed':'Authorized identity projection current'}</strong><span>{inventory?.bounded?'Bounded fields':'Payload boundary not proven'}</span></div><StatusDock className="iam-status-dock" sseConnected={identityAdministrationService.fixtureMode||eps.connected} eps={identityAdministrationService.fixtureMode?12840:eps.eps} mode="historical" lastUpdated={inventoryQuery.dataUpdatedAt?new Date(inventoryQuery.dataUpdatedAt):undefined}/>
    {setup&&<SetupDialog kind={setup} fixture={identityAdministrationService.fixtureMode} onClose={()=>setSetup(undefined)}/>}
  </section>;
}

function Header({onRefresh,onCreate,createLabel}:{onRefresh:()=>void;onCreate?:()=>void;createLabel?:string}):JSX.Element{return <header className="iam-header"><div className="iam-header__identity"><span className="iam-header__mark"><UserCog size={18}/></span><div><span className="iam-eyebrow">ADMINISTRATION · IDENTITY CONTROL PLANE</span><h1>Identity &amp; Tenancy</h1></div></div><div className="iam-header__actions"><span className="iam-shortcut"><kbd>J</kbd>/<kbd>K</kbd> navigate <kbd>Esc</kbd> close</span><button className="iam-button" type="button" onClick={onRefresh}><RefreshCw size={13}/>Refresh</button>{onCreate&&createLabel&&<button className="iam-button iam-button--primary" type="button" onClick={onCreate}><Plus size={14}/>{createLabel}</button>}</div></header>}
function Summary({inventory}:{inventory?:IdentityAdministrationInventory}):JSX.Element{const values=[['Directory',inventory?.totalUsers,'authorized principals'],['Privileged',inventory?.privilegedUsers,'admin or MSSP authority'],['Inactive',inventory?.inactiveUsers,'access disabled'],['Tenants',inventory?.totalTenants,'platform inventory'],['Reviews due',inventory?.reviewsDue,'recertification work'],['Federation',inventory?.federation.filter(item=>item.state==='enabled').length,'enabled connections']] as const;return <section className="iam-summary" aria-label="Identity administration summary">{values.map(([label,value,note])=><div key={label} data-tone={label==='Reviews due'&&value?'warning':label==='Inactive'&&value?'danger':undefined}><span>{label}</span><strong>{fmtNumber(value)}</strong><small>{note}</small></div>)}</section>}
function Tabs({view,inventory,onChange}:{view:IdentityAdministrationView;inventory?:IdentityAdministrationInventory;onChange:(view:IdentityAdministrationView)=>void}):JSX.Element{const tabs=[{id:'directory',label:'Directory',icon:<UsersRound size={13}/>,count:inventory?.users.length??0},{id:'tenants',label:'Tenants',icon:<Building2 size={13}/>,count:inventory?.tenants.length??0},{id:'access',label:'Access reviews',icon:<UserRoundCheck size={13}/>,count:inventory?.reviews.length??0},{id:'federation',label:'Federation',icon:<Fingerprint size={13}/>,count:inventory?.federation.length??0},{id:'activity',label:'Audit activity',icon:<Clock3 size={13}/>,count:inventory?.activity.length??0}] as const;return <nav className="iam-tabs" aria-label="Identity administration workspace">{tabs.map(tab=><button key={tab.id} role="tab" aria-selected={view===tab.id} type="button" onClick={()=>onChange(tab.id)}>{tab.icon}{tab.label}<small>{tab.count}</small></button>)}</nav>}
function Toolbar({view,query,state,onQuery,onState,onRefresh,snapshotAt}:{view:IdentityAdministrationView;query:string;state:string;onQuery:(value:string)=>void;onState:(value:string)=>void;onRefresh:()=>void;snapshotAt?:string}):JSX.Element{return <div className="iam-toolbar"><label className="iam-search"><Search size={13}/><input aria-label={`Search ${view}`} value={query} onChange={event=>onQuery(event.target.value)} placeholder={`Search ${view.replace('access','reviews')}…`}/><kbd>/</kbd></label><label className="iam-filter"><SlidersHorizontal size={12}/><select aria-label={`Filter ${view} state`} value={state} onChange={event=>onState(event.target.value)}><option value="all">All states</option><option value="active">Active</option><option value="enabled">Enabled</option><option value="due">Due</option><option value="overdue">Overdue</option><option value="inactive">Inactive</option><option value="disabled">Disabled</option><option value="suspended">Suspended</option><option value="unknown">Unknown</option></select></label><HaIconButton className="iam-icon-button" aria-label="Refresh current view" onClick={onRefresh} icon={<RefreshCw size={13}/>}/><span className="iam-toolbar__end">Snapshot {fmtDate(snapshotAt)} · server authority only</span></div>}

function DirectoryTable({rows,selected,onSelect}:{rows:IdentityPrincipal[];selected?:string;onSelect:(row:IdentityPrincipal)=>void}):JSX.Element{return <TableState empty={!rows.length} label="principals"><table className="iam-table"><thead><tr><th>Principal</th><th>Sign-in source</th><th>Platform roles</th><th>Tenant access</th><th>MFA</th><th>Review</th><th>Last sign-in</th><th>State</th><th/></tr></thead><tbody>{rows.map(row=><tr key={row.id} tabIndex={0} data-selected={row.id===selected} onClick={()=>onSelect(row)} onKeyDown={event=>activate(event,()=>onSelect(row))}><td><div className="iam-cell-title"><Avatar label={row.displayName}/><div><strong>{row.displayName}</strong><small>{row.email}</small></div></div></td><td><SourceBadge source={row.source}/></td><td><div className="iam-badges">{row.roles.slice(0,2).map(role=><span className="iam-badge" key={role}>{roleLabel(role)}</span>)}{row.roles.length>2&&<span className="iam-badge">+{row.roles.length-2}</span>}</div></td><td>{row.tenantCount===null?'Not reported':`${row.tenantCount} tenant${row.tenantCount===1?'':'s'}`}</td><td><StateBadge state={row.mfaState} label={words(row.mfaState)}/></td><td><StateBadge state={row.reviewState} label={words(row.reviewState)}/></td><td className="iam-mono">{fmtDate(row.lastSignInAt)}</td><td><StateBadge state={row.state} label={row.state}/></td><td><ChevronRight size={13}/></td></tr>)}</tbody></table></TableState>}
function TenantTable({rows,selected,onSelect}:{rows:AdminTenant[];selected?:string;onSelect:(row:AdminTenant)=>void}):JSX.Element{return <TableState empty={!rows.length} label="tenants"><table className="iam-table"><thead><tr><th>Tenant</th><th>Administration</th><th>Members</th><th>Privileged</th><th>Federation</th><th>Licence</th><th>Last activity</th><th>State</th><th/></tr></thead><tbody>{rows.map(row=><tr key={row.id} tabIndex={0} data-selected={row.id===selected} onClick={()=>onSelect(row)} onKeyDown={event=>activate(event,()=>onSelect(row))}><td><div className="iam-cell-title"><span className="iam-tenant-icon"><Building2 size={14}/></span><div><strong>{row.name}</strong><small>{row.prefix} · {row.domain??'domain not reported'}</small></div></div></td><td><ScopeBadge value={row.administration}/></td><td className="iam-mono">{fmtNumber(row.members)}</td><td className="iam-mono">{fmtNumber(row.privilegedMembers)}</td><td className="iam-mono">{fmtNumber(row.identityProviders)}</td><td className="iam-mono">{fmtDate(row.licenceExpiresAt)}</td><td className="iam-mono">{fmtDate(row.lastActivityAt)}</td><td><StateBadge state={row.state} label={row.state}/></td><td><ChevronRight size={13}/></td></tr>)}</tbody></table></TableState>}
function ReviewTable({rows,selected,onSelect}:{rows:AccessReview[];selected?:string;onSelect:(row:AccessReview)=>void}):JSX.Element{if(!rows.length)return <ContractState icon={<UserRoundCheck/>} title="Access certification is not yet authoritative" detail="The backend does not expose scheduled reviews, reviewer assignments, recommendations, decisions, expiry enforcement or an immutable review ledger."/>;return <TableState empty={false} label="reviews"><table className="iam-table"><thead><tr><th>Access review</th><th>Scope</th><th>Reviewer</th><th>Cadence</th><th>Progress</th><th>Due</th><th>Privilege</th><th>State</th><th/></tr></thead><tbody>{rows.map(row=><tr key={row.id} tabIndex={0} data-selected={row.id===selected} onClick={()=>onSelect(row)} onKeyDown={event=>activate(event,()=>onSelect(row))}><td><div className="iam-cell-title"><span className="iam-review-icon"><UserRoundCheck size={14}/></span><div><strong>{row.name}</strong><small>{row.id}</small></div></div></td><td>{row.scope}</td><td>{row.reviewer}</td><td>{row.cadence}</td><td><Progress value={row.decisionsComplete} total={row.decisionsTotal}/></td><td className="iam-mono">{fmtDate(row.dueAt)}</td><td>{row.highPrivilege?<span className="iam-badge iam-badge--warning">High privilege</span>:'Standard'}</td><td><StateBadge state={row.state} label={row.state}/></td><td><ChevronRight size={13}/></td></tr>)}</tbody></table></TableState>}
function FederationWorkspace({rows,selected,onSelect,onOpen}:{rows:FederationConnection[];selected?:string;onSelect:(row:FederationConnection)=>void;onOpen:(route:string)=>void}):JSX.Element{return <div className="iam-federation"><section className="iam-federation__guide"><div><Fingerprint size={17}/><span><strong>Authentication</strong><small>OIDC authorization-code flow with PKCE</small></span></div><ArrowRight/><div><ShieldCheck size={17}/><span><strong>Provisioning</strong><small>SCIM lifecycle and group mapping</small></span></div><ArrowRight/><div><UserRoundCheck size={17}/><span><strong>Governance</strong><small>Access review and immutable evidence</small></span></div></section><section className="iam-section-head"><div><strong>Federated identity connections</strong><span>Secrets are write-only; tenant mappings and claim policy require server authority</span></div><div><button className="iam-button" type="button" onClick={()=>onOpen('/admin/sso')}>OIDC settings</button><button className="iam-button" type="button" onClick={()=>onOpen('/admin/scim')}>SCIM settings</button></div></section><div className="iam-federation-grid">{rows.map(row=><button key={row.id} data-selected={selected===row.id} type="button" onClick={()=>onSelect(row)}><ProtocolIcon protocol={row.protocol}/><div><strong>{row.name}</strong><span>{row.scope}</span><small>{row.endpointLabel}</small></div><StateBadge state={row.state} label={words(row.state)}/><footer><span>Last activity {fmtDate(row.lastActivityAt)}</span><ChevronRight size={12}/></footer></button>)}</div>{!rows.length&&<ContractState icon={<Fingerprint/>} title="No federation configuration loaded" detail="Configure an OIDC identity provider or generate the one-time SCIM provisioning credential."/>}</div>}
function ActivityTable({rows,selected,onSelect}:{rows:IdentityAuditEvent[];selected?:string;onSelect:(row:IdentityAuditEvent)=>void}):JSX.Element{if(!rows.length)return <ContractState icon={<Clock3/>} title="Immutable identity audit is not available" detail="Current user and federation mutations do not return a bounded, tenant-aware identity governance ledger to this page."/>;return <TableState empty={false} label="audit events"><table className="iam-table"><thead><tr><th>Occurred</th><th>Actor</th><th>Action</th><th>Target</th><th>Scope</th><th>Reason</th><th>Result</th><th/></tr></thead><tbody>{rows.map(row=><tr key={row.id} tabIndex={0} data-selected={row.id===selected} onClick={()=>onSelect(row)} onKeyDown={event=>activate(event,()=>onSelect(row))}><td className="iam-mono">{fmtDate(row.occurredAt)}</td><td>{row.actor}</td><td><strong>{row.action}</strong></td><td>{row.target}</td><td>{row.scope}</td><td>{row.reason}</td><td><StateBadge state={row.result} label={row.result}/></td><td><ChevronRight size={13}/></td></tr>)}</tbody></table></TableState>}

function Detail({selection,onClose,onNavigate}:{selection:IdentitySelection;onClose:()=>void;onNavigate:(route:string)=>void}):JSX.Element{const title=selection.kind==='user'?selection.value.displayName:selection.kind==='tenant'?selection.value.name:selection.kind==='federation'?selection.value.name:selection.kind==='review'?selection.value.name:selection.value.action;return <aside className="iam-drawer" aria-label={`${title} context`}><header><div><span>{selection.kind.toUpperCase()} CONTEXT</span><strong>{title}</strong></div><HaIconButton className="iam-icon-button" onClick={onClose} aria-label="Close context" icon={<X size={14}/>}/></header><div className="iam-drawer__scroll">{selection.kind==='user'?<UserDetail value={selection.value}/>:selection.kind==='tenant'?<TenantDetail value={selection.value}/>:selection.kind==='federation'?<FederationDetail value={selection.value}/>:selection.kind==='review'?<ReviewDetail value={selection.value}/>:<AuditDetail value={selection.value}/>}<section className="iam-notice"><ShieldQuestion size={14}/><span>Displayed access is an administrative projection, not authorization to act. Mutations require server-side permission, scope, version and audit validation.</span></section></div><footer>{selection.kind==='federation'&&<button className="iam-button iam-button--primary" type="button" onClick={()=>onNavigate(selection.value.protocol==='OIDC'?'/admin/sso':'/admin/scim')}>Open configuration</button>}<button className="iam-button" type="button" onClick={onClose}>Close</button></footer></aside>}
function UserDetail({value}:{value:IdentityPrincipal}):JSX.Element{return <><section className="iam-profile"><Avatar label={value.displayName}/><div><strong>{value.displayName}</strong><span>{value.login}</span><small>{value.email}</small></div><StateBadge state={value.state} label={value.state}/></section><DetailCard title="Authority boundary" rows={[['Platform roles',value.roles.map(roleLabel).join(', ')||'None'],['Tenant memberships',value.tenantCount===null?'Not reported':String(value.tenantCount)],['Sign-in source',value.source.toUpperCase()],['MFA',words(value.mfaState)]]}/><DetailCard title="Lifecycle" rows={[['Last sign-in',fmtDate(value.lastSignInAt)],['Created',fmtDate(value.createdAt)],['Modified',fmtDate(value.modifiedAt)],['Access review',words(value.reviewState)]]}/><div className="iam-drawer-actions"><button className="iam-button" type="button" disabled>Review access</button><button className="iam-button" type="button" disabled>Suspend</button></div></>}
function TenantDetail({value}:{value:AdminTenant}):JSX.Element{return <><section className="iam-profile"><span className="iam-tenant-icon"><Building2 size={16}/></span><div><strong>{value.name}</strong><span>{value.prefix}</span><small>{value.domain??'Domain not reported'}</small></div><StateBadge state={value.state} label={value.state}/></section><DetailCard title="Administration" rows={[['Control plane',words(value.administration)],['Members',fmtNumber(value.members)],['Privileged',fmtNumber(value.privilegedMembers)],['Federation',fmtNumber(value.identityProviders)]]}/><DetailCard title="Lifecycle" rows={[['Last activity',fmtDate(value.lastActivityAt)],['Licence expiry',fmtDate(value.licenceExpiresAt)],['Tenant ID',value.id],['Data scope','Server-authorized tenant'] ]}/><div className="iam-drawer-actions"><button className="iam-button" type="button" disabled>Manage membership</button><button className="iam-button" type="button" disabled>Review delegation</button></div></>}
function FederationDetail({value}:{value:FederationConnection}):JSX.Element{return <><section className="iam-profile"><ProtocolIcon protocol={value.protocol}/><div><strong>{value.name}</strong><span>{value.protocol} · {value.scope}</span><small>{value.endpointLabel}</small></div><StateBadge state={value.state} label={words(value.state)}/></section><DetailCard title="Trust configuration" rows={[['Protocol',value.protocol],['Owner',value.owner??'Not reported'],['Secret',words(value.secretState)],['Last activity',fmtDate(value.lastActivityAt)]]}/><section className="iam-notice"><KeyRound size={14}/><span>Client secrets and SCIM bearer tokens never render after initial write. Rotation must invalidate prior credentials and produce audit evidence.</span></section></>}
function ReviewDetail({value}:{value:AccessReview}):JSX.Element{return <><section className="iam-profile"><span className="iam-review-icon"><UserRoundCheck size={16}/></span><div><strong>{value.name}</strong><span>{value.scope}</span><small>{value.reviewer}</small></div><StateBadge state={value.state} label={value.state}/></section><Progress value={value.decisionsComplete} total={value.decisionsTotal}/><DetailCard title="Review policy" rows={[['Reviewer',value.reviewer],['Cadence',value.cadence],['Due',fmtDate(value.dueAt)],['High privilege',value.highPrivilege?'Yes':'No']]}/><div className="iam-drawer-actions"><button className="iam-button" type="button" disabled>Open decisions</button><button className="iam-button" type="button" disabled>Export evidence</button></div></>}
function AuditDetail({value}:{value:IdentityAuditEvent}):JSX.Element{return <><section className="iam-profile"><span className="iam-review-icon"><Clock3 size={16}/></span><div><strong>{value.action}</strong><span>{value.actor} → {value.target}</span><small>{fmtDate(value.occurredAt)}</small></div><StateBadge state={value.result} label={value.result}/></section><DetailCard title="Audit evidence" rows={[['Scope',value.scope],['Reason',value.reason],['Correlation',value.correlationId??'Not reported'],['Event ID',value.id]]}/></>}
function DetailCard({title,rows}:{title:string;rows:readonly (readonly [string,string])[]}):JSX.Element{return <section className="iam-card"><h3>{title}</h3><dl>{rows.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></section>}

function SetupDialog({kind,fixture,onClose}:{kind:'invite'|'tenant'|'review';fixture:boolean;onClose:()=>void}):JSX.Element{const copy=kind==='invite'?{eyebrow:'IDENTITY LIFECYCLE',title:'Invite a principal',description:'Stage a tenant-scoped invitation with role, expiry and reviewer context.',fields:[['Email address','maya@example.test'],['Initial platform role','Analyst'],['Tenant scope','Select authorized tenant'],['Access expiry','No expiry configured']]}:kind==='tenant'?{eyebrow:'TENANT LIFECYCLE',title:'Onboard a tenant',description:'Define the tenant boundary, ownership and initial federation posture before provisioning.',fields:[['Tenant name','Example organization'],['Immutable prefix','example-org'],['Administration model','Tenant local'],['Primary owner','owner@example.test']]}:{eyebrow:'ACCESS GOVERNANCE',title:'Schedule an access review',description:'Define the review population, accountable reviewer, recurrence and automatic outcome policy.',fields:[['Review name','Privileged access review'],['Scope','Platform administrators'],['Reviewer','Security Governance'],['Cadence','Quarterly']]};return <div className="iam-dialog-backdrop" role="presentation"><section className="iam-dialog" role="dialog" aria-modal="true" aria-labelledby="iam-dialog-title"><header><div><span>{copy.eyebrow}</span><h2 id="iam-dialog-title">{copy.title}</h2></div><HaIconButton className="iam-icon-button" onClick={onClose} aria-label="Close workflow" icon={<X size={14}/>}/></header><div className="iam-dialog__body"><p>{copy.description}</p><HaStepper className="iam-stepper" ariaLabel={copy.title} current={0} steps={[{id:'define',label:'Define'},{id:'scope',label:'Scope'},{id:'review',label:'Review'},{id:'authorize',label:'Authorize'},{id:'complete',label:'Complete'}]}/><div className="iam-form-grid">{copy.fields.map(([label,placeholder],index)=><label className={index>1?'iam-field iam-field--wide':'iam-field'} key={label}><span>{label}</span>{label.includes('role')||label==='Administration model'||label==='Cadence'?<select defaultValue=""><option value="" disabled>{placeholder}</option></select>:<input placeholder={placeholder}/>}</label>)}</div><section className="iam-notice"><ShieldCheck size={14}/><span>{fixture?'Visual fixture only. Completing this review will not create, invite or authorize a record.':'The authoritative backend workflow is incomplete. Inputs can be reviewed, but submission remains disabled.'}</span></section></div><footer><button className="iam-button" type="button" onClick={onClose}>Cancel</button><button className="iam-button iam-button--primary" type="button" disabled>Continue to scope</button></footer></section></div>}

function ProtocolIcon({protocol}:{protocol:FederationConnection['protocol']}):JSX.Element{return <span className="iam-protocol-icon">{protocol==='OIDC'?<Fingerprint size={17}/>:<KeyRound size={17}/>}</span>}
function Avatar({label}:{label:string}):JSX.Element{return <span className="iam-avatar" aria-hidden="true">{label.split(/\s+/).map(part=>part[0]).join('').slice(0,2).toUpperCase()}</span>}
function SourceBadge({source}:{source:IdentityPrincipal['source']}):JSX.Element{return <span className="iam-source"><Fingerprint size={11}/>{source.toUpperCase()}</span>}
function ScopeBadge({value}:{value:AdminTenant['administration']}):JSX.Element{return <span className="iam-source"><Building2 size={11}/>{words(value)}</span>}
function StateBadge({state,label}:{state:string;label:string}):JSX.Element{return <span className="iam-state" data-state={state}><i/>{label}</span>}
function Progress({value,total}:{value:number;total:number}):JSX.Element{const pct=total?Math.round(value/total*100):0;return <div className="iam-progress" aria-label={`${value} of ${total} decisions complete`}><span><i style={{width:`${pct}%`}}/></span><small>{value}/{total} · {pct}%</small></div>}
function TableState({empty,label,children}:{empty:boolean;label:string;children:React.ReactNode}):JSX.Element{return empty?<ContractState icon={<Search/>} title={`No ${label} match this view`} detail="Adjust the search or state filter. Unknown values remain unknown until returned by the server."/>:<div className="iam-table-wrap">{children}</div>}
function ContractState({icon,title,detail}:{icon:JSX.Element;title:string;detail:string}):JSX.Element{return <div className="iam-contract-state">{icon}<strong>{title}</strong><span>{detail}</span><small><LockKeyhole size={11}/>No browser-inferred authority</small></div>}
function PageState({icon,title,detail,error,action}:{icon:JSX.Element;title:string;detail:string;error?:boolean;action?:()=>void}):JSX.Element{return <div className="iam-empty" data-error={error}>{icon}<strong>{title}</strong><span>{detail}</span>{action&&<button className="iam-button" type="button" onClick={action}>Retry</button>}</div>}
function filterRows(view:IdentityAdministrationView,inventory:IdentityAdministrationInventory|undefined,query:string,state:string):Array<IdentityPrincipal|AdminTenant|FederationConnection|AccessReview|IdentityAuditEvent>{if(!inventory)return[];const source=view==='directory'?inventory.users:view==='tenants'?inventory.tenants:view==='access'?inventory.reviews:view==='federation'?inventory.federation:inventory.activity;const needle=query.trim().toLowerCase();return source.filter(item=>(state==='all'||('state'in item&&item.state===state)||('result'in item&&item.result===state))&&(!needle||JSON.stringify(item).toLowerCase().includes(needle)))}
function toSelection(view:IdentityAdministrationView,value:IdentityPrincipal|AdminTenant|FederationConnection|AccessReview|IdentityAuditEvent):IdentitySelection{if(view==='directory')return{kind:'user',value:value as IdentityPrincipal};if(view==='tenants')return{kind:'tenant',value:value as AdminTenant};if(view==='access')return{kind:'review',value:value as AccessReview};if(view==='federation')return{kind:'federation',value:value as FederationConnection};return{kind:'activity',value:value as IdentityAuditEvent}}
function activate(event:React.KeyboardEvent,action:()=>void):void{if(event.key==='Enter'||event.key===' '){event.preventDefault();action()}}
