receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  filelog:
    include: ["/var/log/syslog", "/var/log/auth.log"]
    start_at: end

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  resource:
    attributes:
      - key: collector.source
        value: otel-collector
        action: upsert

exporters:
  otlp/hivearmor:
    endpoint: eventprocessor-worker:4317
    tls:
      insecure: true
    compression: none

service:
  pipelines:
    logs:
      receivers: [otlp, filelog]
      processors: [batch, resource]
      exporters: [otlp/hivearmor]
